import type { CareerInfo, LanguageInfo, OccupationInfo } from "./types";

// ============================================================
// CAREERS — 8 main + sub-paths for software-engineering
// ============================================================

export const CAREERS: CareerInfo[] = [
  {
    id: "software-engineering",
    label: "Software Engineering",
    tagline: "Build robust systems that scale",
    description:
      "Software engineers design, build, test, and maintain the applications and systems that power modern life. You'll work across the stack — from architecture and APIs to deployment and observability — collaborating with product, design, and operations teams to ship reliable software.",
    recommendedLanguages: ["python", "javascript", "typescript", "java", "sql", "cpp", "csharp", "go", "rust", "git", "docker", "nodejs", "kotlin"],
    skills: ["Data structures & algorithms", "System design", "Version control (Git)", "Testing", "CI/CD basics"],
    demand: 5,
    salaryRange: "$75K – $200K+ globally",
    topCompanies: ["Google", "Microsoft", "Amazon", "Meta", "Apple", "Stripe", "Airbnb"],
    category: "engineering",
    subPaths: [
      { id: "general", label: "General SE", description: "Balanced full-stack with strong fundamentals." },
      { id: "backend", label: "Backend", description: "APIs, databases, distributed systems, performance." },
      { id: "frontend", label: "Frontend", description: "UI engineering, accessibility, design systems." },
      { id: "fullstack", label: "Full-stack", description: "End-to-end product engineering." },
      { id: "devops", label: "DevOps", description: "Infrastructure, automation, reliability." },
    ],
  },
  {
    id: "web-dev",
    label: "Web Development",
    tagline: "Craft fast, beautiful web experiences",
    description:
      "Web developers build the sites and web apps people use every day. You'll master HTML, CSS, JavaScript, modern frameworks, performance optimization, and accessibility — turning designs into responsive, interactive products.",
    recommendedLanguages: ["javascript", "typescript", "html", "css", "react", "nextjs", "nodejs", "vue", "angular", "svelte", "tailwind", "express", "graphql", "bootstrap", "jquery"],
    skills: ["HTML/CSS", "Responsive design", "Accessibility", "Browser APIs", "Performance"],
    demand: 5,
    salaryRange: "$60K – $160K+ globally",
    topCompanies: ["Vercel", "Shopify", "Figma", "Notion", "Linear", "Stripe"],
    category: "engineering",
  },
  {
    id: "cloud-devops",
    label: "Cloud / DevOps",
    tagline: "Automate and scale infrastructure",
    description:
      "Cloud/DevOps engineers own the platforms that run software. You'll work with containers, orchestration (Kubernetes), infrastructure-as-code, observability, CI/CD pipelines, and cloud providers like AWS, GCP, and Azure to keep systems reliable and cost-efficient.",
    recommendedLanguages: ["python", "bash", "go", "typescript", "docker", "kubernetes", "terraform", "yaml", "powershell"],
    skills: ["Linux", "Docker", "Kubernetes", "Terraform", "AWS/GCP/Azure", "Monitoring"],
    demand: 5,
    salaryRange: "$90K – $200K+ globally",
    topCompanies: ["AWS", "HashiCorp", "Datadog", "Cloudflare", "GitLab", "Red Hat"],
    category: "systems",
  },
  {
    id: "data-science",
    label: "Data Science",
    tagline: "Turn data into decisions",
    description:
      "Data scientists extract insights from data using statistics, programming, and machine learning. You'll clean and analyze datasets, build predictive models, create dashboards, and communicate findings to drive product and business decisions.",
    recommendedLanguages: ["python", "r", "sql", "julia", "sas", "tableau", "powerbi"],
    skills: ["Statistics", "Pandas/NumPy", "Visualization", "SQL", "ML basics", "Communication"],
    demand: 5,
    salaryRange: "$80K – $180K+ globally",
    topCompanies: ["Netflix", "Spotify", "Airbnb", "Meta", "Stitch Fix", "Uber"],
    category: "data",
  },
  {
    id: "ai-ml",
    label: "AI / Machine Learning",
    tagline: "Build intelligent systems",
    description:
      "AI/ML engineers design and deploy machine learning models and AI systems. You'll work with deep learning frameworks, large language models, MLOps pipelines, and production inference — turning research into shipped products.",
    recommendedLanguages: ["python", "rust", "cpp", "julia", "r", "cuda", "pytorch", "tensorflow"],
    skills: ["Linear algebra", "PyTorch/TensorFlow", "MLOps", "LLM tooling", "Statistics"],
    demand: 5,
    salaryRange: "$100K – $250K+ globally",
    topCompanies: ["OpenAI", "Anthropic", "DeepMind", "Hugging Face", "NVIDIA", "Tesla"],
    category: "data",
  },
  {
    id: "cybersecurity",
    label: "Cybersecurity",
    tagline: "Defend systems and data",
    description:
      "Cybersecurity professionals protect organizations from threats. You'll learn networking, cryptography, offensive and defensive security, secure coding, and incident response — working as a pentester, SOC analyst, or security engineer.",
    recommendedLanguages: ["python", "bash", "c", "rust", "assembly", "powershell", "ruby", "lua"],
    skills: ["Networking", "Cryptography", "OWASP", "Forensics", "Threat modeling"],
    demand: 5,
    salaryRange: "$80K – $190K+ globally",
    topCompanies: ["CrowdStrike", "Cloudflare", "Palo Alto Networks", "Mandiant", "Okta"],
    category: "systems",
  },
  {
    id: "mobile-dev",
    label: "Mobile Development",
    tagline: "Build apps for iOS and Android",
    description:
      "Mobile developers create native and cross-platform apps. You'll learn Swift/Kotlin for native, or React Native/Flutter for cross-platform, and master mobile UX, offline-first design, app store deployment, and performance.",
    recommendedLanguages: ["kotlin", "swift", "dart", "typescript", "java", "csharp", "objective-c", "react-native"],
    skills: ["Mobile UX", "Offline-first", "App store deployment", "Mobile performance"],
    demand: 4,
    salaryRange: "$70K – $170K+ globally",
    topCompanies: ["Apple", "Google", "Instagram", "Square", "Duolingo", "Discord"],
    category: "engineering",
  },
  {
    id: "game-dev",
    label: "Game Development",
    tagline: "Build interactive worlds",
    description:
      "Game developers create interactive experiences for console, PC, mobile, and web. You'll work with engines like Unity or Unreal, learn C# or C++, master real-time graphics, physics, and gameplay programming.",
    recommendedLanguages: ["cpp", "csharp", "python", "lua", "gdscript", "javascript", "glsl"],
    skills: ["Unity/Unreal", "Linear algebra", "Physics", "Shaders", "Gameplay programming"],
    demand: 3,
    salaryRange: "$60K – $150K+ globally",
    topCompanies: ["Epic Games", "Unity", "Riot", "Naughty Dog", "Valve", "Roblox"],
    category: "creative",
  },
  {
    id: "hardware-embedded",
    label: "Hardware / Embedded",
    tagline: "Program the physical world",
    description:
      "Embedded engineers write firmware for microcontrollers, IoT devices, automotive systems, and robotics. You'll work close to the metal with C/C++, real-time operating systems, hardware interfaces, and low-level optimization.",
    recommendedLanguages: ["c", "cpp", "python", "rust", "assembly", "verilog", "vhdl", "arduino"],
    skills: ["Microcontrollers", "RTOS", "Digital electronics", "Debugging", "Memory management"],
    demand: 4,
    salaryRange: "$80K – $170K+ globally",
    topCompanies: ["Tesla", "SpaceX", "Apple", "Bosch", "STM", "NXP"],
    category: "systems",
  },
];

// ============================================================
// LANGUAGES & FRAMEWORKS — 19+ entries with rich metadata
// ============================================================

export const LANGUAGES: LanguageInfo[] = [
  {
    id: "python",
    name: "Python",
    type: "language",
    tagline: "Versatile, readable, ubiquitous",
    description:
      "Python is a high-level, general-purpose language loved for its clean syntax and enormous ecosystem. It powers data science, AI/ML, web backends, automation, scientific computing, and education — making it the most-recommended first language today.",
    demand: 5,
    salaryImpact: "+15-25% over entry-level baseline",
    useCases: ["Web backends (Django/FastAPI)", "Data science & ML", "Automation & scripting", "Scientific computing", "Education"],
    difficulty: 1,
    learningCurve: "Gentle — beginners ship real scripts in hours.",
    trend: "rising",
    topCompanies: ["Google", "Netflix", "Instagram", "Spotify", "OpenAI", "Dropbox"],
    careers: ["software-engineering", "cloud-devops", "data-science", "ai-ml", "cybersecurity"],
    icon: "🐍",
    color: "#3776AB",
  },
  {
    id: "javascript",
    name: "JavaScript",
    type: "language",
    tagline: "The language of the web",
    description:
      "JavaScript runs in every browser and now on servers via Node.js. It's the backbone of web development, with the largest ecosystem of libraries and frameworks. If you build for the web, you need JavaScript.",
    demand: 5,
    salaryImpact: "+10-20% over entry-level baseline",
    useCases: ["Web frontends", "Web backends (Node.js)", "Mobile (React Native)", "Desktop (Electron)", "Browser extensions"],
    difficulty: 2,
    learningCurve: "Easy start, deep mastery takes time due to quirks.",
    trend: "stable",
    topCompanies: ["Meta", "Netflix", "Microsoft", "Stripe", "Airbnb", "Vercel"],
    careers: ["software-engineering", "web-dev", "mobile-dev"],
    icon: "🟨",
    color: "#F7DF1E",
  },
  {
    id: "typescript",
    name: "TypeScript",
    type: "language",
    parentLanguage: "javascript",
    tagline: "JavaScript with types",
    description:
      "TypeScript adds static typing to JavaScript, catching errors at compile time and powering better tooling. It's the default for modern professional web development and is increasingly required at top companies.",
    demand: 5,
    salaryImpact: "+15-25% over JavaScript baseline",
    useCases: ["Large web apps", "Full-stack (Next.js)", "API servers", "Libraries & SDKs", "Enterprise software"],
    difficulty: 3,
    learningCurve: "Moderate — requires understanding JS plus type system.",
    trend: "rising",
    topCompanies: ["Microsoft", "Vercel", "Airbnb", "Slack", "Asana", "Linear"],
    careers: ["software-engineering", "web-dev", "cloud-devops"],
    icon: "🔷",
    color: "#3178C6",
  },
  {
    id: "java",
    name: "Java",
    type: "language",
    tagline: "Write once, run anywhere",
    description:
      "Java is a mature, strongly-typed language that powers enterprise systems, Android apps, large-scale backend services, and big data pipelines. It's verbose but battle-tested and runs in countless production environments.",
    demand: 4,
    salaryImpact: "+10-20% over entry-level baseline",
    useCases: ["Enterprise backends", "Android apps", "Big data (Hadoop/Spark)", "Banking systems", "Spring services"],
    difficulty: 3,
    learningCurve: "Moderate — verbose but consistent and well-documented.",
    trend: "stable",
    topCompanies: ["Google", "Amazon", "Uber", "LinkedIn", "Netflix", "Banks"],
    careers: ["software-engineering", "mobile-dev"],
    icon: "☕",
    color: "#ED8B00",
  },
  {
    id: "c",
    name: "C",
    type: "language",
    tagline: "The foundational systems language",
    description:
      "C is a low-level, procedural language that powers operating systems, embedded devices, compilers, and high-performance software. Learning C teaches you how memory, pointers, and the machine actually work — invaluable for any serious engineer.",
    demand: 4,
    salaryImpact: "+10-15% for systems roles",
    useCases: ["Operating systems", "Embedded firmware", "Compilers", "High-performance libraries", "IoT"],
    difficulty: 4,
    learningCurve: "Steep — manual memory management and pointers.",
    trend: "stable",
    topCompanies: ["Linux Foundation", "Apple", "Microsoft", "Oracle", "Bosch"],
    careers: ["software-engineering", "cybersecurity", "hardware-embedded", "game-dev"],
    icon: "🔵",
    color: "#5C6BC0",
  },
  {
    id: "cpp",
    name: "C++",
    type: "language",
    parentLanguage: "c",
    tagline: "High-performance systems & games",
    description:
      "C++ extends C with object-oriented and generic programming. It powers game engines (Unreal), high-frequency trading, browsers, AAA games, AI infrastructure, and any system that needs raw performance with abstraction.",
    demand: 4,
    salaryImpact: "+15-25% for performance-critical roles",
    useCases: ["Game engines", "High-frequency trading", "Browsers (Chrome, Firefox)", "AI infra (PyTorch backend)", "Real-time systems"],
    difficulty: 5,
    learningCurve: "Very steep — vast language with sharp edges.",
    trend: "stable",
    topCompanies: ["Epic Games", "Google", "Meta", "NVIDIA", "Tesla", "Adobe"],
    careers: ["software-engineering", "ai-ml", "game-dev", "hardware-embedded"],
    icon: "➕",
    color: "#00599C",
  },
  {
    id: "csharp",
    name: "C#",
    type: "language",
    tagline: "Modern, cross-platform, Microsoft",
    description:
      "C# is a modern object-oriented language from Microsoft, used for Windows apps, web (ASP.NET), games (Unity), and cross-platform enterprise software via .NET. Clean syntax, strong tooling, and excellent performance.",
    demand: 4,
    salaryImpact: "+10-20% over entry-level baseline",
    useCases: ["Unity games", "ASP.NET backends", "Windows desktop apps", "Enterprise software", "Azure functions"],
    difficulty: 3,
    learningCurve: "Moderate — clean and consistent if you know Java or C++.",
    trend: "stable",
    topCompanies: ["Microsoft", "Unity", "Stack Overflow", "Accenture", "Deloitte"],
    careers: ["software-engineering", "game-dev", "web-dev"],
    icon: "#️⃣",
    color: "#239120",
  },
  {
    id: "go",
    name: "Go",
    type: "language",
    tagline: "Simple, fast, concurrent",
    description:
      "Go (Golang) is a compiled language from Google designed for simplicity, fast compilation, and excellent concurrency. It's the go-to for cloud infrastructure, microservices, CLIs, and high-throughput backend systems.",
    demand: 4,
    salaryImpact: "+20-30% — high demand, scarce talent",
    useCases: ["Microservices", "Cloud infrastructure (Kubernetes, Docker)", "CLIs", "API servers", "DevOps tooling"],
    difficulty: 2,
    learningCurve: "Gentle — small language, fast to learn.",
    trend: "rising",
    topCompanies: ["Google", "Uber", "Twitch", "Cloudflare", "DigitalOcean", "HashiCorp"],
    careers: ["software-engineering", "cloud-devops"],
    icon: "🐹",
    color: "#00ADD8",
  },
  {
    id: "rust",
    name: "Rust",
    type: "language",
    tagline: "Memory-safe systems programming",
    description:
      "Rust delivers C++-level performance with memory safety guaranteed at compile time. It's the most-loved language for systems work, powering parts of Linux, Windows, browsers, blockchain, and high-performance tooling.",
    demand: 4,
    salaryImpact: "+25-40% — top-paying systems language",
    useCases: ["Systems programming", "WebAssembly", "CLI tools", "Embedded", "Blockchain", "Browser engines"],
    difficulty: 5,
    learningCurve: "Steep — borrow checker forces new mental models.",
    trend: "rising",
    topCompanies: ["Mozilla", "Cloudflare", "Discord", "Microsoft", "Amazon", "Meta"],
    careers: ["software-engineering", "cloud-devops", "ai-ml", "cybersecurity", "hardware-embedded"],
    icon: "🦀",
    color: "#DEA584",
  },
  {
    id: "kotlin",
    name: "Kotlin",
    type: "language",
    tagline: "Modern Android & backend",
    description:
      "Kotlin is the official language for Android development and a modern alternative to Java for backends (Ktor/Spring). Concise, null-safe, and fully interoperable with Java — it's now Google's recommended choice for new Android apps.",
    demand: 4,
    salaryImpact: "+10-20% over Java baseline",
    useCases: ["Android apps", "Backend (Ktor/Spring)", "Cross-platform (KMP)", "Serverless"],
    difficulty: 3,
    learningCurve: "Moderate — easier than Java, modern features.",
    trend: "rising",
    topCompanies: ["Google", "JetBrains", "Square", "Netflix", "Atlassian"],
    careers: ["software-engineering", "mobile-dev"],
    icon: "🟪",
    color: "#7F52FF",
  },
  {
    id: "swift",
    name: "Swift",
    type: "language",
    tagline: "Native iOS & macOS",
    description:
      "Swift is Apple's modern language for iOS, macOS, watchOS, and tvOS development. Fast, safe, and expressive, it powers all new Apple-platform apps. With SwiftUI, you can build complete apps declaratively.",
    demand: 4,
    salaryImpact: "+15-25% for iOS roles",
    useCases: ["iOS apps", "macOS apps", "Apple Watch apps", "Server (Vapor)", "SwiftUI"],
    difficulty: 3,
    learningCurve: "Moderate — modern syntax, good tooling.",
    trend: "stable",
    topCompanies: ["Apple", "Uber", "Airbnb", "Lyft", "Square", "Discord"],
    careers: ["software-engineering", "mobile-dev"],
    icon: "🦅",
    color: "#F05138",
  },
  {
    id: "php",
    name: "PHP",
    type: "language",
    tagline: "Powers the majority of the web",
    description:
      "PHP runs roughly 75% of the web including WordPress, Wikipedia, and Facebook's early days. Modern PHP (8+) is fast, typed, and pleasant — and Laravel is one of the most productive web frameworks available.",
    demand: 3,
    salaryImpact: "+5-15% over entry-level baseline",
    useCases: ["Web backends (Laravel/Symfony)", "WordPress plugins & themes", "CMSs", "E-commerce"],
    difficulty: 2,
    learningCurve: "Easy start, modern PHP is clean.",
    trend: "stable",
    topCompanies: ["Meta (legacy)", "Slack", "Etsy", "Wikipedia", "Mailchimp"],
    careers: ["software-engineering", "web-dev"],
    icon: "🐘",
    color: "#777BB4",
  },
  {
    id: "ruby",
    name: "Ruby",
    type: "language",
    tagline: "Developer happiness above all",
    description:
      "Ruby is a dynamic, object-oriented language famous for developer productivity. With Ruby on Rails, it powers Shopify, GitHub, Airbnb, and countless startups — letting small teams ship fast.",
    demand: 3,
    salaryImpact: "+5-15% over entry-level baseline",
    useCases: ["Web backends (Rails)", "Prototyping", "Internal tools", "Static site generators"],
    difficulty: 2,
    learningCurve: "Gentle — readable syntax, great community.",
    trend: "stable",
    topCompanies: ["GitHub", "Shopify", "Airbnb", "Stripe", "Basecamp"],
    careers: ["software-engineering", "web-dev"],
    icon: "♦️",
    color: "#CC342D",
  },
  {
    id: "sql",
    name: "SQL",
    type: "language",
    tagline: "Query any database",
    description:
      "SQL is the universal language of relational databases. Every full-stack engineer, data scientist, and analyst needs SQL to read and write data in Postgres, MySQL, SQLite, and beyond. It's a must-have skill.",
    demand: 5,
    salaryImpact: "+10-15% — required for data roles",
    useCases: ["Application backends", "Data analytics", "Reporting", "Data warehousing", "BI"],
    difficulty: 2,
    learningCurve: "Easy basics, deep mastery takes practice.",
    trend: "stable",
    topCompanies: ["Every company with a database"],
    careers: ["software-engineering", "data-science", "ai-ml", "web-dev"],
    icon: "🗄️",
    color: "#336791",
  },
  {
    id: "bash",
    name: "Bash / Shell",
    type: "language",
    tagline: "Automate the command line",
    description:
      "Bash and shell scripting glue together Linux/Unix systems. It's essential for DevOps, sysadmin work, automation, and any engineer who lives in the terminal. Learn it once, use it daily forever.",
    demand: 4,
    salaryImpact: "+5-10% for DevOps roles",
    useCases: ["Automation", "DevOps pipelines", "System administration", "Build scripts", "CI/CD"],
    difficulty: 2,
    learningCurve: "Gentle — start with simple commands.",
    trend: "stable",
    topCompanies: ["Every Linux shop", "AWS", "Red Hat", "Cloud providers"],
    careers: ["cloud-devops", "software-engineering", "cybersecurity"],
    icon: "💻",
    color: "#4EAA25",
  },
  {
    id: "r",
    name: "R",
    type: "language",
    tagline: "Statistics & data visualization",
    description:
      "R is purpose-built for statistics, data analysis, and visualization. Beloved by statisticians, researchers, and data scientists for its CRAN ecosystem, ggplot2, and tidyverse.",
    demand: 3,
    salaryImpact: "+10-15% for data roles",
    useCases: ["Statistical analysis", "Data visualization (ggplot2)", "Research", "Bioinformatics", "Reporting"],
    difficulty: 3,
    learningCurve: "Moderate — different paradigm than general-purpose languages.",
    trend: "stable",
    topCompanies: ["Pharma", "Research labs", "Google", "Facebook", "Banks"],
    careers: ["data-science"],
    icon: "📊",
    color: "#276DC3",
  },
  {
    id: "dart",
    name: "Dart",
    type: "language",
    tagline: "Flutter's language",
    description:
      "Dart is Google's UI language, paired with Flutter to build cross-platform mobile, web, and desktop apps from one codebase. Easy to learn if you know Java or JavaScript, with strong tooling and hot reload.",
    demand: 3,
    salaryImpact: "+10-15% for mobile roles",
    useCases: ["Cross-platform apps (Flutter)", "Mobile (iOS + Android)", "Web (Flutter Web)", "Desktop"],
    difficulty: 2,
    learningCurve: "Gentle — familiar C-family syntax.",
    trend: "rising",
    topCompanies: ["Google", "BMW", "Alibaba", "eBay", "Toyota"],
    careers: ["mobile-dev", "software-engineering"],
    icon: "🎯",
    color: "#0175C2",
  },
  {
    id: "react",
    name: "React",
    type: "framework",
    companions: ["javascript", "typescript"],
    parentLanguage: "javascript",
    tagline: "The dominant UI library",
    description:
      "React is the most popular UI library in the world, powering Facebook, Instagram, Netflix, and millions of other sites. Its component model and hooks API are the industry standard for building modern web UIs.",
    demand: 5,
    salaryImpact: "+15-25% for frontend roles",
    useCases: ["Web apps", "Single-page apps", "Server-rendered sites", "Mobile (React Native)", "Dashboards"],
    difficulty: 3,
    learningCurve: "Moderate — concepts first, then ecosystem.",
    trend: "stable",
    topCompanies: ["Meta", "Netflix", "Airbnb", "Discord", "Vercel", "Notion"],
    careers: ["software-engineering", "web-dev", "mobile-dev"],
    icon: "⚛️",
    color: "#61DAFB",
  },
  {
    id: "nextjs",
    name: "Next.js",
    type: "framework",
    companions: ["react", "javascript", "typescript"],
    fullstack: true,
    parentLanguage: "typescript",
    tagline: "The React framework for production",
    description:
      "Next.js is the production-grade React framework from Vercel, adding server-side rendering, routing, API routes, image optimization, and deployment out of the box. It's the default starting point for serious React apps.",
    demand: 5,
    salaryImpact: "+20-30% — top-tier full-stack skill",
    useCases: ["Production web apps", "Marketing sites", "SaaS products", "Dashboards", "E-commerce"],
    difficulty: 3,
    learningCurve: "Moderate — React knowledge transfers directly.",
    trend: "rising",
    topCompanies: ["Vercel", "OpenAI", "Notion", "Loom", "Cal.com", "Hugging Face"],
    careers: ["software-engineering", "web-dev"],
    icon: "▲",
    color: "#000000",
  },
  {
    id: "django",
    name: "Django",
    type: "framework",
    companions: ["python"],
    fullstack: true,
    parentLanguage: "python",
    tagline: "Batteries-included Python web framework",
    description:
      "Django is a high-level Python web framework with everything included: ORM, auth, admin, forms, security. It powers Instagram, Pinterest, and Disqus — perfect for content-heavy apps and rapid prototyping.",
    demand: 4,
    salaryImpact: "+10-20% for Python backend roles",
    useCases: ["Content sites", "SaaS backends", "CMSs", "Internal tools", "REST APIs (DRF)"],
    difficulty: 3,
    learningCurve: "Moderate — conventions to learn, but very productive.",
    trend: "stable",
    topCompanies: ["Instagram", "Pinterest", "Disqus", "Mozilla", "Spotipy"],
    careers: ["software-engineering", "web-dev"],
    icon: "🦄",
    color: "#092E20",
  },
  {
    id: "fastapi",
    name: "FastAPI",
    type: "framework",
    companions: ["python"],
    parentLanguage: "python",
    tagline: "Modern, fast Python APIs",
    description:
      "FastAPI is a modern Python framework for building APIs with type hints, automatic docs, and async support. It's the fastest-growing Python backend framework, used for ML model serving and high-performance microservices.",
    demand: 4,
    salaryImpact: "+15-25% — modern Python backend skill",
    useCases: ["REST APIs", "ML model serving", "Microservices", "Real-time APIs", "SaaS backends"],
    difficulty: 2,
    learningCurve: "Gentle — feels like writing typed Python functions.",
    trend: "rising",
    topCompanies: ["Uber", "Netflix", "Microsoft", "OpenAI", "Stripe"],
    careers: ["software-engineering", "ai-ml", "web-dev"],
    icon: "⚡",
    color: "#009688",
  },
  {
    id: "flask",
    name: "Flask",
    type: "framework",
    companions: ["python"],
    parentLanguage: "python",
    tagline: "Micro framework, maximum flexibility",
    description:
      "Flask is a lightweight Python web framework — minimal core, huge extension ecosystem. Perfect when you want fine control, small APIs, or learning projects. Pinned at companies like Pinterest and LinkedIn for select services.",
    demand: 3,
    salaryImpact: "+5-15% for Python backend roles",
    useCases: ["Small APIs", "Prototypes", "Internal tools", "Learning projects", "Microservices"],
    difficulty: 2,
    learningCurve: "Gentle — minimal magic.",
    trend: "stable",
    topCompanies: ["Pinterest", "LinkedIn", "Twilio", "Reddit"],
    careers: ["software-engineering", "web-dev"],
    icon: "🍶",
    color: "#000000",
  },
  {
    id: "html",
    name: "HTML",
    type: "language",
    tagline: "The structure of the web",
    description:
      "HTML is the markup language that defines the structure of every web page. It's the first thing any web developer learns, and semantic HTML is the foundation of accessibility and SEO.",
    demand: 5,
    salaryImpact: "Required for web roles",
    useCases: ["Every web page", "Emails", "Web components", "PWA shells"],
    difficulty: 1,
    learningCurve: "Trivial basics, mastery via accessibility.",
    trend: "stable",
    topCompanies: ["Every company with a website"],
    careers: ["web-dev", "software-engineering"],
    icon: "📄",
    color: "#E34F26",
  },
  {
    id: "css",
    name: "CSS",
    type: "language",
    tagline: "Style the web",
    description:
      "CSS controls how web pages look — layout, color, typography, animation. Modern CSS (Grid, Flexbox, custom properties, container queries) is powerful enough to replace most preprocessor features.",
    demand: 5,
    salaryImpact: "Required for web roles",
    useCases: ["Web page styling", "Responsive design", "Animations", "Design systems", "Theming"],
    difficulty: 3,
    learningCurve: "Easy basics, layout mastery takes time.",
    trend: "stable",
    topCompanies: ["Every company with a website"],
    careers: ["web-dev", "software-engineering"],
    icon: "🎨",
    color: "#1572B6",
  },  // ---- Web frameworks & tools ----
  {
    id: "nodejs",
    name: "Node.js",
    type: "framework",
    parentLanguage: "javascript",
    tagline: "JavaScript runtime for server-side development",
    description: "Node.js is a JavaScript runtime built on Chrome's V8 engine that lets developers run JavaScript outside the browser. It powers scalable network applications, APIs, real-time services, and tooling. The npm ecosystem is the largest package registry in the world.",
    demand: 5,
    salaryImpact: "+15-25% salary premium for full-stack JS developers",
    useCases: ["REST/GraphQL APIs", "Real-time apps (chat, collaboration)", "CLI tools", "Build tooling", "Microservices"],
    difficulty: 3,
    learningCurve: "Easy if you know JavaScript; event-loop mental model takes practice",
    trend: "stable",
    topCompanies: ["Netflix", "PayPal", "LinkedIn", "Uber", "NASA", "Trello"],
    careers: ["web-dev", "software-engineering", "cloud-devops"],
    icon: "🟩",
    color: "#339933",
    companions: ["javascript", "typescript"],
    fullstack: true,
  },
  {
    id: "vue",
    name: "Vue",
    type: "framework",
    parentLanguage: "javascript",
    tagline: "Progressive JavaScript framework for UIs",
    description: "Vue.js is a progressive framework for building user interfaces. Unlike monolithic frameworks, Vue is designed from the ground up to be incrementally adoptable. The core library focuses only on the view layer, making it easy to pick up and integrate with other libraries or existing projects.",
    demand: 4,
    salaryImpact: "+10-15% salary premium for Vue specialists",
    useCases: ["SPAs", "Interactive UIs", "Prototyping", "Enterprise dashboards", "Progressive enhancement"],
    difficulty: 2,
    learningCurve: "Gentlest learning curve of the big three frontend frameworks",
    trend: "rising",
    topCompanies: ["Alibaba", "GitLab", "Adobe", "Behance", "Xiaomi", "Louis Vuitton"],
    careers: ["web-dev", "software-engineering"],
    icon: "💚",
    color: "#42B883",
    companions: ["javascript", "typescript"],
  },
  {
    id: "angular",
    name: "Angular",
    type: "framework",
    parentLanguage: "typescript",
    tagline: "Full-platform TypeScript framework by Google",
    description: "Angular is a TypeScript-based web application framework led by Google. It is a complete rewrite from the same team that built AngularJS, focused on building dynamic, modern web apps with first-class TypeScript support, dependency injection, and a powerful CLI.",
    demand: 4,
    salaryImpact: "+12-18% salary premium for Angular enterprise developers",
    useCases: ["Enterprise SPAs", "PWAs", "Dashboards", "Admin panels", "Large-scale web apps"],
    difficulty: 4,
    learningCurve: "Steep — RxJS, dependency injection, and TypeScript mastery required",
    trend: "stable",
    topCompanies: ["Google", "Microsoft", "IBM", "Forbes", "PayPal", "Upwork"],
    careers: ["web-dev", "software-engineering"],
    icon: "🅰️",
    color: "#DD0031",
    companions: ["typescript"],
    fullstack: true,
  },
  {
    id: "svelte",
    name: "Svelte",
    type: "framework",
    parentLanguage: "javascript",
    tagline: "Compile-time reactive UI framework",
    description: "Svelte is a radical new approach to building user interfaces. Whereas traditional frameworks like React and Vue do the bulk of their work in the browser, Svelte shifts that work into a compile step that happens when you build your app. The result: smaller bundles, better performance, and a more intuitive authoring experience.",
    demand: 3,
    salaryImpact: "+8-12% salary premium for Svelte specialists",
    useCases: ["Lightweight SPAs", "Performance-critical UIs", "Embeddable widgets", "Marketing sites"],
    difficulty: 2,
    learningCurve: "Easiest modern framework — feels like writing plain HTML/JS",
    trend: "rising",
    topCompanies: ["The New York Times", "Spotify", "GoDaddy", "Rakuten", "Avast"],
    careers: ["web-dev", "software-engineering"],
    icon: "🔥",
    color: "#FF3E00",
    companions: ["javascript", "typescript"],
  },
  {
    id: "tailwind",
    name: "Tailwind CSS",
    type: "framework",
    tagline: "Utility-first CSS framework",
    description: "Tailwind CSS is a utility-first CSS framework for rapidly building custom user interfaces. It provides low-level utility classes that let you build custom designs without leaving your HTML, accelerating development while keeping bundle sizes tiny with its JIT compiler.",
    demand: 4,
    salaryImpact: "+5-10% productivity boost; standard in modern frontend stacks",
    useCases: ["Rapid prototyping", "Design systems", "Marketing sites", "Dashboards", "Component libraries"],
    difficulty: 2,
    learningCurve: "A few hours to ramp up; mastery of design tokens takes longer",
    trend: "rising",
    topCompanies: ["Vercel", "Stripe", "OpenAI", "GitHub", "Hashnode", "Linear"],
    careers: ["web-dev", "software-engineering"],
    icon: "🌬️",
    color: "#06B6D4",
    companions: ["html", "css", "javascript", "react", "nextjs", "vue", "svelte"],
  },
  {
    id: "express",
    name: "Express",
    type: "framework",
    parentLanguage: "javascript",
    tagline: "Minimal Node.js web framework",
    description: "Express is a minimal and flexible Node.js web application framework that provides a robust set of features for web and mobile applications. It is the de facto standard server framework for Node.js and the foundation for many higher-level frameworks like NestJS and Sails.",
    demand: 4,
    salaryImpact: "+8-12% salary premium for backend Node.js developers",
    useCases: ["REST APIs", "Server-rendered apps", "Microservices", "Webhook handlers", "API gateways"],
    difficulty: 2,
    learningCurve: "Minimal API — quick to learn if you know JavaScript and HTTP",
    trend: "stable",
    topCompanies: ["IBM", "Accenture", "Uber", "Twitter", "Medium"],
    careers: ["web-dev", "software-engineering"],
    icon: "🚂",
    color: "#000000",
    companions: ["nodejs", "javascript", "typescript"],
  },
  {
    id: "graphql",
    name: "GraphQL",
    type: "framework",
    tagline: "Query language for APIs",
    description: "GraphQL is a query language for APIs and a runtime for fulfilling those queries with your existing data. Created by Facebook in 2012 and open-sourced in 2015, it gives clients the power to ask for exactly what they need and nothing more, making it easier to evolve APIs over time.",
    demand: 4,
    salaryImpact: "+10-15% salary premium for full-stack GraphQL developers",
    useCases: ["Mobile APIs", "Federated microservices", "Aggregation layers", "Client-driven queries"],
    difficulty: 3,
    learningCurve: "Schema-first thinking + N+1 problem awareness needed",
    trend: "rising",
    topCompanies: ["Meta", "GitHub", "Shopify", "Airbnb", "Twitter", "Pinterest"],
    careers: ["web-dev", "software-engineering", "mobile-dev"],
    icon: " ◈",
    color: "#E10098",
    companions: ["nodejs", "typescript", "react"],
  },
  {
    id: "bootstrap",
    name: "Bootstrap",
    type: "framework",
    tagline: "CSS framework for responsive sites",
    description: "Bootstrap is the world's most popular CSS framework for developing responsive, mobile-first websites. Originally created at Twitter, it provides pre-built components, a 12-column grid system, and JavaScript plugins that get projects off the ground fast.",
    demand: 3,
    salaryImpact: "Common baseline skill; minor premium for component design",
    useCases: ["Internal tools", "Admin dashboards", "Marketing sites", "Rapid prototyping", "Legacy migrations"],
    difficulty: 1,
    learningCurve: "Hours — the lowest learning curve of any CSS framework",
    trend: "declining",
    topCompanies: ["Twitter", "Spotify", "LinkedIn", "Vogue", "NASA"],
    careers: ["web-dev", "software-engineering"],
    icon: "🅱️",
    color: "#7952B3",
    companions: ["html", "css", "javascript"],
  },
  {
    id: "jquery",
    name: "jQuery",
    type: "framework",
    tagline: "Classic JavaScript library",
    description: "jQuery is a fast, small, and feature-rich JavaScript library. It makes things like HTML document traversal and manipulation, event handling, and animation much simpler with an easy-to-use API that works across a multitude of browsers. Still found in many legacy codebases.",
    demand: 2,
    salaryImpact: "Useful for legacy maintenance; minimal premium",
    useCases: ["Legacy maintenance", "WordPress sites", "Quick DOM scripts", "Older browser support"],
    difficulty: 1,
    learningCurve: "Trivial — one of the easiest JS libraries to learn",
    trend: "declining",
    topCompanies: ["WordPress", "IBM", "Microsoft (legacy)", "Bank of America"],
    careers: ["web-dev", "software-engineering"],
    icon: "📦",
    color: "#0769AD",
    companions: ["javascript", "html"],
  },
  // ---- Systems & tools ----
  {
    id: "git",
    name: "Git",
    type: "tool",
    tagline: "Distributed version control system",
    description: "Git is a free and open-source distributed version control system designed to handle everything from small to very large projects with speed and efficiency. It is the foundation of modern software collaboration, used by virtually every development team on Earth.",
    demand: 5,
    salaryImpact: "Essential baseline skill — required for every dev role",
    useCases: ["Source control", "Collaboration", "CI/CD triggers", "Code review", "Release management"],
    difficulty: 2,
    learningCurve: "Basic commands in hours; branching/rebasing mastery takes weeks",
    trend: "stable",
    topCompanies: ["Every tech company", "GitHub", "GitLab", "Atlassian", "Microsoft"],
    careers: ["software-engineering", "web-dev", "cloud-devops", "data-science", "ai-ml", "cybersecurity", "mobile-dev", "game-dev", "hardware-embedded"],
    icon: "🌿",
    color: "#F05032",
  },
  {
    id: "docker",
    name: "Docker",
    type: "tool",
    tagline: "Container platform for portable apps",
    description: "Docker is an open platform for developing, shipping, and running applications in containers. Containers package software into standardized units that have everything the software needs to run, including code, libraries, and system tools, ensuring consistent behavior across environments.",
    demand: 5,
    salaryImpact: "+15-20% salary premium for DevOps and backend engineers",
    useCases: ["App packaging", "Local dev environments", "Microservices", "CI/CD pipelines", "Reproducible builds"],
    difficulty: 3,
    learningCurve: "Days to use; weeks to optimize multi-stage builds and compose files",
    trend: "stable",
    topCompanies: ["Google", "Microsoft", "Amazon", "Netflix", "PayPal", "Spotify"],
    careers: ["cloud-devops", "software-engineering", "web-dev", "data-science", "ai-ml"],
    icon: "🐳",
    color: "#2496ED",
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    type: "tool",
    tagline: "Container orchestration platform",
    description: "Kubernetes (K8s) is an open-source system for automating deployment, scaling, and management of containerized applications. Originally developed at Google from their Borg project, it is now the industry standard for running production container workloads at scale.",
    demand: 5,
    salaryImpact: "+25-35% salary premium for certified K8s administrators",
    useCases: ["Container orchestration", "Auto-scaling", "Self-healing services", "Hybrid/multi-cloud", "Batch jobs"],
    difficulty: 5,
    learningCurve: "Steep — networking, RBAC, operators, and CRDs take months to master",
    trend: "rising",
    topCompanies: ["Google", "Amazon (EKS)", "Microsoft (AKS)", "Apple", "Stripe", "Airbnb"],
    careers: ["cloud-devops", "software-engineering"],
    icon: "☸️",
    color: "#326CE5",
    companions: ["docker"],
  },
  {
    id: "terraform",
    name: "Terraform",
    type: "tool",
    tagline: "Infrastructure as Code tool",
    description: "Terraform is HashiCorp's Infrastructure as Code (IaC) tool that lets you define and provision cloud infrastructure using a declarative configuration language. It supports AWS, Azure, GCP, and hundreds of other providers, making it the leading multi-cloud IaC solution.",
    demand: 5,
    salaryImpact: "+20-30% salary premium for DevOps engineers with IaC",
    useCases: ["Cloud provisioning", "Multi-cloud deployments", "Environment parity", "Disaster recovery", "Compliance"],
    difficulty: 4,
    learningCurve: "HCL syntax in days; state management and modules take weeks",
    trend: "rising",
    topCompanies: ["HashiCorp", "AWS", "Google", "Stripe", "Segment", "GitHub"],
    careers: ["cloud-devops", "software-engineering"],
    icon: "🌍",
    color: "#7B42BC",
    companions: ["docker", "kubernetes"],
  },
  {
    id: "yaml",
    name: "YAML",
    type: "tool",
    tagline: "Human-friendly data serialization",
    description: "YAML ('YAML Ain't Markup Language') is a human-friendly data serialization standard for all programming languages. It is widely used for configuration files, CI/CD pipelines (GitHub Actions, GitLab CI), Kubernetes manifests, and infrastructure-as-code.",
    demand: 3,
    salaryImpact: "Baseline skill — expected of every DevOps/backend engineer",
    useCases: ["Config files", "CI/CD pipelines", "K8s manifests", "Terraform", "Static site generators"],
    difficulty: 1,
    learningCurve: "Hours — syntax is minimal but indentation-sensitive",
    trend: "stable",
    topCompanies: ["Every DevOps team", "GitHub", "GitLab", "Red Hat", "AWS"],
    careers: ["cloud-devops", "software-engineering", "web-dev"],
    icon: "📋",
    color: "#CB171E",
  },
  {
    id: "powershell",
    name: "PowerShell",
    type: "language",
    tagline: "Microsoft's cross-platform shell & scripting language",
    description: "PowerShell is a cross-platform task automation solution made up of a command-line shell, a scripting language, and a configuration management framework. Built on .NET, it is the standard for Windows administration, Azure automation, and enterprise reporting.",
    demand: 3,
    salaryImpact: "+15-20% for Windows/Azure-focused sysadmins and DevOps",
    useCases: ["Windows administration", "Azure automation", "Active Directory", "Compliance reporting", "CI/CD on Windows"],
    difficulty: 3,
    learningCurve: "Days for basics; object pipeline mastery takes weeks",
    trend: "stable",
    topCompanies: ["Microsoft", "Bank of America", "JPMorgan", "Deloitte", "Cerner"],
    careers: ["cloud-devops", "cybersecurity", "software-engineering"],
    icon: "⚡",
    color: "#5391FE",
  },
  // ---- Data science & ML ----
  {
    id: "julia",
    name: "Julia",
    type: "language",
    tagline: "High-performance scientific computing",
    description: "Julia is a high-level, high-performance dynamic programming language for technical computing, with syntax that is familiar to users of other technical computing environments. It solves the 'two-language problem' by being both fast (like C) and productive (like Python).",
    demand: 3,
    salaryImpact: "+10-15% for scientific computing and HPC roles",
    useCases: ["Scientific computing", "Numerical simulation", "Machine learning", "Quantitative finance", "Optimization"],
    difficulty: 3,
    learningCurve: "Easy if you know Python or MATLAB; multiple dispatch takes getting used to",
    trend: "rising",
    topCompanies: ["NASA", "AstraZeneca", "BlackRock", "MIT", "Julia Computing"],
    careers: ["data-science", "ai-ml"],
    icon: "💎",
    color: "#9558B2",
  },
  {
    id: "sas",
    name: "SAS",
    type: "language",
    tagline: "Enterprise statistical analysis system",
    description: "SAS (Statistical Analysis System) is a software suite developed by SAS Institute for advanced analytics, multivariate analysis, business intelligence, data management, and predictive analytics. Heavily used in regulated industries like pharma, banking, and healthcare.",
    demand: 2,
    salaryImpact: "+15-20% in regulated industries (pharma, banking, healthcare)",
    useCases: ["Clinical trial analysis", "Banking risk models", "Regulatory reporting", "Survey analytics", "BI dashboards"],
    difficulty: 3,
    learningCurve: "Days for DATA step; weeks for PROC SQL and macros",
    trend: "declining",
    topCompanies: ["Pfizer", "Novartis", "Bank of America", "Wells Fargo", "Mayo Clinic"],
    careers: ["data-science"],
    icon: "📊",
    color: "#0066CC",
  },
  {
    id: "tableau",
    name: "Tableau",
    type: "tool",
    tagline: "Visual analytics platform",
    description: "Tableau is a leading data visualization and business intelligence platform that helps people see and understand their data. Acquired by Salesforce in 2019, it is the standard for non-technical dashboards in marketing, sales, and operations teams.",
    demand: 3,
    salaryImpact: "+10-15% for analyst and BI roles",
    useCases: ["Executive dashboards", "Sales analytics", "Marketing attribution", "Operational reporting", "Self-service BI"],
    difficulty: 2,
    learningCurve: "Days to build dashboards; weeks for LOD calcs and parameters",
    trend: "stable",
    topCompanies: ["Salesforce", "Coca-Cola", "Netflix", "Deloitte", "JPMorgan"],
    careers: ["data-science"],
    icon: "📈",
    color: "#E97627",
  },
  {
    id: "powerbi",
    name: "Power BI",
    type: "tool",
    tagline: "Microsoft business intelligence platform",
    description: "Power BI is Microsoft's business analytics service that delivers insights for analyzing data and sharing insights. It connects to hundreds of data sources, simplifies data prep, and drives ad-hoc analysis — the standard BI tool in Microsoft-heavy enterprises.",
    demand: 4,
    salaryImpact: "+12-18% for analysts in Microsoft shops",
    useCases: ["Executive dashboards", "Operational reporting", "Excel replacement", "Embedded analytics", "Data storytelling"],
    difficulty: 2,
    learningCurve: "Days to build a dashboard; DAX mastery takes weeks",
    trend: "rising",
    topCompanies: ["Microsoft", "KPMG", "PwC", "EY", "Toyota", "T-Mobile"],
    careers: ["data-science"],
    icon: "📉",
    color: "#F2C811",
  },
  {
    id: "cuda",
    name: "CUDA",
    type: "tool",
    tagline: "NVIDIA's GPU programming platform",
    description: "CUDA (Compute Unified Device Architecture) is NVIDIA's parallel computing platform and programming model that enables dramatic increases in computing performance by harnessing the power of GPUs. It is the foundation of modern deep learning and HPC workloads.",
    demand: 4,
    salaryImpact: "+25-40% for ML systems engineers and HPC roles",
    useCases: ["Deep learning training", "Scientific computing", "Computer vision", "Crypto mining", "GPU-accelerated analytics"],
    difficulty: 5,
    learningCurve: "Steep — requires C/C++ and parallel programming mindset",
    trend: "rising",
    topCompanies: ["NVIDIA", "OpenAI", "Anthropic", "Tesla", "Meta AI", "DeepMind"],
    careers: ["ai-ml", "data-science", "software-engineering"],
    icon: "🎮",
    color: "#76B900",
    companions: ["python", "cpp"],
  },
  {
    id: "pytorch",
    name: "PyTorch",
    type: "framework",
    parentLanguage: "python",
    tagline: "Deep learning framework by Meta",
    description: "PyTorch is an open-source machine learning library developed by Meta's AI Research lab. It provides a flexible, dynamic computational graph that makes it the preferred framework for researchers. Used by most cutting-edge LLM and computer vision research.",
    demand: 5,
    salaryImpact: "+20-30% for ML engineers and research scientists",
    useCases: ["LLM training", "Computer vision", "Reinforcement learning", "Research prototypes", "Production ML at scale"],
    difficulty: 4,
    learningCurve: "Days if you know Python + deep learning basics; mastery takes months",
    trend: "rising",
    topCompanies: ["Meta", "OpenAI", "Tesla", "Microsoft", "NVIDIA", "Stability AI"],
    careers: ["ai-ml", "data-science"],
    icon: "🔴",
    color: "#EE4C2C",
    companions: ["python"],
  },
  {
    id: "tensorflow",
    name: "TensorFlow",
    type: "framework",
    parentLanguage: "python",
    tagline: "Production ML framework by Google",
    description: "TensorFlow is Google's end-to-end open-source machine learning platform. While PyTorch dominates research, TensorFlow (with Keras) remains strong in production deployment, edge devices (TF Lite), and enterprise ML pipelines. Used across Google's products.",
    demand: 4,
    salaryImpact: "+15-25% for ML engineers in production roles",
    useCases: ["Production ML pipelines", "Edge inference", "Mobile ML", "Recommendation systems", "Speech recognition"],
    difficulty: 4,
    learningCurve: "Keras high-level API is easy; low-level TF takes longer",
    trend: "declining",
    topCompanies: ["Google", "Airbnb", "Intel", "Twitter", "SAP", "PayPal"],
    careers: ["ai-ml", "data-science"],
    icon: "🟠",
    color: "#FF6F00",
    companions: ["python"],
  },
  // ---- Cybersecurity & low-level ----
  {
    id: "assembly",
    name: "Assembly",
    type: "language",
    tagline: "Low-level CPU programming language",
    description: "Assembly language is a low-level programming language for a computer or other programmable device that is a close-to-the-metal representation of machine code. Each CPU family has its own assembly dialect (x86, ARM, RISC-V). Critical for reverse engineering, exploit dev, and embedded systems.",
    demand: 3,
    salaryImpact: "+20-30% for vulnerability research and exploit development",
    useCases: ["Reverse engineering", "Exploit development", "Embedded firmware", "Performance tuning", "Compiler backends"],
    difficulty: 5,
    learningCurve: "Steep — requires deep CPU/architecture knowledge",
    trend: "stable",
    topCompanies: ["Intel", "AMD", "ARM", "NSA", "CrowdStrike", "IDF Unit 8200"],
    careers: ["cybersecurity", "hardware-embedded", "game-dev"],
    icon: "🔩",
    color: "#6E4C13",
  },
  {
    id: "lua",
    name: "Lua",
    type: "language",
    tagline: "Lightweight embeddable scripting language",
    description: "Lua is a powerful, fast, lightweight, embeddable scripting language. It is designed as a scripting language that is small enough to fit on embedded devices, fast enough for game scripting, and flexible enough for plugin systems. Used by Redis, Nginx, Roblox, and World of Warcraft.",
    demand: 2,
    salaryImpact: "+10-15% in game dev and embedded scripting roles",
    useCases: ["Game scripting (Roblox, WoW)", "Nginx/Redis plugins", "Embedded scripting", "Config DSLs", "Plugin systems"],
    difficulty: 2,
    learningCurve: "Days — minimal syntax; tables + metatables are the main concept",
    trend: "stable",
    topCompanies: ["Roblox", "Blizzard", "Adobe (Lightroom)", "Cloudflare", "Tencent"],
    careers: ["game-dev", "hardware-embedded", "software-engineering"],
    icon: "🌙",
    color: "#2C2D72",
  },
  {
    id: "objective-c",
    name: "Objective-C",
    type: "language",
    tagline: "Apple's pre-Swift language",
    description: "Objective-C is a general-purpose, object-oriented programming language that adds Smalltalk-style messaging to the C programming language. It was the standard for macOS and iOS development before Swift, and is still heavily present in legacy Apple codebases.",
    demand: 2,
    salaryImpact: "+15-20% for maintaining legacy Apple codebases",
    useCases: ["Legacy iOS/macOS maintenance", "Apple framework internals", "Mixed Swift/Obj-C codebases"],
    difficulty: 4,
    learningCurve: "Moderate if you know C; bracket syntax is unusual",
    trend: "declining",
    topCompanies: ["Apple", "Google (legacy iOS apps)", "Facebook", "Microsoft (Office for Mac)"],
    careers: ["mobile-dev"],
    icon: "🍎",
    color: "#438EFF",
  },
  {
    id: "react-native",
    name: "React Native",
    type: "framework",
    parentLanguage: "javascript",
    tagline: "Cross-platform mobile apps with React",
    description: "React Native lets you build native iOS and Android apps using React and JavaScript. Created by Meta, it powers some of the world's most popular apps (Instagram, Discord, Shopify, Tesla). Write once, ship to both platforms with native performance.",
    demand: 4,
    salaryImpact: "+15-25% for cross-platform mobile developers",
    useCases: ["iOS + Android apps from one codebase", "MVPs", "E-commerce apps", "Social apps", "Rapid mobile prototyping"],
    difficulty: 3,
    learningCurve: "Easy if you know React; native modules take longer",
    trend: "rising",
    topCompanies: ["Meta (Instagram)", "Discord", "Shopify", "Tesla", "Microsoft", "Walmart"],
    careers: ["mobile-dev", "web-dev"],
    icon: "📱",
    color: "#61DAFB",
    companions: ["react", "javascript", "typescript"],
  },
  // ---- Game dev ----
  {
    id: "gdscript",
    name: "GDScript",
    type: "language",
    tagline: "Godot Engine's scripting language",
    description: "GDScript is the built-in scripting language for the Godot Engine, designed specifically for game development. Python-like syntax, tightly integrated with Godot's scene system, and fast iteration without compilation makes it the favorite of indie game developers.",
    demand: 2,
    salaryImpact: "+10-15% in indie game dev; growing as Godot adoption rises",
    useCases: ["Indie games", "Game jams", "2D and 3D game logic", "Prototyping", "Educational tools"],
    difficulty: 2,
    learningCurve: "Days if you know Python; scene system takes a few weeks",
    trend: "rising",
    topCompanies: ["Godot Foundation", "Indie studios", "Schools", "Game jam participants"],
    careers: ["game-dev"],
    icon: "🎮",
    color: "#478CBF",
  },
  {
    id: "glsl",
    name: "GLSL",
    type: "language",
    tagline: "OpenGL Shading Language",
    description: "GLSL (OpenGL Shading Language) is a C-style language used to program the GPU's programmable pipeline. It is the foundation of real-time graphics for games, scientific visualization, WebGL, and creative coding. Shaders written in GLSL run on every GPU.",
    demand: 3,
    salaryImpact: "+20-30% for graphics programmers and technical artists",
    useCases: ["Game shaders", "WebGL/WebGPU effects", "VFX", "Real-time visualization", "Generative art"],
    difficulty: 5,
    learningCurve: "Steep — requires linear algebra and GPU mental model",
    trend: "stable",
    topCompanies: ["Epic Games", "Unity", "Adobe", "Autodesk", "DJI", "Shadertoy creators"],
    careers: ["game-dev", "software-engineering"],
    icon: "🌈",
    color: "#5566AC",
  },
  // ---- Hardware ----
  {
    id: "verilog",
    name: "Verilog",
    type: "language",
    tagline: "Hardware description language",
    description: "Verilog is a hardware description language (HDL) used to model electronic systems. Unlike software languages, Verilog describes the behavior of digital circuits that will be synthesized into actual hardware (FPGAs, ASICs). The foundation of chip design.",
    demand: 3,
    salaryImpact: "+25-40% for FPGA and ASIC design engineers",
    useCases: ["FPGA design", "ASIC development", "Digital IC verification", "Hardware emulation", "Test benches"],
    difficulty: 5,
    learningCurve: "Steep — requires digital logic + concurrent thinking",
    trend: "stable",
    topCompanies: ["Intel", "AMD", "NVIDIA", "Apple (silicon)", "Tesla", "Qualcomm"],
    careers: ["hardware-embedded"],
    icon: "🔌",
    color: "#B30000",
  },
  {
    id: "vhdl",
    name: "VHDL",
    type: "language",
    tagline: "VHSIC Hardware Description Language",
    description: "VHDL is a strongly-typed hardware description language used in electronic design automation to describe digital and mixed-signal systems. Used heavily in aerospace, defense, and automotive where strong typing and formal verification matter.",
    demand: 2,
    salaryImpact: "+25-40% for FPGA/ASIC roles in defense and aerospace",
    useCases: ["Aerospace FPGA design", "Defense systems", "Automotive safety", "Telecom", "Formal verification"],
    difficulty: 5,
    learningCurve: "Steep — verbose syntax + concurrency model",
    trend: "stable",
    topCompanies: ["Lockheed Martin", "Raytheon", "NASA", "Boeing", "Intel (FPGA)"],
    careers: ["hardware-embedded"],
    icon: "🔲",
    color: "#543978",
  },
  {
    id: "arduino",
    name: "Arduino C++",
    type: "framework",
    parentLanguage: "cpp",
    tagline: "Embedded programming for makers",
    description: "Arduino is an open-source electronics platform based on easy-to-use hardware and software. Arduino boards read inputs — light, a finger, a Twitter message — and turn them into outputs: activating a motor, turning on an LED, publishing something online. The gateway to embedded systems.",
    demand: 3,
    salaryImpact: "+10-15% for IoT and maker-focused embedded roles",
    useCases: ["IoT devices", "Robotics", "Sensor projects", "Educational kits", "Rapid hardware prototypes"],
    difficulty: 2,
    learningCurve: "Days — gentlest entry to embedded programming",
    trend: "rising",
    topCompanies: ["Arduino", "Adafruit", "SparkFun", "Startups", "Schools", "Maker spaces"],
    careers: ["hardware-embedded"],
    icon: "🔧",
    color: "#00979D",
    companions: ["cpp", "c"],
  },
];

export const LANGUAGE_MAP: Record<string, LanguageInfo> = Object.fromEntries(
  LANGUAGES.map((l) => [l.id, l]),
);

export const CAREER_MAP: Record<string, CareerInfo> = Object.fromEntries(
  CAREERS.map((c) => [c.id, c]),
);

// ============================================================
// OCCUPATIONS
// ============================================================

export const OCCUPATIONS: OccupationInfo[] = [
  { id: "student", label: "Student (school/university)", pace: "foundational", description: "Full-time student with more availability — plan adds extra depth, fundamentals, and projects." },
  { id: "professional", label: "Working professional", pace: "condensed", description: "Currently employed — plan is condensed to fit evenings/weekends with practical shortcuts." },
  { id: "career-changer", label: "Career changer", pace: "foundational", description: "Switching into tech from another field — plan emphasizes foundations and a portfolio project." },
  { id: "freelancer", label: "Freelancer / self-employed", pace: "condensed", description: "Self-employed with variable schedule — plan is flexible and project-focused." },
  { id: "bootcamp-grad", label: "Bootcamp graduate", pace: "condensed", description: "Already has some training — plan fills gaps and goes deeper on systems & algorithms." },
  { id: "hobbyist", label: "Hobbyist / curious learner", pace: "foundational", description: "Learning for fun or side projects — plan is exploratory and curiosity-driven." },
  { id: "unemployed", label: "Job seeker (full-time available)", pace: "foundational", description: "Full-time available to learn — plan is intensive with job-readiness focus." },
];

export const OCCUPATION_MAP: Record<string, OccupationInfo> = Object.fromEntries(
  OCCUPATIONS.map((o) => [o.id, o]),
);

// ============================================================
// BACKGROUND THEMES — 10 presets + custom
// ============================================================

export type BackgroundTheme = {
  id: string;
  label: string;
  description: string;
  /** Tailwind/CSS gradient or color stops */
  gradient: string;
  /** Swatch color for the picker */
  swatch: string;
};

export const BACKGROUND_THEMES: BackgroundTheme[] = [
  { id: "aurora", label: "Aurora", description: "Default teal-violet-amber aurora", gradient: "radial-gradient(at 20% 20%, rgba(45,212,191,0.18) 0px, transparent 50%), radial-gradient(at 80% 10%, rgba(232,121,249,0.15) 0px, transparent 50%), radial-gradient(at 50% 90%, rgba(252,211,77,0.12) 0px, transparent 50%)", swatch: "#2DD4BF" },
  { id: "ocean", label: "Ocean", description: "Deep blues and teals", gradient: "radial-gradient(at 20% 20%, rgba(56,189,248,0.20) 0px, transparent 50%), radial-gradient(at 80% 30%, rgba(14,165,233,0.18) 0px, transparent 50%), radial-gradient(at 50% 90%, rgba(30,64,175,0.20) 0px, transparent 50%)", swatch: "#0EA5E9" },
  { id: "forest", label: "Forest", description: "Greens and earth tones", gradient: "radial-gradient(at 20% 20%, rgba(34,197,94,0.18) 0px, transparent 50%), radial-gradient(at 80% 30%, rgba(132,204,22,0.16) 0px, transparent 50%), radial-gradient(at 50% 90%, rgba(20,83,45,0.18) 0px, transparent 50%)", swatch: "#22C55E" },
  { id: "sunset", label: "Sunset", description: "Warm oranges and pinks", gradient: "radial-gradient(at 20% 20%, rgba(251,146,60,0.18) 0px, transparent 50%), radial-gradient(at 80% 30%, rgba(236,72,153,0.18) 0px, transparent 50%), radial-gradient(at 50% 90%, rgba(220,38,38,0.16) 0px, transparent 50%)", swatch: "#F97316" },
  { id: "midnight", label: "Midnight", description: "Deep dark navy", gradient: "radial-gradient(at 20% 20%, rgba(99,102,241,0.16) 0px, transparent 50%), radial-gradient(at 80% 30%, rgba(30,27,75,0.50) 0px, transparent 50%), radial-gradient(at 50% 90%, rgba(2,6,23,0.50) 0px, transparent 50%)", swatch: "#1E1B4B" },
  { id: "lavender", label: "Lavender", description: "Soft purples", gradient: "radial-gradient(at 20% 20%, rgba(196,181,253,0.22) 0px, transparent 50%), radial-gradient(at 80% 30%, rgba(167,139,250,0.18) 0px, transparent 50%), radial-gradient(at 50% 90%, rgba(139,92,246,0.16) 0px, transparent 50%)", swatch: "#A78BFA" },
  { id: "rose", label: "Rose", description: "Romantic pinks", gradient: "radial-gradient(at 20% 20%, rgba(251,207,232,0.22) 0px, transparent 50%), radial-gradient(at 80% 30%, rgba(244,114,182,0.18) 0px, transparent 50%), radial-gradient(at 50% 90%, rgba(219,39,119,0.16) 0px, transparent 50%)", swatch: "#F472B6" },
  { id: "mint", label: "Mint", description: "Fresh mints", gradient: "radial-gradient(at 20% 20%, rgba(167,243,208,0.22) 0px, transparent 50%), radial-gradient(at 80% 30%, rgba(110,231,183,0.18) 0px, transparent 50%), radial-gradient(at 50% 90%, rgba(16,185,129,0.16) 0px, transparent 50%)", swatch: "#10B981" },
  { id: "slate", label: "Slate", description: "Cool grays", gradient: "radial-gradient(at 20% 20%, rgba(148,163,184,0.18) 0px, transparent 50%), radial-gradient(at 80% 30%, rgba(100,116,139,0.16) 0px, transparent 50%), radial-gradient(at 50% 90%, rgba(51,65,85,0.18) 0px, transparent 50%)", swatch: "#64748B" },
  { id: "custom", label: "Custom", description: "Pick your own color", gradient: "", swatch: "#6366F1" },
];

export function getBackgroundTheme(id: string, customColor?: string): BackgroundTheme | null {
  if (id === "custom" && customColor) {
    return {
      id: "custom",
      label: "Custom",
      description: "Your custom color",
      gradient: `radial-gradient(at 20% 20%, ${customColor}33 0px, transparent 50%), radial-gradient(at 80% 30%, ${customColor}22 0px, transparent 50%), radial-gradient(at 50% 90%, ${customColor}33 0px, transparent 50%)`,
      swatch: customColor,
    };
  }
  return BACKGROUND_THEMES.find((t) => t.id === id) ?? BACKGROUND_THEMES[0];
}
