import type { CareerInfo, LanguageInfo, OccupationInfo } from "./types";

// ============================================================
// CAREERS — 8 main + sub-paths for software-engineering
// ============================================================

export const CAREERS: CareerInfo[] = [
  {
    id: "software-engineering",
    label: "Software Engineering",
    tagline: "Build robust systems that scale",
    description:
      "Software engineers design, build, test, and maintain the applications and systems that power modern life. You'll work across the stack — from architecture and APIs to deployment and observability — collaborating with product, design, and operations teams to ship reliable software.",
    recommendedLanguages: ["python", "javascript", "typescript", "java", "sql"],
    skills: ["Data structures & algorithms", "System design", "Version control (Git)", "Testing", "CI/CD basics"],
    demand: 5,
    salaryRange: "$75K – $200K+ globally",
    topCompanies: ["Google", "Microsoft", "Amazon", "Meta", "Apple", "Stripe", "Airbnb"],
    category: "engineering",
    subPaths: [
      { id: "general", label: "General SE", description: "Balanced full-stack with strong fundamentals." },
      { id: "backend", label: "Backend", description: "APIs, databases, distributed systems, performance." },
      { id: "frontend", label: "Frontend", description: "UI engineering, accessibility, design systems." },
      { id: "fullstack", label: "Full-stack", description: "End-to-end product engineering." },
      { id: "devops", label: "DevOps", description: "Infrastructure, automation, reliability." },
    ],
  },
  {
    id: "web-dev",
    label: "Web Development",
    tagline: "Craft fast, beautiful web experiences",
    description:
      "Web developers build the sites and web apps people use every day. You'll master HTML, CSS, JavaScript, modern frameworks, performance optimization, and accessibility — turning designs into responsive, interactive products.",
    recommendedLanguages: ["javascript", "typescript", "html", "css", "react", "nextjs"],
    skills: ["HTML/CSS", "Responsive design", "Accessibility", "Browser APIs", "Performance"],
    demand: 5,
    salaryRange: "$60K – $160K+ globally",
    topCompanies: ["Vercel", "Shopify", "Figma", "Notion", "Linear", "Stripe"],
    category: "engineering",
  },
  {
    id: "cloud-devops",
    label: "Cloud / DevOps",
    tagline: "Automate and scale infrastructure",
    description:
      "Cloud/DevOps engineers own the platforms that run software. You'll work with containers, orchestration (Kubernetes), infrastructure-as-code, observability, CI/CD pipelines, and cloud providers like AWS, GCP, and Azure to keep systems reliable and cost-efficient.",
    recommendedLanguages: ["python", "bash", "go", "typescript"],
    skills: ["Linux", "Docker", "Kubernetes", "Terraform", "AWS/GCP/Azure", "Monitoring"],
    demand: 5,
    salaryRange: "$90K – $200K+ globally",
    topCompanies: ["AWS", "HashiCorp", "Datadog", "Cloudflare", "GitLab", "Red Hat"],
    category: "systems",
  },
  {
    id: "data-science",
    label: "Data Science",
    tagline: "Turn data into decisions",
    description:
      "Data scientists extract insights from data using statistics, programming, and machine learning. You'll clean and analyze datasets, build predictive models, create dashboards, and communicate findings to drive product and business decisions.",
    recommendedLanguages: ["python", "r", "sql"],
    skills: ["Statistics", "Pandas/NumPy", "Visualization", "SQL", "ML basics", "Communication"],
    demand: 5,
    salaryRange: "$80K – $180K+ globally",
    topCompanies: ["Netflix", "Spotify", "Airbnb", "Meta", "Stitch Fix", "Uber"],
    category: "data",
  },
  {
    id: "ai-ml",
    label: "AI / Machine Learning",
    tagline: "Build intelligent systems",
    description:
      "AI/ML engineers design and deploy machine learning models and AI systems. You'll work with deep learning frameworks, large language models, MLOps pipelines, and production inference — turning research into shipped products.",
    recommendedLanguages: ["python", "rust", "cpp"],
    skills: ["Linear algebra", "PyTorch/TensorFlow", "MLOps", "LLM tooling", "Statistics"],
    demand: 5,
    salaryRange: "$100K – $250K+ globally",
    topCompanies: ["OpenAI", "Anthropic", "DeepMind", "Hugging Face", "NVIDIA", "Tesla"],
    category: "data",
  },
  {
    id: "cybersecurity",
    label: "Cybersecurity",
    tagline: "Defend systems and data",
    description:
      "Cybersecurity professionals protect organizations from threats. You'll learn networking, cryptography, offensive and defensive security, secure coding, and incident response — working as a pentester, SOC analyst, or security engineer.",
    recommendedLanguages: ["python", "bash", "c", "rust"],
    skills: ["Networking", "Cryptography", "OWASP", "Forensics", "Threat modeling"],
    demand: 5,
    salaryRange: "$80K – $190K+ globally",
    topCompanies: ["CrowdStrike", "Cloudflare", "Palo Alto Networks", "Mandiant", "Okta"],
    category: "systems",
  },
  {
    id: "mobile-dev",
    label: "Mobile Development",
    tagline: "Build apps for iOS and Android",
    description:
      "Mobile developers create native and cross-platform apps. You'll learn Swift/Kotlin for native, or React Native/Flutter for cross-platform, and master mobile UX, offline-first design, app store deployment, and performance.",
    recommendedLanguages: ["kotlin", "swift", "dart", "typescript"],
    skills: ["Mobile UX", "Offline-first", "App store deployment", "Mobile performance"],
    demand: 4,
    salaryRange: "$70K – $170K+ globally",
    topCompanies: ["Apple", "Google", "Instagram", "Square", "Duolingo", "Discord"],
    category: "engineering",
  },
  {
    id: "game-dev",
    label: "Game Development",
    tagline: "Build interactive worlds",
    description:
      "Game developers create interactive experiences for console, PC, mobile, and web. You'll work with engines like Unity or Unreal, learn C# or C++, master real-time graphics, physics, and gameplay programming.",
    recommendedLanguages: ["cpp", "csharp", "python"],
    skills: ["Unity/Unreal", "Linear algebra", "Physics", "Shaders", "Gameplay programming"],
    demand: 3,
    salaryRange: "$60K – $150K+ globally",
    topCompanies: ["Epic Games", "Unity", "Riot", "Naughty Dog", "Valve", "Roblox"],
    category: "creative",
  },
  {
    id: "hardware-embedded",
    label: "Hardware / Embedded",
    tagline: "Program the physical world",
    description:
      "Embedded engineers write firmware for microcontrollers, IoT devices, automotive systems, and robotics. You'll work close to the metal with C/C++, real-time operating systems, hardware interfaces, and low-level optimization.",
    recommendedLanguages: ["c", "cpp", "python", "rust"],
    skills: ["Microcontrollers", "RTOS", "Digital electronics", "Debugging", "Memory management"],
    demand: 4,
    salaryRange: "$80K – $170K+ globally",
    topCompanies: ["Tesla", "SpaceX", "Apple", "Bosch", "STM", "NXP"],
    category: "systems",
  },
];

// ============================================================
// LANGUAGES & FRAMEWORKS — 19+ entries with rich metadata
// ============================================================

export const LANGUAGES: LanguageInfo[] = [
  {
    id: "python",
    name: "Python",
    type: "language",
    tagline: "Versatile, readable, ubiquitous",
    description:
      "Python is a high-level, general-purpose language loved for its clean syntax and enormous ecosystem. It powers data science, AI/ML, web backends, automation, scientific computing, and education — making it the most-recommended first language today.",
    demand: 5,
    salaryImpact: "+15-25% over entry-level baseline",
    useCases: ["Web backends (Django/FastAPI)", "Data science & ML", "Automation & scripting", "Scientific computing", "Education"],
    difficulty: 1,
    learningCurve: "Gentle — beginners ship real scripts in hours.",
    trend: "rising",
    topCompanies: ["Google", "Netflix", "Instagram", "Spotify", "OpenAI", "Dropbox"],
    careers: ["software-engineering", "cloud-devops", "data-science", "ai-ml", "cybersecurity"],
    icon: "🐍",
    color: "#3776AB",
  },
  {
    id: "javascript",
    name: "JavaScript",
    type: "language",
    tagline: "The language of the web",
    description:
      "JavaScript runs in every browser and now on servers via Node.js. It's the backbone of web development, with the largest ecosystem of libraries and frameworks. If you build for the web, you need JavaScript.",
    demand: 5,
    salaryImpact: "+10-20% over entry-level baseline",
    useCases: ["Web frontends", "Web backends (Node.js)", "Mobile (React Native)", "Desktop (Electron)", "Browser extensions"],
    difficulty: 2,
    learningCurve: "Easy start, deep mastery takes time due to quirks.",
    trend: "stable",
    topCompanies: ["Meta", "Netflix", "Microsoft", "Stripe", "Airbnb", "Vercel"],
    careers: ["software-engineering", "web-dev", "mobile-dev"],
    icon: "🟨",
    color: "#F7DF1E",
  },
  {
    id: "typescript",
    name: "TypeScript",
    type: "language",
    parentLanguage: "javascript",
    tagline: "JavaScript with types",
    description:
      "TypeScript adds static typing to JavaScript, catching errors at compile time and powering better tooling. It's the default for modern professional web development and is increasingly required at top companies.",
    demand: 5,
    salaryImpact: "+15-25% over JavaScript baseline",
    useCases: ["Large web apps", "Full-stack (Next.js)", "API servers", "Libraries & SDKs", "Enterprise software"],
    difficulty: 3,
    learningCurve: "Moderate — requires understanding JS plus type system.",
    trend: "rising",
    topCompanies: ["Microsoft", "Vercel", "Airbnb", "Slack", "Asana", "Linear"],
    careers: ["software-engineering", "web-dev", "cloud-devops"],
    icon: "🔷",
    color: "#3178C6",
  },
  {
    id: "java",
    name: "Java",
    type: "language",
    tagline: "Write once, run anywhere",
    description:
      "Java is a mature, strongly-typed language that powers enterprise systems, Android apps, large-scale backend services, and big data pipelines. It's verbose but battle-tested and runs in countless production environments.",
    demand: 4,
    salaryImpact: "+10-20% over entry-level baseline",
    useCases: ["Enterprise backends", "Android apps", "Big data (Hadoop/Spark)", "Banking systems", "Spring services"],
    difficulty: 3,
    learningCurve: "Moderate — verbose but consistent and well-documented.",
    trend: "stable",
    topCompanies: ["Google", "Amazon", "Uber", "LinkedIn", "Netflix", "Banks"],
    careers: ["software-engineering", "mobile-dev"],
    icon: "☕",
    color: "#ED8B00",
  },
  {
    id: "c",
    name: "C",
    type: "language",
    tagline: "The foundational systems language",
    description:
      "C is a low-level, procedural language that powers operating systems, embedded devices, compilers, and high-performance software. Learning C teaches you how memory, pointers, and the machine actually work — invaluable for any serious engineer.",
    demand: 4,
    salaryImpact: "+10-15% for systems roles",
    useCases: ["Operating systems", "Embedded firmware", "Compilers", "High-performance libraries", "IoT"],
    difficulty: 4,
    learningCurve: "Steep — manual memory management and pointers.",
    trend: "stable",
    topCompanies: ["Linux Foundation", "Apple", "Microsoft", "Oracle", "Bosch"],
    careers: ["software-engineering", "cybersecurity", "hardware-embedded", "game-dev"],
    icon: "🔵",
    color: "#5C6BC0",
  },
  {
    id: "cpp",
    name: "C++",
    type: "language",
    parentLanguage: "c",
    tagline: "High-performance systems & games",
    description:
      "C++ extends C with object-oriented and generic programming. It powers game engines (Unreal), high-frequency trading, browsers, AAA games, AI infrastructure, and any system that needs raw performance with abstraction.",
    demand: 4,
    salaryImpact: "+15-25% for performance-critical roles",
    useCases: ["Game engines", "High-frequency trading", "Browsers (Chrome, Firefox)", "AI infra (PyTorch backend)", "Real-time systems"],
    difficulty: 5,
    learningCurve: "Very steep — vast language with sharp edges.",
    trend: "stable",
    topCompanies: ["Epic Games", "Google", "Meta", "NVIDIA", "Tesla", "Adobe"],
    careers: ["software-engineering", "ai-ml", "game-dev", "hardware-embedded"],
    icon: "➕",
    color: "#00599C",
  },
  {
    id: "csharp",
    name: "C#",
    type: "language",
    tagline: "Modern, cross-platform, Microsoft",
    description:
      "C# is a modern object-oriented language from Microsoft, used for Windows apps, web (ASP.NET), games (Unity), and cross-platform enterprise software via .NET. Clean syntax, strong tooling, and excellent performance.",
    demand: 4,
    salaryImpact: "+10-20% over entry-level baseline",
    useCases: ["Unity games", "ASP.NET backends", "Windows desktop apps", "Enterprise software", "Azure functions"],
    difficulty: 3,
    learningCurve: "Moderate — clean and consistent if you know Java or C++.",
    trend: "stable",
    topCompanies: ["Microsoft", "Unity", "Stack Overflow", "Accenture", "Deloitte"],
    careers: ["software-engineering", "game-dev", "web-dev"],
    icon: "#️⃣",
    color: "#239120",
  },
  {
    id: "go",
    name: "Go",
    type: "language",
    tagline: "Simple, fast, concurrent",
    description:
      "Go (Golang) is a compiled language from Google designed for simplicity, fast compilation, and excellent concurrency. It's the go-to for cloud infrastructure, microservices, CLIs, and high-throughput backend systems.",
    demand: 4,
    salaryImpact: "+20-30% — high demand, scarce talent",
    useCases: ["Microservices", "Cloud infrastructure (Kubernetes, Docker)", "CLIs", "API servers", "DevOps tooling"],
    difficulty: 2,
    learningCurve: "Gentle — small language, fast to learn.",
    trend: "rising",
    topCompanies: ["Google", "Uber", "Twitch", "Cloudflare", "DigitalOcean", "HashiCorp"],
    careers: ["software-engineering", "cloud-devops"],
    icon: "🐹",
    color: "#00ADD8",
  },
  {
    id: "rust",
    name: "Rust",
    type: "language",
    tagline: "Memory-safe systems programming",
    description:
      "Rust delivers C++-level performance with memory safety guaranteed at compile time. It's the most-loved language for systems work, powering parts of Linux, Windows, browsers, blockchain, and high-performance tooling.",
    demand: 4,
    salaryImpact: "+25-40% — top-paying systems language",
    useCases: ["Systems programming", "WebAssembly", "CLI tools", "Embedded", "Blockchain", "Browser engines"],
    difficulty: 5,
    learningCurve: "Steep — borrow checker forces new mental models.",
    trend: "rising",
    topCompanies: ["Mozilla", "Cloudflare", "Discord", "Microsoft", "Amazon", "Meta"],
    careers: ["software-engineering", "cloud-devops", "ai-ml", "cybersecurity", "hardware-embedded"],
    icon: "🦀",
    color: "#DEA584",
  },
  {
    id: "kotlin",
    name: "Kotlin",
    type: "language",
    tagline: "Modern Android & backend",
    description:
      "Kotlin is the official language for Android development and a modern alternative to Java for backends (Ktor/Spring). Concise, null-safe, and fully interoperable with Java — it's now Google's recommended choice for new Android apps.",
    demand: 4,
    salaryImpact: "+10-20% over Java baseline",
    useCases: ["Android apps", "Backend (Ktor/Spring)", "Cross-platform (KMP)", "Serverless"],
    difficulty: 3,
    learningCurve: "Moderate — easier than Java, modern features.",
    trend: "rising",
    topCompanies: ["Google", "JetBrains", "Square", "Netflix", "Atlassian"],
    careers: ["software-engineering", "mobile-dev"],
    icon: "🟪",
    color: "#7F52FF",
  },
  {
    id: "swift",
    name: "Swift",
    type: "language",
    tagline: "Native iOS & macOS",
    description:
      "Swift is Apple's modern language for iOS, macOS, watchOS, and tvOS development. Fast, safe, and expressive, it powers all new Apple-platform apps. With SwiftUI, you can build complete apps declaratively.",
    demand: 4,
    salaryImpact: "+15-25% for iOS roles",
    useCases: ["iOS apps", "macOS apps", "Apple Watch apps", "Server (Vapor)", "SwiftUI"],
    difficulty: 3,
    learningCurve: "Moderate — modern syntax, good tooling.",
    trend: "stable",
    topCompanies: ["Apple", "Uber", "Airbnb", "Lyft", "Square", "Discord"],
    careers: ["software-engineering", "mobile-dev"],
    icon: "🦅",
    color: "#F05138",
  },
  {
    id: "php",
    name: "PHP",
    type: "language",
    tagline: "Powers the majority of the web",
    description:
      "PHP runs roughly 75% of the web including WordPress, Wikipedia, and Facebook's early days. Modern PHP (8+) is fast, typed, and pleasant — and Laravel is one of the most productive web frameworks available.",
    demand: 3,
    salaryImpact: "+5-15% over entry-level baseline",
    useCases: ["Web backends (Laravel/Symfony)", "WordPress plugins & themes", "CMSs", "E-commerce"],
    difficulty: 2,
    learningCurve: "Easy start, modern PHP is clean.",
    trend: "stable",
    topCompanies: ["Meta (legacy)", "Slack", "Etsy", "Wikipedia", "Mailchimp"],
    careers: ["software-engineering", "web-dev"],
    icon: "🐘",
    color: "#777BB4",
  },
  {
    id: "ruby",
    name: "Ruby",
    type: "language",
    tagline: "Developer happiness above all",
    description:
      "Ruby is a dynamic, object-oriented language famous for developer productivity. With Ruby on Rails, it powers Shopify, GitHub, Airbnb, and countless startups — letting small teams ship fast.",
    demand: 3,
    salaryImpact: "+5-15% over entry-level baseline",
    useCases: ["Web backends (Rails)", "Prototyping", "Internal tools", "Static site generators"],
    difficulty: 2,
    learningCurve: "Gentle — readable syntax, great community.",
    trend: "stable",
    topCompanies: ["GitHub", "Shopify", "Airbnb", "Stripe", "Basecamp"],
    careers: ["software-engineering", "web-dev"],
    icon: "♦️",
    color: "#CC342D",
  },
  {
    id: "sql",
    name: "SQL",
    type: "language",
    tagline: "Query any database",
    description:
      "SQL is the universal language of relational databases. Every full-stack engineer, data scientist, and analyst needs SQL to read and write data in Postgres, MySQL, SQLite, and beyond. It's a must-have skill.",
    demand: 5,
    salaryImpact: "+10-15% — required for data roles",
    useCases: ["Application backends", "Data analytics", "Reporting", "Data warehousing", "BI"],
    difficulty: 2,
    learningCurve: "Easy basics, deep mastery takes practice.",
    trend: "stable",
    topCompanies: ["Every company with a database"],
    careers: ["software-engineering", "data-science", "ai-ml", "web-dev"],
    icon: "🗄️",
    color: "#336791",
  },
  {
    id: "bash",
    name: "Bash / Shell",
    type: "language",
    tagline: "Automate the command line",
    description:
      "Bash and shell scripting glue together Linux/Unix systems. It's essential for DevOps, sysadmin work, automation, and any engineer who lives in the terminal. Learn it once, use it daily forever.",
    demand: 4,
    salaryImpact: "+5-10% for DevOps roles",
    useCases: ["Automation", "DevOps pipelines", "System administration", "Build scripts", "CI/CD"],
    difficulty: 2,
    learningCurve: "Gentle — start with simple commands.",
    trend: "stable",
    topCompanies: ["Every Linux shop", "AWS", "Red Hat", "Cloud providers"],
    careers: ["cloud-devops", "software-engineering", "cybersecurity"],
    icon: "💻",
    color: "#4EAA25",
  },
  {
    id: "r",
    name: "R",
    type: "language",
    tagline: "Statistics & data visualization",
    description:
      "R is purpose-built for statistics, data analysis, and visualization. Beloved by statisticians, researchers, and data scientists for its CRAN ecosystem, ggplot2, and tidyverse.",
    demand: 3,
    salaryImpact: "+10-15% for data roles",
    useCases: ["Statistical analysis", "Data visualization (ggplot2)", "Research", "Bioinformatics", "Reporting"],
    difficulty: 3,
    learningCurve: "Moderate — different paradigm than general-purpose languages.",
    trend: "stable",
    topCompanies: ["Pharma", "Research labs", "Google", "Facebook", "Banks"],
    careers: ["data-science"],
    icon: "📊",
    color: "#276DC3",
  },
  {
    id: "dart",
    name: "Dart",
    type: "language",
    tagline: "Flutter's language",
    description:
      "Dart is Google's UI language, paired with Flutter to build cross-platform mobile, web, and desktop apps from one codebase. Easy to learn if you know Java or JavaScript, with strong tooling and hot reload.",
    demand: 3,
    salaryImpact: "+10-15% for mobile roles",
    useCases: ["Cross-platform apps (Flutter)", "Mobile (iOS + Android)", "Web (Flutter Web)", "Desktop"],
    difficulty: 2,
    learningCurve: "Gentle — familiar C-family syntax.",
    trend: "rising",
    topCompanies: ["Google", "BMW", "Alibaba", "eBay", "Toyota"],
    careers: ["mobile-dev", "software-engineering"],
    icon: "🎯",
    color: "#0175C2",
  },
  {
    id: "react",
    name: "React",
    type: "framework",
    parentLanguage: "javascript",
    tagline: "The dominant UI library",
    description:
      "React is the most popular UI library in the world, powering Facebook, Instagram, Netflix, and millions of other sites. Its component model and hooks API are the industry standard for building modern web UIs.",
    demand: 5,
    salaryImpact: "+15-25% for frontend roles",
    useCases: ["Web apps", "Single-page apps", "Server-rendered sites", "Mobile (React Native)", "Dashboards"],
    difficulty: 3,
    learningCurve: "Moderate — concepts first, then ecosystem.",
    trend: "stable",
    topCompanies: ["Meta", "Netflix", "Airbnb", "Discord", "Vercel", "Notion"],
    careers: ["software-engineering", "web-dev", "mobile-dev"],
    icon: "⚛️",
    color: "#61DAFB",
  },
  {
    id: "nextjs",
    name: "Next.js",
    type: "framework",
    parentLanguage: "typescript",
    tagline: "The React framework for production",
    description:
      "Next.js is the production-grade React framework from Vercel, adding server-side rendering, routing, API routes, image optimization, and deployment out of the box. It's the default starting point for serious React apps.",
    demand: 5,
    salaryImpact: "+20-30% — top-tier full-stack skill",
    useCases: ["Production web apps", "Marketing sites", "SaaS products", "Dashboards", "E-commerce"],
    difficulty: 3,
    learningCurve: "Moderate — React knowledge transfers directly.",
    trend: "rising",
    topCompanies: ["Vercel", "OpenAI", "Notion", "Loom", "Cal.com", "Hugging Face"],
    careers: ["software-engineering", "web-dev"],
    icon: "▲",
    color: "#000000",
  },
  {
    id: "django",
    name: "Django",
    type: "framework",
    parentLanguage: "python",
    tagline: "Batteries-included Python web framework",
    description:
      "Django is a high-level Python web framework with everything included: ORM, auth, admin, forms, security. It powers Instagram, Pinterest, and Disqus — perfect for content-heavy apps and rapid prototyping.",
    demand: 4,
    salaryImpact: "+10-20% for Python backend roles",
    useCases: ["Content sites", "SaaS backends", "CMSs", "Internal tools", "REST APIs (DRF)"],
    difficulty: 3,
    learningCurve: "Moderate — conventions to learn, but very productive.",
    trend: "stable",
    topCompanies: ["Instagram", "Pinterest", "Disqus", "Mozilla", "Spotipy"],
    careers: ["software-engineering", "web-dev"],
    icon: "🦄",
    color: "#092E20",
  },
  {
    id: "fastapi",
    name: "FastAPI",
    type: "framework",
    parentLanguage: "python",
    tagline: "Modern, fast Python APIs",
    description:
      "FastAPI is a modern Python framework for building APIs with type hints, automatic docs, and async support. It's the fastest-growing Python backend framework, used for ML model serving and high-performance microservices.",
    demand: 4,
    salaryImpact: "+15-25% — modern Python backend skill",
    useCases: ["REST APIs", "ML model serving", "Microservices", "Real-time APIs", "SaaS backends"],
    difficulty: 2,
    learningCurve: "Gentle — feels like writing typed Python functions.",
    trend: "rising",
    topCompanies: ["Uber", "Netflix", "Microsoft", "OpenAI", "Stripe"],
    careers: ["software-engineering", "ai-ml", "web-dev"],
    icon: "⚡",
    color: "#009688",
  },
  {
    id: "flask",
    name: "Flask",
    type: "framework",
    parentLanguage: "python",
    tagline: "Micro framework, maximum flexibility",
    description:
      "Flask is a lightweight Python web framework — minimal core, huge extension ecosystem. Perfect when you want fine control, small APIs, or learning projects. Pinned at companies like Pinterest and LinkedIn for select services.",
    demand: 3,
    salaryImpact: "+5-15% for Python backend roles",
    useCases: ["Small APIs", "Prototypes", "Internal tools", "Learning projects", "Microservices"],
    difficulty: 2,
    learningCurve: "Gentle — minimal magic.",
    trend: "stable",
    topCompanies: ["Pinterest", "LinkedIn", "Twilio", "Reddit"],
    careers: ["software-engineering", "web-dev"],
    icon: "🍶",
    color: "#000000",
  },
  {
    id: "html",
    name: "HTML",
    type: "language",
    tagline: "The structure of the web",
    description:
      "HTML is the markup language that defines the structure of every web page. It's the first thing any web developer learns, and semantic HTML is the foundation of accessibility and SEO.",
    demand: 5,
    salaryImpact: "Required for web roles",
    useCases: ["Every web page", "Emails", "Web components", "PWA shells"],
    difficulty: 1,
    learningCurve: "Trivial basics, mastery via accessibility.",
    trend: "stable",
    topCompanies: ["Every company with a website"],
    careers: ["web-dev", "software-engineering"],
    icon: "📄",
    color: "#E34F26",
  },
  {
    id: "css",
    name: "CSS",
    type: "language",
    tagline: "Style the web",
    description:
      "CSS controls how web pages look — layout, color, typography, animation. Modern CSS (Grid, Flexbox, custom properties, container queries) is powerful enough to replace most preprocessor features.",
    demand: 5,
    salaryImpact: "Required for web roles",
    useCases: ["Web page styling", "Responsive design", "Animations", "Design systems", "Theming"],
    difficulty: 3,
    learningCurve: "Easy basics, layout mastery takes time.",
    trend: "stable",
    topCompanies: ["Every company with a website"],
    careers: ["web-dev", "software-engineering"],
    icon: "🎨",
    color: "#1572B6",
  },
];

export const LANGUAGE_MAP: Record<string, LanguageInfo> = Object.fromEntries(
  LANGUAGES.map((l) => [l.id, l]),
);

export const CAREER_MAP: Record<string, CareerInfo> = Object.fromEntries(
  CAREERS.map((c) => [c.id, c]),
);

// ============================================================
// OCCUPATIONS
// ============================================================

export const OCCUPATIONS: OccupationInfo[] = [
  { id: "student", label: "Student (school/university)", pace: "foundational", description: "Full-time student with more availability — plan adds extra depth, fundamentals, and projects." },
  { id: "professional", label: "Working professional", pace: "condensed", description: "Currently employed — plan is condensed to fit evenings/weekends with practical shortcuts." },
  { id: "career-changer", label: "Career changer", pace: "foundational", description: "Switching into tech from another field — plan emphasizes foundations and a portfolio project." },
  { id: "freelancer", label: "Freelancer / self-employed", pace: "condensed", description: "Self-employed with variable schedule — plan is flexible and project-focused." },
  { id: "bootcamp-grad", label: "Bootcamp graduate", pace: "condensed", description: "Already has some training — plan fills gaps and goes deeper on systems & algorithms." },
  { id: "hobbyist", label: "Hobbyist / curious learner", pace: "foundational", description: "Learning for fun or side projects — plan is exploratory and curiosity-driven." },
  { id: "unemployed", label: "Job seeker (full-time available)", pace: "foundational", description: "Full-time available to learn — plan is intensive with job-readiness focus." },
];

export const OCCUPATION_MAP: Record<string, OccupationInfo> = Object.fromEntries(
  OCCUPATIONS.map((o) => [o.id, o]),
);

// ============================================================
// BACKGROUND THEMES — 10 presets + custom
// ============================================================

export type BackgroundTheme = {
  id: string;
  label: string;
  description: string;
  /** Tailwind/CSS gradient or color stops */
  gradient: string;
  /** Swatch color for the picker */
  swatch: string;
};

export const BACKGROUND_THEMES: BackgroundTheme[] = [
  { id: "aurora", label: "Aurora", description: "Default teal-violet-amber aurora", gradient: "radial-gradient(at 20% 20%, rgba(45,212,191,0.18) 0px, transparent 50%), radial-gradient(at 80% 10%, rgba(232,121,249,0.15) 0px, transparent 50%), radial-gradient(at 50% 90%, rgba(252,211,77,0.12) 0px, transparent 50%)", swatch: "#2DD4BF" },
  { id: "ocean", label: "Ocean", description: "Deep blues and teals", gradient: "radial-gradient(at 20% 20%, rgba(56,189,248,0.20) 0px, transparent 50%), radial-gradient(at 80% 30%, rgba(14,165,233,0.18) 0px, transparent 50%), radial-gradient(at 50% 90%, rgba(30,64,175,0.20) 0px, transparent 50%)", swatch: "#0EA5E9" },
  { id: "forest", label: "Forest", description: "Greens and earth tones", gradient: "radial-gradient(at 20% 20%, rgba(34,197,94,0.18) 0px, transparent 50%), radial-gradient(at 80% 30%, rgba(132,204,22,0.16) 0px, transparent 50%), radial-gradient(at 50% 90%, rgba(20,83,45,0.18) 0px, transparent 50%)", swatch: "#22C55E" },
  { id: "sunset", label: "Sunset", description: "Warm oranges and pinks", gradient: "radial-gradient(at 20% 20%, rgba(251,146,60,0.18) 0px, transparent 50%), radial-gradient(at 80% 30%, rgba(236,72,153,0.18) 0px, transparent 50%), radial-gradient(at 50% 90%, rgba(220,38,38,0.16) 0px, transparent 50%)", swatch: "#F97316" },
  { id: "midnight", label: "Midnight", description: "Deep dark navy", gradient: "radial-gradient(at 20% 20%, rgba(99,102,241,0.16) 0px, transparent 50%), radial-gradient(at 80% 30%, rgba(30,27,75,0.50) 0px, transparent 50%), radial-gradient(at 50% 90%, rgba(2,6,23,0.50) 0px, transparent 50%)", swatch: "#1E1B4B" },
  { id: "lavender", label: "Lavender", description: "Soft purples", gradient: "radial-gradient(at 20% 20%, rgba(196,181,253,0.22) 0px, transparent 50%), radial-gradient(at 80% 30%, rgba(167,139,250,0.18) 0px, transparent 50%), radial-gradient(at 50% 90%, rgba(139,92,246,0.16) 0px, transparent 50%)", swatch: "#A78BFA" },
  { id: "rose", label: "Rose", description: "Romantic pinks", gradient: "radial-gradient(at 20% 20%, rgba(251,207,232,0.22) 0px, transparent 50%), radial-gradient(at 80% 30%, rgba(244,114,182,0.18) 0px, transparent 50%), radial-gradient(at 50% 90%, rgba(219,39,119,0.16) 0px, transparent 50%)", swatch: "#F472B6" },
  { id: "mint", label: "Mint", description: "Fresh mints", gradient: "radial-gradient(at 20% 20%, rgba(167,243,208,0.22) 0px, transparent 50%), radial-gradient(at 80% 30%, rgba(110,231,183,0.18) 0px, transparent 50%), radial-gradient(at 50% 90%, rgba(16,185,129,0.16) 0px, transparent 50%)", swatch: "#10B981" },
  { id: "slate", label: "Slate", description: "Cool grays", gradient: "radial-gradient(at 20% 20%, rgba(148,163,184,0.18) 0px, transparent 50%), radial-gradient(at 80% 30%, rgba(100,116,139,0.16) 0px, transparent 50%), radial-gradient(at 50% 90%, rgba(51,65,85,0.18) 0px, transparent 50%)", swatch: "#64748B" },
  { id: "custom", label: "Custom", description: "Pick your own color", gradient: "", swatch: "#6366F1" },
];

export function getBackgroundTheme(id: string, customColor?: string): BackgroundTheme | null {
  if (id === "custom" && customColor) {
    return {
      id: "custom",
      label: "Custom",
      description: "Your custom color",
      gradient: `radial-gradient(at 20% 20%, ${customColor}33 0px, transparent 50%), radial-gradient(at 80% 30%, ${customColor}22 0px, transparent 50%), radial-gradient(at 50% 90%, ${customColor}33 0px, transparent 50%)`,
      swatch: customColor,
    };
  }
  return BACKGROUND_THEMES.find((t) => t.id === id) ?? BACKGROUND_THEMES[0];
}
