import type { Lesson, LessonBlock, QuizQuestion } from "./types";

// ============================================================
// Lesson tracks for languages beyond Python/JavaScript.
// Each language gets a 10-lesson track covering:
//   1. Setup & hello world
//   2. Variables & data types
//   3. Control flow (if/else, loops)
//   4. Functions
//   5. Data structures (arrays, maps, etc.)
//   6. OOP / modules
//   7. File I/O
//   8. Error handling
//   9. Working with APIs
//   10. Capstone project
//
// Code examples use String.raw or escaped strings to avoid
// template literal interpolation conflicts with ${...} syntax
// in the target languages (Kotlin, Swift, Bash, etc.).
// ============================================================

type Code = string; // pre-built code string

type LangSpec = {
  id: string;
  name: string;
  icon: string;
  fileExt: string;
  helloWorld: Code;
  variables: Code;
  controlFlow: Code;
  functions: Code;
  dataStructures: Code;
  oop: Code;
  fileIO: Code;
  errors: Code;
  api: Code;
  capstone: Code;
};

// Helper: build a code string from lines (avoids template literal issues)
function code(...lines: string[]): string {
  return lines.join("\n");
}

const LANGS: LangSpec[] = [
  // ---------- TypeScript ----------
  {
    id: "typescript", name: "TypeScript", icon: "🔷", fileExt: "typescript",
    helloWorld: code(
      "// TypeScript adds static types to JavaScript",
      'const message: string = "Hello, TypeScript!";',
      "console.log(message);",
      "",
      "// Type annotations catch errors at compile time",
      "function greet(name: string): string {",
      "  return `Hello, ${name}!`;",
      "}",
      "",
      'console.log(greet("World"));',
    ),
    variables: code(
      "// TypeScript primitive types",
      'let text: string = "hello";',
      "let count: number = 42;",
      "let isActive: boolean = true;",
      "let nothing: null = null;",
      "",
      "// Arrays",
      "let numbers: number[] = [1, 2, 3];",
      "let mixed: Array<string | number> = [1, \"two\", 3];",
      "",
      "// Type inference",
      'const auto = "inferred as string";',
      "",
      "// Union types",
      "let id: string | number = 123;",
      'id = "abc"; // also OK',
      "",
      "// Interfaces",
      "interface User {",
      "  name: string;",
      "  age: number;",
      "  email?: string;",
      "}",
      "",
      "const user: User = { name: \"Alice\", age: 30 };",
      "console.log(user.name);",
    ),
    controlFlow: code(
      "const age: number = 20;",
      "",
      "if (age < 13) {",
      '  console.log("Child");',
      "} else if (age < 20) {",
      '  console.log("Teen");',
      "} else {",
      '  console.log("Adult");',
      "}",
      "",
      "// Switch with exhaustive checking",
      'type Status = "pending" | "active" | "archived";',
      "function handle(s: Status): string {",
      "  switch (s) {",
      '    case "pending": return "Waiting";',
      '    case "active": return "Live";',
      '    case "archived": return "Done";',
      "  }",
      "}",
      "",
      "// Loops",
      "for (let i = 0; i < 5; i++) console.log(i);",
      "",
      'const items: string[] = ["a", "b", "c"];',
      "for (const item of items) console.log(item);",
    ),
    functions: code(
      "function add(a: number, b: number): number {",
      "  return a + b;",
      "}",
      "",
      "const square = (x: number): number => x * x;",
      "",
      'function greet(name: string, greeting: string = "Hello"): string {',
      "  return `${greeting}, ${name}!`;",
      "}",
      "",
      "function sum(...nums: number[]): number {",
      "  return nums.reduce((a, b) => a + b, 0);",
      "}",
      "",
      "// Generics",
      "function first<T>(arr: T[]): T | undefined {",
      "  return arr[0];",
      "}",
    ),
    dataStructures: code(
      "// Arrays and tuples",
      "let nums: number[] = [1, 2, 3];",
      'let tuple: [string, number] = ["Alice", 30];',
      "",
      "// Objects with interfaces",
      "interface Point { x: number; y: number; }",
      "const p: Point = { x: 1, y: 2 };",
      "",
      "// Maps and Sets",
      "const map = new Map<string, number>();",
      'map.set("a", 1);',
      "",
      "const set = new Set<number>([1, 2, 3]);",
      "",
      "// Records",
      "type UserMap = Record<string, { name: string; age: number }>;",
      "const users: UserMap = {",
      "  alice: { name: \"Alice\", age: 30 },",
      "};",
    ),
    oop: code(
      "class Animal {",
      "  constructor(public name: string) {}",
      "  speak(): string {",
      "    return `${this.name} makes a sound`;",
      "  }",
      "}",
      "",
      "class Dog extends Animal {",
      "  speak(): string {",
      "    return `${this.name} barks`;",
      "  }",
      "}",
      "",
      "const dog = new Dog(\"Buddy\");",
      "console.log(dog.speak());",
      "",
      "// Abstract classes",
      "abstract class Shape { abstract area(): number; }",
      "class Circle extends Shape {",
      "  constructor(public radius: number) { super(); }",
      "  area(): number { return Math.PI * this.radius ** 2; }",
      "}",
      "",
      "// Enums",
      "enum Color { Red, Green, Blue }",
      "const c: Color = Color.Green;",
    ),
    fileIO: code(
      'import { readFileSync, writeFileSync } from "fs";',
      "",
      "// Read a file",
      'const content: string = readFileSync("data.txt", "utf-8");',
      "console.log(content);",
      "",
      "// Write a file",
      'writeFileSync("output.txt", "Hello, world!");',
      "",
      "// Async file I/O",
      'import { promises as fs } from "fs";',
      "",
      "async function readJson<T>(path: string): Promise<T> {",
      '  const raw: string = await fs.readFile(path, "utf-8");',
      "  return JSON.parse(raw) as T;",
      "}",
      "",
      "interface Config { port: number; host: string; }",
      'const config = await readJson<Config>("config.json");',
      "console.log(config.port);",
    ),
    errors: code(
      "try {",
      "  const result: number = riskyOperation();",
      "  console.log(result);",
      "} catch (err) {",
      "  if (err instanceof Error) {",
      "    console.error(err.message);",
      "  } else {",
      "    console.error(String(err));",
      "  }",
      "}",
      "",
      "// Custom error classes",
      "class ValidationError extends Error {",
      "  constructor(public field: string, message: string) {",
      "    super(message);",
      '    this.name = "ValidationError";',
      "  }",
      "}",
      "",
      "function validate(input: string): void {",
      '  if (input.length === 0) {',
      '    throw new ValidationError("name", "Name cannot be empty");',
      "  }",
      "}",
    ),
    api: code(
      "interface User {",
      "  id: number;",
      "  name: string;",
      "  email: string;",
      "}",
      "",
      "async function fetchUser(id: number): Promise<User> {",
      "  const response = await fetch(`/api/users/${id}`);",
      "  if (!response.ok) {",
      "    throw new Error(`HTTP ${response.status}`);",
      "  }",
      "  return (await response.json()) as User;",
      "}",
      "",
      "const user = await fetchUser(1);",
      "console.log(user.name);",
    ),
    capstone: code(
      'type Priority = "low" | "medium" | "high";',
      "",
      "interface Task {",
      "  id: string;",
      "  title: string;",
      "  done: boolean;",
      "  priority: Priority;",
      "}",
      "",
      "class TaskManager {",
      "  private tasks: Map<string, Task> = new Map();",
      "",
      '  add(title: string, priority: Priority = "medium"): Task {',
      "    const task: Task = {",
      "      id: crypto.randomUUID(),",
      "      title,",
      "      done: false,",
      "      priority,",
      "    };",
      "    this.tasks.set(task.id, task);",
      "    return task;",
      "  }",
      "",
      "  complete(id: string): void {",
      "    const task = this.tasks.get(id);",
      "    if (task) task.done = true;",
      "  }",
      "",
      '  list(filter?: "done" | "pending"): Task[] {',
      "    return Array.from(this.tasks.values())",
      '      .filter(t => !filter || (filter === "done" ? t.done : !t.done));',
      "  }",
      "}",
      "",
      "const manager = new TaskManager();",
      'manager.add("Learn TypeScript", "high");',
      'manager.add("Build a project", "medium");',
      "const pending = manager.list(\"pending\");",
      "console.log(`${pending.length} tasks pending`);",
    ),
  },
  // ---------- Java ----------
  {
    id: "java", name: "Java", icon: "☕", fileExt: "java",
    helloWorld: code(
      "// Java — strongly typed, runs on JVM",
      "public class Hello {",
      "    public static void main(String[] args) {",
      '        System.out.println("Hello, Java!");',
      "",
      '        String name = "World";',
      '        System.out.println("Hello, " + name);',
      "    }",
      "}",
    ),
    variables: code(
      "// Java primitive types",
      "int count = 42;",
      "double price = 9.99;",
      "boolean active = true;",
      "char grade = 'A';",
      "long bigNumber = 100_000_000L;",
      "",
      "// Reference types",
      'String name = "Alice";',
      "int[] numbers = {1, 2, 3};",
      "",
      "// var (Java 10+) — type inference",
      'var message = "Hello";',
      "var list = new ArrayList<String>();",
      "",
      "// Constants",
      "final double PI = 3.14159;",
      "",
      "// Type wrappers",
      "Integer boxed = 42;",
      "String s = boxed.toString();",
    ),
    controlFlow: code(
      "int age = 20;",
      "if (age < 13) {",
      '    System.out.println("Child");',
      "} else if (age < 20) {",
      '    System.out.println("Teen");',
      "} else {",
      '    System.out.println("Adult");',
      "}",
      "",
      "// Switch",
      'String day = "MON";',
      "switch (day) {",
      '    case "MON": case "TUE": case "WED":',
      '    case "THU": case "FRI":',
      '        System.out.println("Weekday");',
      "        break;",
      '    case "SAT": case "SUN":',
      '        System.out.println("Weekend");',
      "        break;",
      "    default:",
      '        System.out.println("Unknown");',
      "}",
      "",
      "for (int i = 0; i < 5; i++) System.out.println(i);",
      "int[] nums = {1, 2, 3};",
      "for (int n : nums) System.out.println(n);",
    ),
    functions: code(
      "public class Math {",
      "    public static int add(int a, int b) { return a + b; }",
      "",
      "    // Overloading",
      "    public static double add(double a, double b) { return a + b; }",
      "",
      "    // Varargs",
      "    public static int sum(int... nums) {",
      "        int total = 0;",
      "        for (int n : nums) total += n;",
      "        return total;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(add(2, 3));",
      "        System.out.println(sum(1, 2, 3, 4));",
      "    }",
      "}",
    ),
    dataStructures: code(
      "import java.util.*;",
      "",
      "// ArrayList",
      "List<String> list = new ArrayList<>();",
      'list.add("apple");',
      'list.add("banana");',
      'list.get(0); // "apple"',
      "",
      "// HashMap",
      "Map<String, Integer> ages = new HashMap<>();",
      'ages.put("Alice", 30);',
      'ages.put("Bob", 25);',
      'ages.get("Alice"); // 30',
      "",
      "// HashSet",
      "Set<Integer> set = new HashSet<>();",
      "set.add(1); set.add(2); set.add(1); // size = 2",
      "",
      "// Iterating",
      'for (Map.Entry<String, Integer> entry : ages.entrySet()) {',
      '    System.out.println(entry.getKey() + ": " + entry.getValue());',
      "}",
    ),
    oop: code(
      "class Animal {",
      "    protected String name;",
      "    public Animal(String name) { this.name = name; }",
      "    public String speak() { return name + \" makes a sound\"; }",
      "}",
      "",
      "class Dog extends Animal {",
      "    public Dog(String name) { super(name); }",
      "    @Override",
      "    public String speak() { return name + \" barks\"; }",
      "}",
      "",
      "interface Serializable { String toJSON(); }",
      "",
      "class User implements Serializable {",
      "    private String name;",
      "    public User(String name) { this.name = name; }",
      "    @Override",
      '    public String toJSON() { return "{\\"name\\": \\"" + name + "\\"}"; }',
      "}",
      "",
      "// Abstract classes",
      "abstract class Shape { abstract double area(); }",
      "class Circle extends Shape {",
      "    private double radius;",
      "    public Circle(double r) { this.radius = r; }",
      "    @Override double area() { return Math.PI * radius * radius; }",
      "}",
    ),
    fileIO: code(
      "import java.nio.file.*;",
      "import java.util.List;",
      "",
      "// Modern NIO",
      'String content = Files.readString(Path.of("data.txt"));',
      "System.out.println(content);",
      "",
      "// Write",
      'Files.writeString(Path.of("output.txt"), "Hello, world!");',
      "",
      "// Read all lines",
      'List<String> lines = Files.readAllLines(Path.of("log.txt"));',
      "for (String line : lines) System.out.println(line);",
      "",
      "// try-with-resources",
      'try (BufferedReader br = new BufferedReader(new FileReader("big.txt"))) {',
      "    String line;",
      "    while ((line = br.readLine()) != null) System.out.println(line);",
      "} catch (IOException e) { e.printStackTrace(); }",
    ),
    errors: code(
      "try {",
      "    int result = 10 / 0;",
      "} catch (ArithmeticException e) {",
      '    System.out.println("Math error: " + e.getMessage());',
      "} catch (Exception e) {",
      '    System.out.println("Other: " + e.getMessage());',
      "} finally {",
      '    System.out.println("Always runs");',
      "}",
      "",
      "// Custom exceptions",
      "class ValidationError extends Exception {",
      "    public ValidationError(String message) { super(message); }",
      "}",
      "",
      "public void validate(String input) throws ValidationError {",
      "    if (input == null || input.isEmpty()) {",
      '        throw new ValidationError("Input cannot be empty");',
      "    }",
      "}",
    ),
    api: code(
      "import java.net.*;",
      "import java.net.http.*;",
      "",
      "HttpClient client = HttpClient.newHttpClient();",
      "",
      "HttpRequest request = HttpRequest.newBuilder()",
      '    .uri(URI.create("https://api.example.com/users/1"))',
      '    .header("Accept", "application/json")',
      "    .build();",
      "",
      "HttpResponse<String> response = client.send(",
      "    request, HttpResponse.BodyHandlers.ofString()",
      ");",
      "",
      "System.out.println(response.statusCode());",
      "System.out.println(response.body());",
      "",
      "// POST with JSON",
      'String json = "{\\"name\\": \\"Alice\\"}";',
      "HttpRequest postRequest = HttpRequest.newBuilder()",
      '    .uri(URI.create("https://api.example.com/users"))',
      '    .header("Content-Type", "application/json")',
      "    .POST(HttpRequest.BodyPublishers.ofString(json))",
      "    .build();",
    ),
    capstone: code(
      "import java.util.*;",
      "",
      "class Task {",
      "    private String id, title, priority;",
      "    private boolean done;",
      "    public Task(String id, String title, String priority) {",
      "        this.id = id; this.title = title; this.priority = priority; this.done = false;",
      "    }",
      "    public void complete() { this.done = true; }",
      "    public String getTitle() { return title; }",
      "    public boolean isDone() { return done; }",
      "}",
      "",
      "public class TaskManager {",
      "    private Map<String, Task> tasks = new HashMap<>();",
      "",
      "    public Task add(String title, String priority) {",
      "        String id = UUID.randomUUID().toString();",
      "        Task task = new Task(id, title, priority);",
      "        tasks.put(id, task);",
      "        return task;",
      "    }",
      "",
      "    public void complete(String id) {",
      "        Task t = tasks.get(id);",
      "        if (t != null) t.complete();",
      "    }",
      "",
      "    public List<Task> listPending() {",
      "        List<Task> pending = new ArrayList<>();",
      "        for (Task t : tasks.values()) if (!t.isDone()) pending.add(t);",
      "        return pending;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        TaskManager manager = new TaskManager();",
      '        manager.add("Learn Java", "high");',
      '        manager.add("Build a project", "medium");',
      '        System.out.println("Pending: " + manager.listPending().size());',
      "    }",
      "}",
    ),
  },
  // ---------- C ----------
  {
    id: "c", name: "C", icon: "🔵", fileExt: "c",
    helloWorld: code(
      "// C — compiled, low-level, foundational",
      '#include <stdio.h>',
      "",
      "int main(void) {",
      '    printf("Hello, C!\\n");',
      "",
      '    char name[] = "World";',
      '    printf("Hello, %s!\\n", name);',
      "    return 0;",
      "}",
    ),
    variables: code(
      "#include <stdio.h>",
      "#include <stdbool.h>",
      "",
      "int main(void) {",
      "    int count = 42;",
      "    float price = 9.99f;",
      "    double pi = 3.14159;",
      "    char grade = 'A';",
      "    bool active = true;",
      "",
      "    int numbers[] = {1, 2, 3, 4, 5};",
      '    char name[] = "Alice";',
      "",
      "    int x = 10;",
      "    int *ptr = &x;",
      '    printf("x = %d, *ptr = %d\\n", x, *ptr);',
      "",
      "    const double PI = 3.14159;",
      '    printf("int size: %zu bytes\\n", sizeof(int));',
      "    return 0;",
      "}",
    ),
    controlFlow: code(
      "#include <stdio.h>",
      "",
      "int main(void) {",
      "    int age = 20;",
      '    if (age < 13) printf("Child\\n");',
      '    else if (age < 20) printf("Teen\\n");',
      '    else printf("Adult\\n");',
      "",
      "    int day = 1;",
      "    switch (day) {",
      '        case 1: printf("Monday\\n"); break;',
      '        case 2: printf("Tuesday\\n"); break;',
      '        default: printf("Other\\n");',
      "    }",
      "",
      "    for (int i = 0; i < 5; i++) printf(\"%d\\n\", i);",
      "",
      "    int count = 0;",
      "    while (count < 3) { printf(\"%d\\n\", count); count++; }",
      "    return 0;",
      "}",
    ),
    functions: code(
      "#include <stdio.h>",
      "",
      "int add(int a, int b) { return a + b; }",
      "",
      'void greet(const char *name) { printf("Hello, %s!\\n", name); }',
      "",
      "void increment(int *x) { (*x)++; }",
      "",
      "int main(void) {",
      '    printf("%d\\n", add(2, 3));',
      '    greet("Alice");',
      "    int x = 10; increment(&x);",
      '    printf("%d\\n", x);',
      "    return 0;",
      "}",
    ),
    dataStructures: code(
      "#include <stdio.h>",
      "#include <stdlib.h>",
      "#include <string.h>",
      "",
      "// Arrays",
      "int nums[] = {1, 2, 3, 4, 5};",
      "int length = sizeof(nums) / sizeof(nums[0]);",
      "",
      "// Strings",
      'char name[] = "Alice";',
      "int len = strlen(name);",
      "",
      "// Structs",
      "struct Point { int x; int y; };",
      "struct Point p = {3, 5};",
      '    printf("(%d, %d)\\n", p.x, p.y);',
      "",
      "// Dynamic allocation",
      "int *dynamic = malloc(10 * sizeof(int));",
      "for (int i = 0; i < 10; i++) dynamic[i] = i * 2;",
      "free(dynamic);",
      "",
      "// Typedef",
      "typedef struct { char name[50]; int age; } Person;",
      'Person alice = {"Alice", 30};',
    ),
    oop: code(
      "// C is not OOP, but you can simulate it with structs + function pointers",
      "#include <stdio.h>",
      "#include <string.h>",
      "",
      "typedef struct {",
      "    char name[50];",
      "    void (*speak)(const char *name);",
      "} Animal;",
      "",
      'void animal_speak(const char *name) { printf("%s makes a sound\\n", name); }',
      'void dog_speak(const char *name) { printf("%s barks\\n", name); }',
      "",
      "int main(void) {",
      '    Animal generic = {"Generic", animal_speak};',
      '    Animal dog = {"Buddy", dog_speak};',
      "    generic.speak(generic.name);",
      "    dog.speak(dog.name);",
      "    return 0;",
      "}",
    ),
    fileIO: code(
      "#include <stdio.h>",
      "",
      "int main(void) {",
      '    FILE *f = fopen("output.txt", "w");',
      "    if (f == NULL) { perror(\"Failed\"); return 1; }",
      '    fprintf(f, "Hello, file!\\n");',
      "    fclose(f);",
      "",
      '    FILE *rf = fopen("output.txt", "r");',
      "    char line[256];",
      "    while (fgets(line, sizeof(line), rf) != NULL) printf(\"%s\", line);",
      "    fclose(rf);",
      "    return 0;",
      "}",
    ),
    errors: code(
      "#include <stdio.h>",
      "#include <errno.h>",
      "#include <string.h>",
      "",
      "// C has no exceptions — error handling via return codes + errno",
      "int divide(int a, int b, int *result) {",
      "    if (b == 0) { errno = EINVAL; return -1; }",
      "    *result = a / b;",
      "    return 0;",
      "}",
      "",
      "int main(void) {",
      "    int result;",
      "    if (divide(10, 0, &result) != 0) {",
      '        printf("Error: %s\\n", strerror(errno));',
      "    } else {",
      '        printf("Result: %d\\n", result);',
      "    }",
      "    return 0;",
      "}",
    ),
    api: code(
      "// C doesn't have built-in HTTP — use libcurl",
      "// Compile: gcc -o app app.c -lcurl",
      "#include <stdio.h>",
      "#include <curl/curl.h>",
      "",
      "size_t write_cb(char *ptr, size_t size, size_t nmemb, void *userdata) {",
      "    fwrite(ptr, size, nmemb, stdout);",
      "    return size * nmemb;",
      "}",
      "",
      "int main(void) {",
      "    CURL *curl = curl_easy_init();",
      "    if (!curl) return 1;",
      "",
      '    curl_easy_setopt(curl, CURLOPT_URL, "https://api.example.com/users/1");',
      "    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, write_cb);",
      "    curl_easy_perform(curl);",
      "    curl_easy_cleanup(curl);",
      "    return 0;",
      "}",
    ),
    capstone: code(
      "#include <stdio.h>",
      "#include <string.h>",
      "",
      "#define MAX_TASKS 100",
      "#define MAX_TITLE 100",
      "",
      "typedef struct { int id; char title[MAX_TITLE]; int done; } Task;",
      "",
      "Task tasks[MAX_TASKS];",
      "int task_count = 0;",
      "int next_id = 1;",
      "",
      "int add_task(const char *title) {",
      "    if (task_count >= MAX_TASKS) return -1;",
      "    tasks[task_count].id = next_id++;",
      "    strncpy(tasks[task_count].title, title, MAX_TITLE - 1);",
      "    tasks[task_count].done = 0;",
      "    return tasks[task_count++].id;",
      "}",
      "",
      "void complete_task(int id) {",
      "    for (int i = 0; i < task_count; i++)",
      "        if (tasks[i].id == id) tasks[i].done = 1;",
      "}",
      "",
      "int main(void) {",
      '    add_task("Learn C");',
      '    add_task("Build a project");',
      "    complete_task(1);",
      "    int pending = 0;",
      "    for (int i = 0; i < task_count; i++) if (!tasks[i].done) pending++;",
      '    printf("Pending: %d\\n", pending);',
      "    return 0;",
      "}",
    ),
  },
  // ---------- C++ ----------
  {
    id: "cpp", name: "C++", icon: "➕", fileExt: "cpp",
    helloWorld: code(
      "#include <iostream>",
      "using namespace std;",
      "",
      "int main() {",
      '    cout << "Hello, C++!" << endl;',
      '    string name = "World";',
      '    cout << "Hello, " << name << "!" << endl;',
      "    return 0;",
      "}",
    ),
    variables: code(
      "#include <iostream>",
      "#include <string>",
      "#include <vector>",
      "using namespace std;",
      "",
      "int main() {",
      "    int count = 42;",
      "    double price = 9.99;",
      "    bool active = true;",
      "    string name = \"Alice\";",
      "",
      "    auto msg = \"Hello\"s; // string literal",
      "    const double PI = 3.14159;",
      "",
      "    int arr[] = {1, 2, 3, 4, 5};",
      "    vector<int> nums = {10, 20, 30};",
      "",
      "    int x = 10; int &ref = x; ref = 20;",
      '    cout << count << " " << name << endl;',
      "    return 0;",
      "}",
    ),
    controlFlow: code(
      "#include <iostream>",
      "using namespace std;",
      "",
      "int main() {",
      "    int age = 20;",
      '    if (age < 13) cout << "Child" << endl;',
      '    else if (age < 20) cout << "Teen" << endl;',
      '    else cout << "Adult" << endl;',
      "",
      "    for (int n : {1, 2, 3, 4, 5}) cout << n << endl;",
      "",
      "    int count = 0;",
      "    while (count < 3) { cout << count << endl; count++; }",
      "    return 0;",
      "}",
    ),
    functions: code(
      "#include <iostream>",
      "using namespace std;",
      "",
      "int add(int a, int b) { return a + b; }",
      "",
      'string greet(string name, string greeting = "Hello") {',
      "    return greeting + \", \" + name + \"!\";",
      "}",
      "",
      "void increment(int &x) { x++; }",
      "",
      "template <typename T>",
      "T maximum(T a, T b) { return a > b ? a : b; }",
      "",
      "int main() {",
      "    cout << add(2, 3) << endl;",
      '    cout << greet("Alice") << endl;',
      "    cout << maximum(3, 7) << endl;",
      "    return 0;",
      "}",
    ),
    dataStructures: code(
      "#include <iostream>",
      "#include <vector>",
      "#include <map>",
      "#include <set>",
      "using namespace std;",
      "",
      "int main() {",
      "    vector<int> nums = {1, 2, 3, 4, 5};",
      "    nums.push_back(6);",
      "",
      "    map<string, int> ages;",
      '    ages["Alice"] = 30;',
      '    ages["Bob"] = 25;',
      "",
      "    set<int> unique = {3, 1, 4, 1, 5, 9, 2, 6};",
      "",
      "    for (const auto &n : nums) cout << n << \" \";",
      "    cout << endl;",
      "    return 0;",
      "}",
    ),
    oop: code(
      "#include <iostream>",
      "#include <string>",
      "using namespace std;",
      "",
      "class Animal {",
      "protected:",
      "    string name;",
      "public:",
      "    Animal(string n) : name(n) {}",
      '    virtual string speak() const { return name + " makes a sound"; }',
      "    virtual ~Animal() = default;",
      "};",
      "",
      "class Dog : public Animal {",
      "public:",
      "    Dog(string n) : Animal(n) {}",
      '    string speak() const override { return name + " barks"; }',
      "};",
      "",
      "int main() {",
      '    Dog dog("Buddy");',
      "    cout << dog.speak() << endl;",
      "    return 0;",
      "}",
    ),
    fileIO: code(
      "#include <iostream>",
      "#include <fstream>",
      "using namespace std;",
      "",
      "int main() {",
      '    ofstream out("output.txt");',
      '    out << "Hello, file!" << endl;',
      "    out.close();",
      "",
      '    ifstream in("output.txt");',
      "    string line;",
      "    while (getline(in, line)) cout << line << endl;",
      "    return 0;",
      "}",
    ),
    errors: code(
      "#include <iostream>",
      "#include <stdexcept>",
      "using namespace std;",
      "",
      "double divide(double a, double b) {",
      "    if (b == 0) throw invalid_argument(\"Cannot divide by zero\");",
      "    return a / b;",
      "}",
      "",
      "int main() {",
      "    try { cout << divide(10, 0) << endl; }",
      "    catch (const invalid_argument &e) { cerr << e.what() << endl; }",
      "    return 0;",
      "}",
    ),
    api: code(
      "// C++ HTTP needs a library — use cpr or libcurl",
      "// Example with cpr (https://github.com/libcpr/cpr)",
      "#include <cpr/cpr.h>",
      "#include <iostream>",
      "",
      "int main() {",
      '    auto r = cpr::Get(cpr::Url{"https://api.example.com/users/1"});',
      '    std::cout << "Status: " << r.status_code << std::endl;',
      "    std::cout << r.text << std::endl;",
      "    return 0;",
      "}",
    ),
    capstone: code(
      "#include <iostream>",
      "#include <vector>",
      "#include <string>",
      "using namespace std;",
      "",
      "class Task {",
      "public:",
      "    int id; string title; bool done; string priority;",
      "    Task(int i, string t, string p) : id(i), title(t), done(false), priority(p) {}",
      "};",
      "",
      "class TaskManager {",
      "    vector<Task> tasks;",
      "    int nextId = 1;",
      "public:",
      '    Task add(string title, string priority = "medium") {',
      "        Task t(nextId++, title, priority);",
      "        tasks.push_back(t);",
      "        return t;",
      "    }",
      "    void complete(int id) {",
      "        for (auto &t : tasks) if (t.id == id) t.done = true;",
      "    }",
      "    int pending() const {",
      "        int count = 0;",
      "        for (const auto &t : tasks) if (!t.done) count++;",
      "        return count;",
      "    }",
      "};",
      "",
      "int main() {",
      "    TaskManager manager;",
      '    manager.add("Learn C++", "high");',
      '    manager.add("Build a project", "medium");',
      "    manager.complete(1);",
      '    cout << "Pending: " << manager.pending() << endl;',
      "    return 0;",
      "}",
    ),
  },
  // ---------- C# ----------
  {
    id: "csharp", name: "C#", icon: "#️⃣", fileExt: "csharp",
    helloWorld: code(
      "using System;",
      "",
      "class Program {",
      "    static void Main() {",
      '        Console.WriteLine("Hello, C#!");',
      '        string name = "World";',
      '        Console.WriteLine($"Hello, {name}!");',
      "    }",
      "}",
    ),
    variables: code(
      "using System;",
      "using System.Collections.Generic;",
      "",
      "class Program {",
      "    static void Main() {",
      "        int count = 42;",
      "        double price = 9.99;",
      "        bool active = true;",
      '        string name = "Alice";',
      "        var msg = \"Hello\";",
      "        const double PI = 3.14159;",
      "        int? maybeNull = null;",
      "        int[] nums = {1, 2, 3, 4, 5};",
      '        var list = new List<string> { "apple", "banana" };',
      "        var dict = new Dictionary<string, int>();",
      '        dict["Alice"] = 30;',
      '        Console.WriteLine($"{name} is {dict[\"Alice\"]}");',
      "    }",
      "}",
    ),
    controlFlow: code(
      "using System;",
      "",
      "class Program {",
      "    static void Main() {",
      "        int age = 20;",
      '        if (age < 13) Console.WriteLine("Child");',
      '        else if (age < 20) Console.WriteLine("Teen");',
      '        else Console.WriteLine("Adult");',
      "",
      "        var day = 1;",
      "        switch (day) {",
      '            case 1: case 2: case 3: case 4: case 5:',
      '                Console.WriteLine("Weekday"); break;',
      '            case 6: case 7:',
      '                Console.WriteLine("Weekend"); break;',
      "        }",
      "",
      "        for (int i = 0; i < 5; i++) Console.WriteLine(i);",
      "        var items = new[] {1, 2, 3};",
      "        foreach (var n in items) Console.WriteLine(n);",
      "    }",
      "}",
    ),
    functions: code(
      "using System;",
      "",
      "class Program {",
      "    static int Add(int a, int b) => a + b;",
      '    static string Greet(string name, string greeting = "Hello") => $"{greeting}, {name}!";',
      "    static int Sum(params int[] nums) {",
      "        var sum = 0; foreach (var n in nums) sum += n; return sum;",
      "    }",
      "    static void Main() {",
      "        Console.WriteLine(Add(2, 3));",
      "        Console.WriteLine(Greet(\"Alice\"));",
      "        Console.WriteLine(Sum(1, 2, 3, 4));",
      "    }",
      "}",
    ),
    dataStructures: code(
      "using System;",
      "using System.Collections.Generic;",
      "using System.Linq;",
      "",
      "class Program {",
      "    static void Main() {",
      "        var list = new List<int> {1, 2, 3, 4, 5};",
      "        list.Add(6);",
      "",
      "        var dict = new Dictionary<string, int> {",
      '            ["Alice"] = 30,',
      '            ["Bob"] = 25,',
      "        };",
      "",
      "        var set = new HashSet<int> {1, 2, 3, 1, 2};",
      "",
      "        // LINQ",
      "        var nums = new List<int> {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};",
      "        var evens = nums.Where(n => n % 2 == 0).ToList();",
      "        var sum = nums.Sum();",
      '        Console.WriteLine($"Evens: {evens.Count}, Sum: {sum}");',
      "    }",
      "}",
    ),
    oop: code(
      "using System;",
      "",
      "class Animal {",
      "    public string Name { get; set; }",
      "    public Animal(string name) { Name = name; }",
      '    public virtual string Speak() => $"{Name} makes a sound";',
      "}",
      "",
      "class Dog : Animal {",
      "    public Dog(string name) : base(name) {}",
      '    public override string Speak() => $"{Name} barks";',
      "}",
      "",
      "abstract class Shape { public abstract double Area(); }",
      "class Circle : Shape {",
      "    public double Radius { get; set; }",
      "    public Circle(double r) { Radius = r; }",
      "    public override double Area() => Math.PI * Radius * Radius;",
      "}",
      "",
      "record Person(string Name, int Age);",
      "",
      "class Program {",
      "    static void Main() {",
      '        var dog = new Dog("Buddy");',
      "        Console.WriteLine(dog.Speak());",
      '        var p = new Person("Alice", 30);',
      "        Console.WriteLine(p);",
      "    }",
      "}",
    ),
    fileIO: code(
      "using System;",
      "using System.IO;",
      "using System.Text.Json;",
      "using System.Threading.Tasks;",
      "",
      "class Program {",
      "    static async Task Main() {",
      '        await File.WriteAllTextAsync("output.txt", "Hello, file!\\n");',
      '        string content = await File.ReadAllTextAsync("output.txt");',
      "        Console.WriteLine(content);",
      "",
      "        var lines = await File.ReadAllLinesAsync(\"log.txt\");",
      "        foreach (var line in lines) Console.WriteLine(line);",
      "",
      "        var data = new { name = \"Alice\", age = 30 };",
      "        string json = JsonSerializer.Serialize(data);",
      '        await File.WriteAllTextAsync("data.json", json);',
      "    }",
      "}",
    ),
    errors: code(
      "using System;",
      "",
      "class Program {",
      "    static void Main() {",
      "        try {",
      "            int result = 10 / int.Parse(\"0\");",
      "        } catch (DivideByZeroException e) {",
      '            Console.WriteLine($"Div error: {e.Message}");',
      "        } catch (FormatException e) {",
      '            Console.WriteLine($"Format: {e.Message}");',
      "        } catch (Exception e) {",
      '            Console.WriteLine($"Other: {e.Message}");',
      "        } finally {",
      '            Console.WriteLine("Always runs");',
      "        }",
      "    }",
      "}",
    ),
    api: code(
      "using System;",
      "using System.Net.Http;",
      "using System.Text;",
      "using System.Text.Json;",
      "using System.Threading.Tasks;",
      "",
      "class Program {",
      "    static readonly HttpClient client = new HttpClient();",
      "",
      "    static async Task Main() {",
      '        var response = await client.GetAsync("https://api.example.com/users/1");',
      "        response.EnsureSuccessStatusCode();",
      "        var body = await response.Content.ReadAsStringAsync();",
      "        Console.WriteLine(body);",
      "",
      "        var data = new { name = \"Alice\", age = 30 };",
      "        var json = JsonSerializer.Serialize(data);",
      "        var content = new StringContent(json, Encoding.UTF8, \"application/json\");",
      '        await client.PostAsync("https://api.example.com/users", content);',
      "    }",
      "}",
    ),
    capstone: code(
      "using System;",
      "using System.Collections.Generic;",
      "using System.Linq;",
      "",
      "class Task {",
      "    public int Id { get; set; }",
      "    public string Title { get; set; }",
      "    public bool Done { get; set; }",
      "    public string Priority { get; set; }",
      "}",
      "",
      "class TaskManager {",
      "    private List<Task> tasks = new List<Task>();",
      "    private int nextId = 1;",
      "",
      '    public Task Add(string title, string priority = "medium") {',
      "        var t = new Task { Id = nextId++, Title = title, Priority = priority };",
      "        tasks.Add(t);",
      "        return t;",
      "    }",
      "    public void Complete(int id) {",
      "        var t = tasks.FirstOrDefault(x => x.Id == id);",
      "        if (t != null) t.Done = true;",
      "    }",
      "    public List<Task> Pending() => tasks.Where(t => !t.Done).ToList();",
      "}",
      "",
      "class Program {",
      "    static void Main() {",
      "        var manager = new TaskManager();",
      '        manager.Add("Learn C#", "high");',
      '        manager.Add("Build a project", "medium");',
      "        manager.Complete(1);",
      '        Console.WriteLine($"Pending: {manager.Pending().Count}");',
      "    }",
      "}",
    ),
  },
  // ---------- Go ----------
  {
    id: "go", name: "Go", icon: "🐹", fileExt: "go",
    helloWorld: code(
      "package main",
      "",
      'import "fmt"',
      "",
      "func main() {",
      '    fmt.Println("Hello, Go!")',
      "",
      '    name := "World"',
      '    fmt.Printf("Hello, %s!\\n", name)',
      "}",
    ),
    variables: code(
      "package main",
      'import "fmt"',
      "",
      "func main() {",
      "    count := 42",
      "    price := 9.99",
      "    active := true",
      '    name := "Alice"',
      "    var age int = 30",
      "    const Pi = 3.14159",
      "    a, b := 1, 2",
      "    var arr [5]int = [5]int{1, 2, 3, 4, 5}",
      "    nums := []int{10, 20, 30}",
      "    nums = append(nums, 40)",
      '    fmt.Println(count, name, age, a, b, arr, nums)',
      "}",
    ),
    controlFlow: code(
      "package main",
      'import "fmt"',
      "",
      "func main() {",
      "    age := 20",
      '    if age < 13 { fmt.Println("Child") }',
      '    else if age < 20 { fmt.Println("Teen") }',
      '    else { fmt.Println("Adult") }',
      "",
      "    day := 1",
      "    switch day {",
      '    case 1: fmt.Println("Monday")',
      '    case 2: fmt.Println("Tuesday")',
      '    default: fmt.Println("Other")',
      "    }",
      "",
      "    for i := 0; i < 5; i++ { fmt.Println(i) }",
      "",
      "    count := 0",
      "    for count < 3 { fmt.Println(count); count++ }",
      "}",
    ),
    functions: code(
      "package main",
      'import "fmt"',
      "",
      "func add(a, b int) int { return a + b }",
      "",
      "func divmod(a, b int) (int, int) { return a / b, a % b }",
      "",
      "func sum(nums ...int) int {",
      "    total := 0",
      "    for _, n := range nums { total += n }",
      "    return total",
      "}",
      "",
      "func main() {",
      "    fmt.Println(add(2, 3))",
      "    q, r := divmod(17, 5)",
      "    fmt.Println(q, r)",
      "    fmt.Println(sum(1, 2, 3, 4))",
      "}",
    ),
    dataStructures: code(
      "package main",
      'import "fmt"',
      "",
      "func main() {",
      "    nums := []int{1, 2, 3, 4, 5}",
      "    nums = append(nums, 6)",
      "",
      "    ages := map[string]int{",
      "        \"Alice\": 30,",
      "        \"Bob\":   25,",
      "    }",
      '    ages["Carol"] = 28',
      "    delete(ages, \"Bob\")",
      "",
      "    type Point struct { X, Y int }",
      "    p := Point{X: 1, Y: 2}",
      "    fmt.Println(p)",
      "}",
    ),
    oop: code(
      "package main",
      'import "fmt"',
      "",
      "// Go uses structs + methods + interfaces (no classes)",
      "type Animal struct { Name string }",
      "",
      'func (a *Animal) Speak() string { return a.Name + " makes a sound" }',
      "",
      "type Dog struct { Animal }",
      "",
      'func (d *Dog) Speak() string { return d.Name + " barks" }',
      "",
      "type Speaker interface { Speak() string }",
      "",
      "func main() {",
      '    dog := &Dog{Animal{Name: "Buddy"}}',
      "    fmt.Println(dog.Speak())",
      "    var s Speaker = dog",
      "    fmt.Println(s.Speak())",
      "}",
    ),
    fileIO: code(
      "package main",
      "import (",
      '    "fmt"',
      '    "os"',
      '    "encoding/json"',
      ")",
      "",
      "func main() {",
      '    err := os.WriteFile("output.txt", []byte("Hello, file!\\n"), 0644)',
      "    if err != nil { panic(err) }",
      "",
      '    data, err := os.ReadFile("output.txt")',
      "    if err != nil { panic(err) }",
      "    fmt.Println(string(data))",
      "",
      "    type User struct {",
      '        Name string `json:"name"`',
      '        Age  int    `json:"age"`',
      "    }",
      '    user := User{Name: "Alice", Age: 30}',
      "    js, _ := json.Marshal(user)",
      '    os.WriteFile("user.json", js, 0644)',
      "}",
    ),
    errors: code(
      "package main",
      "import (",
      '    "fmt"',
      '    "errors"',
      ")",
      "",
      "func divide(a, b float64) (float64, error) {",
      "    if b == 0 {",
      '        return 0, errors.New("cannot divide by zero")',
      "    }",
      "    return a / b, nil",
      "}",
      "",
      "func main() {",
      "    result, err := divide(10, 0)",
      "    if err != nil {",
      '        fmt.Println("Error:", err)',
      "        return",
      "    }",
      "    fmt.Println(result)",
      "}",
    ),
    api: code(
      "package main",
      "import (",
      '    "encoding/json"',
      '    "fmt"',
      '    "io"',
      '    "net/http"',
      ")",
      "",
      "type User struct {",
      "    ID   int    `json:\"id\"`",
      "    Name string `json:\"name\"`",
      "}",
      "",
      "func main() {",
      '    resp, err := http.Get("https://api.example.com/users/1")',
      "    if err != nil { panic(err) }",
      "    defer resp.Body.Close()",
      "",
      "    body, _ := io.ReadAll(resp.Body)",
      "    fmt.Println(string(body))",
      "",
      "    var user User",
      "    json.Unmarshal(body, &user)",
      "    fmt.Println(user.Name)",
      "}",
    ),
    capstone: code(
      "package main",
      'import "fmt"',
      "",
      "type Task struct {",
      "    ID       int",
      "    Title    string",
      "    Done     bool",
      "    Priority string",
      "}",
      "",
      "type TaskManager struct {",
      "    tasks  []Task",
      "    nextID int",
      "}",
      "",
      "func (m *TaskManager) Add(title, priority string) Task {",
      "    t := Task{ID: m.nextID, Title: title, Priority: priority}",
      "    m.nextID++",
      "    m.tasks = append(m.tasks, t)",
      "    return t",
      "}",
      "",
      "func (m *TaskManager) Complete(id int) {",
      "    for i := range m.tasks {",
      "        if m.tasks[i].ID == id { m.tasks[i].Done = true; return }",
      "    }",
      "}",
      "",
      "func (m *TaskManager) Pending() []Task {",
      "    var pending []Task",
      "    for _, t := range m.tasks {",
      "        if !t.Done { pending = append(pending, t) }",
      "    }",
      "    return pending",
      "}",
      "",
      "func main() {",
      "    m := &TaskManager{}",
      '    m.Add("Learn Go", "high")',
      '    m.Add("Build a project", "medium")',
      "    m.Complete(1)",
      '    fmt.Printf("Pending: %d\\n", len(m.Pending()))',
      "}",
    ),
  },
  // ---------- Rust ----------
  {
    id: "rust", name: "Rust", icon: "🦀", fileExt: "rust",
    helloWorld: code(
      "fn main() {",
      '    println!("Hello, Rust!");',
      "",
      '    let name = "World";',
      '    println!("Hello, {}!", name);',
      "}",
    ),
    variables: code(
      "fn main() {",
      "    let count = 42;",
      '    let name = "Alice";',
      "    let mut counter = 0;",
      "    counter += 1;",
      "    const PI: f64 = 3.14159;",
      "    let price: f64 = 9.99;",
      "    let active: bool = true;",
      "",
      "    let x = 5;",
      "    let x = x * 2;",
      "",
      "    let pair: (i32, &str) = (1, \"hello\");",
      "    let arr: [i32; 5] = [1, 2, 3, 4, 5];",
      "    let mut nums = vec![1, 2, 3];",
      "    nums.push(4);",
      "",
      '    println!("{} {}", count, name);',
      "}",
    ),
    controlFlow: code(
      "fn main() {",
      "    let age = 20;",
      "",
      '    if age < 13 { println!("Child") }',
      '    else if age < 20 { println!("Teen") }',
      '    else { println!("Adult") }',
      "",
      "    let day = 1;",
      "    match day {",
      '        1 | 2 | 3 | 4 | 5 => println!("Weekday"),',
      '        6 | 7 => println!("Weekend"),',
      '        _ => println!("Other"),',
      "    }",
      "",
      "    for i in 0..5 { println!(\"{}\", i); }",
      "",
      "    let mut count = 0;",
      "    while count < 3 {",
      "        println!(\"{}\", count);",
      "        count += 1;",
      "    }",
      "}",
    ),
    functions: code(
      "fn add(a: i32, b: i32) -> i32 { a + b }",
      "",
      "fn divmod(a: i32, b: i32) -> (i32, i32) {",
      "    (a / b, a % b)",
      "}",
      "",
      "fn main() {",
      "    println!(\"{}\", add(2, 3));",
      "    let (q, r) = divmod(17, 5);",
      "    println!(\"{} {}\", q, r);",
      "",
      "    let square = |x: i32| x * x;",
      "    println!(\"{}\", square(5));",
      "",
      "    let nums = vec![1, 2, 3, 4, 5];",
      "    let doubled: Vec<i32> = nums.iter().map(|&x| x * 2).collect();",
      "    let sum: i32 = nums.iter().sum();",
      "    println!(\"{:?} {}\", doubled, sum);",
      "}",
    ),
    dataStructures: code(
      "use std::collections::{HashMap, HashSet};",
      "",
      "fn main() {",
      "    let mut nums = vec![1, 2, 3, 4, 5];",
      "    nums.push(6);",
      "",
      "    let mut ages: HashMap<&str, i32> = HashMap::new();",
      "    ages.insert(\"Alice\", 30);",
      "    ages.insert(\"Bob\", 25);",
      "",
      "    let mut set: HashSet<i32> = HashSet::new();",
      "    set.insert(1);",
      "    set.insert(2);",
      "",
      "    struct Point { x: i32, y: i32 }",
      "    let p = Point { x: 1, y: 2 };",
      "",
      "    enum Color { Red, Green, Blue }",
      "    let c = Color::Green;",
      "}",
    ),
    oop: code(
      "// Rust uses structs + traits instead of classes",
      "struct Animal { name: String }",
      "",
      "impl Animal {",
      "    fn new(name: &str) -> Self { Animal { name: name.to_string() } }",
      '    fn speak(&self) -> String { format!("{} makes a sound", self.name) }',
      "}",
      "",
      "struct Dog { animal: Animal }",
      "",
      "impl Dog {",
      "    fn new(name: &str) -> Self { Dog { animal: Animal::new(name) } }",
      '    fn speak(&self) -> String { format!("{} barks", self.animal.name) }',
      "}",
      "",
      "trait Speaker { fn speak(&self) -> String; }",
      "impl Speaker for Animal { fn speak(&self) -> String { self.speak() } }",
      "impl Speaker for Dog { fn speak(&self) -> String { self.speak() } }",
      "",
      "fn main() {",
      '    let dog = Dog::new("Buddy");',
      "    println!(\"{}\", dog.speak());",
      "}",
    ),
    fileIO: code(
      "use std::fs;",
      "use std::io::{self, BufRead};",
      "",
      "fn main() -> io::Result<()> {",
      "    fs::write(\"output.txt\", \"Hello, file!\\n\")?;",
      "    let content = fs::read_to_string(\"output.txt\")?;",
      "    println!(\"{}\", content);",
      "",
      "    let file = std::fs::File::open(\"big.txt\")?;",
      "    let reader = io::BufReader::new(file);",
      "    for line in reader.lines() {",
      "        println!(\"{}\", line?);",
      "    }",
      "    Ok(())",
      "}",
    ),
    errors: code(
      "use std::error::Error;",
      "use std::fmt;",
      "",
      "#[derive(Debug)]",
      "struct ValidationError { field: String, message: String }",
      "",
      "impl fmt::Display for ValidationError {",
      "    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {",
      "        write!(f, \"{}: {}\", self.field, self.message)",
      "    }",
      "}",
      "impl Error for ValidationError {}",
      "",
      "fn divide(a: f64, b: f64) -> Result<f64, String> {",
      "    if b == 0.0 {",
      "        Err(String::from(\"cannot divide by zero\"))",
      "    } else { Ok(a / b) }",
      "}",
      "",
      "fn main() {",
      "    match divide(10.0, 0.0) {",
      "        Ok(result) => println!(\"{}\", result),",
      "        Err(e) => eprintln!(\"Error: {}\", e),",
      "    }",
      "}",
    ),
    api: code(
      "// Add to Cargo.toml: reqwest = { version = \"0.11\", features = [\"json\"] }",
      "//                    tokio = { version = \"1\", features = [\"full\"] }",
      "//                    serde = { version = \"1\", features = [\"derive\"] }",
      "use serde::Deserialize;",
      "",
      "#[derive(Deserialize, Debug)]",
      "struct User { id: i32, name: String }",
      "",
      "#[tokio::main]",
      "async fn main() -> Result<(), Box<dyn std::error::Error>> {",
      "    let resp = reqwest::get(\"https://api.example.com/users/1\").await?;",
      "    let user: User = resp.json().await?;",
      "    println!(\"{:?}\", user);",
      "    Ok(())",
      "}",
    ),
    capstone: code(
      "use std::collections::HashMap;",
      "",
      "#[derive(Debug, Clone)]",
      "struct Task {",
      "    id: u32,",
      "    title: String,",
      "    done: bool,",
      "    priority: String,",
      "}",
      "",
      "struct TaskManager {",
      "    tasks: HashMap<u32, Task>,",
      "    next_id: u32,",
      "}",
      "",
      "impl TaskManager {",
      "    fn new() -> Self {",
      "        TaskManager { tasks: HashMap::new(), next_id: 1 }",
      "    }",
      "    fn add(&mut self, title: &str, priority: &str) -> u32 {",
      "        let id = self.next_id;",
      "        self.next_id += 1;",
      "        self.tasks.insert(id, Task {",
      "            id,",
      "            title: title.to_string(),",
      "            done: false,",
      "            priority: priority.to_string(),",
      "        });",
      "        id",
      "    }",
      "    fn complete(&mut self, id: u32) {",
      "        if let Some(task) = self.tasks.get_mut(&id) { task.done = true; }",
      "    }",
      "    fn pending(&self) -> Vec<&Task> {",
      "        self.tasks.values().filter(|t| !t.done).collect()",
      "    }",
      "}",
      "",
      "fn main() {",
      "    let mut manager = TaskManager::new();",
      "    manager.add(\"Learn Rust\", \"high\");",
      "    manager.add(\"Build a project\", \"medium\");",
      "    manager.complete(1);",
      "    println!(\"Pending: {}\", manager.pending().len());",
      "}",
    ),
  },
];

// ============================================================
// Build a 10-lesson track from a LangSpec
// ============================================================

function buildTrack(spec: LangSpec): Lesson[] {
  const langName = spec.name;
  const langId = spec.id;
  const trackId = langId as "typescript" | "java" | "c";

  const make = (
    n: number,
    title: string,
    desc: string,
    codeContent: string,
    q: QuizQuestion,
  ): Lesson => ({
    id: `${langId}-${String(n).padStart(2, "0")}`,
    track: trackId,
    order: n,
    title,
    description: desc,
    difficulty: n <= 3 ? "beginner" : n <= 7 ? "intermediate" : "advanced",
    estMinutes: 30 + n * 5,
    blocks: [
      { kind: "heading", content: title },
      { kind: "text", content: `${desc} This lesson covers ${langName}-specific syntax and patterns.` },
      { kind: "code", language: spec.fileExt, code: codeContent, caption: `${langName} example` },
      { kind: "tip", content: "Practice each concept by modifying the example and running it locally." },
    ],
    quiz: [q],
  });

  return [
    make(1, `Getting Started with ${langName}`, `Install ${langName}, write your first program.`, spec.helloWorld,
      { id: "q1", question: `What file extension do ${langName} files use?`, options: [`.${spec.fileExt}`, ".txt", ".code", ".exe"], correctIndex: 0 }),
    make(2, `Variables and Types in ${langName}`, `Learn ${langName}'s type system and variables.`, spec.variables,
      { id: "q1", question: `Which is a primitive type in ${langName}?`, options: ["int", "object", "list", "function"], correctIndex: 0 }),
    make(3, `Control Flow in ${langName}`, `Make decisions and repeat work.`, spec.controlFlow,
      { id: "q1", question: `Which keyword starts a conditional in ${langName}?`, options: ["if", "when", "case", "cond"], correctIndex: 0 }),
    make(4, `Functions in ${langName}`, `Package logic into reusable functions.`, spec.functions,
      { id: "q1", question: `What's the keyword to define a function in ${langName}?`, options: ["function", "func", "def", "fn"], correctIndex: 1 }),
    make(5, `Data Structures in ${langName}`, `Work with collections.`, spec.dataStructures,
      { id: "q1", question: `Which is a collection type in ${langName}?`, options: ["Array", "List", "Map", "All of the above"], correctIndex: 3 }),
    make(6, `OOP and Modules in ${langName}`, `Structure larger programs.`, spec.oop,
      { id: "q1", question: `Does ${langName} support classes or structs?`, options: ["Yes", "No", "Only structs", "Only classes"], correctIndex: 0 }),
    make(7, `File I/O in ${langName}`, `Read and write files.`, spec.fileIO,
      { id: "q1", question: `What should you always do after opening a file?`, options: ["Nothing", "Close it", "Lock it", "Encrypt it"], correctIndex: 1 }),
    make(8, `Error Handling in ${langName}`, `Handle errors gracefully.`, spec.errors,
      { id: "q1", question: `What's the keyword for catching errors in ${langName}?`, options: ["catch", "rescue", "except", "handle"], correctIndex: 0 }),
    make(9, `Working with APIs in ${langName}`, `Call REST APIs.`, spec.api,
      { id: "q1", question: `What's the standard HTTP status for success?`, options: ["200", "404", "500", "100"], correctIndex: 0 }),
    make(10, `Capstone Project in ${langName}`, `Build a small project.`, spec.capstone,
      { id: "q1", question: `What's the best way to learn ${langName}?`, options: ["Read only", "Build projects", "Watch only", "Memorize syntax"], correctIndex: 1 }),
  ];
}

// Generate lessons for all languages
export const EXTRA_LANGUAGE_LESSONS: Lesson[] = LANGS.flatMap(buildTrack);

export const EXTRA_LANGUAGES = LANGS.map((l) => ({
  id: l.id,
  name: l.name,
  icon: l.icon,
}));
