import type { Lesson } from "./types";

// ============================================================
// 15 Python lessons + 15 JavaScript lessons = 30 total
// ============================================================

export const PYTHON_LESSONS: Lesson[] = [
  {
    id: "py-01",
    track: "python",
    order: 1,
    title: "Getting Started with Python",
    description: "Install Python, write your first program, and understand the REPL.",
    difficulty: "beginner",
    estMinutes: 30,
    blocks: [
      { kind: "heading", content: "What is Python?" },
      { kind: "text", content: "Python is a high-level, general-purpose programming language created by Guido van Rossum in 1991. It emphasizes readability, simplicity, and a gentle learning curve — which is why it's the most-recommended first language today. Python powers data science, AI/ML, web backends (Django, FastAPI), automation, scientific computing, and education. Companies like Google, Netflix, Instagram, and OpenAI rely on it heavily." },
      { kind: "heading", content: "Installing Python" },
      { kind: "text", content: "Download Python 3 from python.org and run the installer. On macOS and Linux, Python is often pre-installed — verify with `python3 --version`. On Windows, ensure you check 'Add Python to PATH' during installation." },
      { kind: "code", language: "bash", code: "python3 --version\n# Python 3.12.0", caption: "Check your Python version" },
      { kind: "heading", content: "Your First Program" },
      { kind: "text", content: "The tradition is to print 'Hello, World!'. In Python, this is one line:" },
      { kind: "code", language: "python", code: 'print("Hello, World!")', caption: "hello.py" },
      { kind: "tip", content: "Save this as `hello.py` and run it with `python3 hello.py`. Congrats — you've written your first Python program!" },
      { kind: "heading", content: "The Python REPL" },
      { kind: "text", content: "Type `python3` with no arguments and you'll enter the REPL (Read-Eval-Print Loop) — an interactive shell where you can experiment with code line-by-line. Use it to test ideas quickly." },
      { kind: "warning", content: "Press Ctrl+D (or type `exit()`) to leave the REPL. Don't confuse it with a regular shell." },
    ],
    quiz: [
      {
        id: "q1",
        question: "Who created Python?",
        options: ["Linus Torvalds", "Guido van Rossum", "Dennis Ritchie", "Brendan Eich"],
        correctIndex: 1,
        explanation: "Guido van Rossum began working on Python in 1989 and released the first version in 1991.",
      },
      {
        id: "q2",
        question: "What does the print() function do?",
        options: ["Sends text to a printer", "Displays output to the console", "Creates a file", "Sends an email"],
        correctIndex: 1,
        explanation: "print() writes text to standard output (usually the terminal).",
      },
      {
        id: "q3",
        question: "How do you check your Python version from the terminal?",
        options: ["python version", "python3 --version", "python -v", "show python"],
        correctIndex: 1,
      },
    ],
    deepDiveResources: [
      { label: "Official Python Tutorial", url: "https://docs.python.org/3/tutorial/", kind: "doc" },
      { label: "Real Python — Getting Started", url: "https://realpython.com/learning-paths/python-basics/", kind: "article" },
    ],
  },
  {
    id: "py-02",
    track: "python",
    order: 2,
    title: "Variables and Data Types",
    description: "Store data in variables and learn Python's core types.",
    difficulty: "beginner",
    estMinutes: 45,
    blocks: [
      { kind: "heading", content: "What is a variable?" },
      { kind: "text", content: "A variable is a named container for a value. In Python, you create one by assignment — no declaration needed. Names are case-sensitive and may contain letters, digits, and underscores, but cannot start with a digit." },
      { kind: "code", language: "python", code: 'name = "Alice"\nage = 30\nheight = 1.65\nis_student = True\n\nprint(name, age, height, is_student)' },
      { kind: "heading", content: "Core data types" },
      { kind: "text", content: "Python has several built-in types. The most common ones you'll meet on day one: `int` (whole numbers), `float` (decimals), `str` (text), `bool` (True/False), `list` (ordered, mutable), `tuple` (ordered, immutable), `dict` (key-value pairs), and `set` (unique items)." },
      { kind: "code", language: "python", code: 'integer = 42\nfloating = 3.14\ntext = "Hello"\nboolean = True\nnumbers = [1, 2, 3]\npair = (10, 20)\nperson = {"name": "Alice", "age": 30}\nunique = {1, 2, 3}\n\nprint(type(integer))    # <class \'int\'>\nprint(type(text))       # <class \'str\'>' },
      { kind: "tip", content: "Use `type(x)` to inspect any value's type. This is invaluable when debugging." },
      { kind: "heading", content: "Type conversion" },
      { kind: "text", content: "You can convert between types with built-in functions: int(), float(), str(), bool()." },
      { kind: "code", language: "python", code: 'age_str = "25"\nage = int(age_str)\nprint(age + 5)  # 30\n\nprint(str(42))         # "42"\nprint(bool(0))         # False\nprint(bool("hello"))   # True' },
      { kind: "warning", content: "int('hello') will raise a ValueError. Always wrap user input in try/except when converting." },
    ],
    quiz: [
      { id: "q1", question: "Which of these is NOT a valid Python variable name?", options: ["my_var", "_private", "2nd_value", "userName"], correctIndex: 2, explanation: "Variable names cannot start with a digit." },
      { id: "q2", question: "What is the type of `3.14`?", options: ["int", "float", "str", "decimal"], correctIndex: 1 },
      { id: "q3", question: "How do you convert the string '42' to an integer?", options: ["int('42')", "integer('42')", "parse('42')", "to_int('42')"], correctIndex: 0 },
    ],
  },
  {
    id: "py-03",
    track: "python",
    order: 3,
    title: "Strings and String Methods",
    description: "Master text manipulation in Python.",
    difficulty: "beginner",
    estMinutes: 45,
    blocks: [
      { kind: "heading", content: "String basics" },
      { kind: "text", content: "Strings in Python are sequences of characters wrapped in single, double, or triple quotes. Triple-quoted strings can span multiple lines — perfect for docstrings and multi-line text." },
      { kind: "code", language: "python", code: 'single = \'hello\'\ndouble = "world"\nmulti = """This is\na multi-line\nstring."""' },
      { kind: "heading", content: "f-strings (formatted strings)" },
      { kind: "text", content: "f-strings (Python 3.6+) are the cleanest way to embed values into text. Prefix a string with `f` and use `{}` to inject expressions." },
      { kind: "code", language: "python", code: 'name = "Alice"\nage = 30\nmsg = f"My name is {name} and I\'m {age} years old."\nprint(msg)\n# My name is Alice and I\'m 30 years old.\n\n# Expressions work too\nprint(f"Next year: {age + 1}")' },
      { kind: "heading", content: "Common string methods" },
      { kind: "code", language: "python", code: 's = "  Hello, World!  "\n\nprint(s.strip())         # "Hello, World!"\nprint(s.lower())         # "  hello, world!  "\nprint(s.upper())         # "  HELLO, WORLD!  "\nprint(s.replace(",", "!"))  # "  Hello! World!  "\nprint("hello".capitalize())  # "Hello"\nprint("a,b,c".split(","))     # [\'a\', \'b\', \'c\']\nprint("-".join(["2024", "01", "15"]))  # "2024-01-15"' },
      { kind: "tip", content: "Strings are immutable — methods return new strings rather than modifying in place." },
      { kind: "heading", content: "Indexing and slicing" },
      { kind: "code", language: "python", code: 's = "Python"\nprint(s[0])      # P\nprint(s[-1])     # n\nprint(s[0:3])    # Pyt\nprint(s[::-1])   # nohtyP (reversed!)' },
      { kind: "warning", content: "Out-of-range slicing is safe (returns empty/shorter string), but out-of-range indexing raises IndexError." },
    ],
    quiz: [
      { id: "q1", question: "What does `\"hello\".upper()` return?", options: ["Hello", "HELLO", "hello", "Error"], correctIndex: 1 },
      { id: "q2", question: "How do you write an f-string in Python?", options: ["f'...'", "format'...'", "$'...'", "%'...'"], correctIndex: 0 },
      { id: "q3", question: "What is `s[-1]` for s='Python'?", options: ["P", "n", "Error", "Python"], correctIndex: 1, explanation: "Negative indices count from the end; -1 is the last character." },
    ],
  },
  {
    id: "py-04",
    track: "python",
    order: 4,
    title: "Numbers and Operators",
    description: "Arithmetic, comparison, and logical operators in Python.",
    difficulty: "beginner",
    estMinutes: 40,
    blocks: [
      { kind: "heading", content: "Arithmetic operators" },
      { kind: "code", language: "python", code: 'print(7 + 2)    # 9\nprint(7 - 2)    # 5\nprint(7 * 2)    # 14\nprint(7 / 2)    # 3.5 (always float)\nprint(7 // 2)   # 3 (floor division)\nprint(7 % 2)    # 1 (modulo)\nprint(7 ** 2)   # 49 (power)' },
      { kind: "tip", content: "Unlike many languages, `/` always returns a float. Use `//` for integer division." },
      { kind: "heading", content: "Comparison operators" },
      { kind: "code", language: "python", code: 'print(3 == 3)   # True\nprint(3 != 4)   # True\nprint(3 < 5)    # True\nprint(3 >= 3)   # True\n\n# Chained comparisons!\nprint(1 < 2 < 3)  # True' },
      { kind: "heading", content: "Logical operators" },
      { kind: "code", language: "python", code: 'print(True and False)  # False\nprint(True or False)   # True\nprint(not True)        # False\n\n# Truthy / falsy values\nprint(bool(0))         # False\nprint(bool(""))        # False\nprint(bool([]))        # False\nprint(bool("0"))       # True (non-empty string)' },
      { kind: "heading", content: "Math module" },
      { kind: "code", language: "python", code: 'import math\n\nprint(math.sqrt(16))    # 4.0\nprint(math.pi)          # 3.141592653589793\nprint(math.ceil(3.1))   # 4\nprint(math.floor(3.9))  # 3' },
    ],
    quiz: [
      { id: "q1", question: "What does `7 // 2` return?", options: ["3", "3.5", "4", "Error"], correctIndex: 0, explanation: "// is floor division — returns the largest integer <= the result." },
      { id: "q2", question: "What does `7 ** 2` return?", options: ["14", "49", "7", "72"], correctIndex: 1 },
      { id: "q3", question: "Which value is falsy in Python?", options: ["'0'", "0", "[0]", "'False'"], correctIndex: 1, explanation: "0, 0.0, '', [], {}, None, and False are all falsy. Non-empty strings (even '0' or 'False') are truthy." },
    ],
  },
  {
    id: "py-05",
    track: "python",
    order: 5,
    title: "Lists and Tuples",
    description: "Store ordered collections of data.",
    difficulty: "beginner",
    estMinutes: 50,
    blocks: [
      { kind: "heading", content: "Lists — mutable sequences" },
      { kind: "text", content: "A list is an ordered, mutable collection. Use it whenever you need to store multiple items in order and modify them later." },
      { kind: "code", language: "python", code: 'fruits = ["apple", "banana", "cherry"]\nprint(fruits[0])        # apple\nprint(len(fruits))      # 3\n\nfruits.append("date")\nprint(fruits)           # [\'apple\', \'banana\', \'cherry\', \'date\']\n\nfruits.insert(1, "avocado")\nprint(fruits)           # [\'apple\', \'avocado\', \'banana\', \'cherry\', \'date\']\n\nfruits.remove("banana")\nprint(fruits)           # [\'apple\', \'avocado\', \'cherry\', \'date\']\n\nlast = fruits.pop()\nprint(last, fruits)     # date [\'apple\', \'avocado\', \'cherry\']' },
      { kind: "heading", content: "Slicing" },
      { kind: "code", language: "python", code: 'nums = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]\nprint(nums[2:5])    # [2, 3, 4]\nprint(nums[:3])     # [0, 1, 2]\nprint(nums[7:])     # [7, 8, 9]\nprint(nums[::-1])   # [9, 8, 7, ..., 0]\nprint(nums[::2])    # [0, 2, 4, 6, 8]' },
      { kind: "heading", content: "Tuples — immutable sequences" },
      { kind: "text", content: "Tuples are like lists but immutable. Use them for fixed collections (coordinates, RGB colors, etc.) and as dictionary keys." },
      { kind: "code", language: "python", code: 'point = (3, 5)\nprint(point[0])     # 3\n\n# point[0] = 10  # TypeError: tuples are immutable\n\n# Tuple unpacking\nx, y = point\nprint(x, y)         # 3 5' },
      { kind: "tip", content: "Use tuples when the collection shouldn't change. They're also slightly faster than lists." },
      { kind: "heading", content: "List comprehensions" },
      { kind: "text", content: "List comprehensions are a concise, Pythonic way to build lists. They replace many simple for-loops." },
      { kind: "code", language: "python", code: '# Squares of 0-9\nsquares = [x**2 for x in range(10)]\nprint(squares)\n# [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]\n\n# Even squares only\neven_squares = [x**2 for x in range(10) if x % 2 == 0]\nprint(even_squares)\n# [0, 4, 16, 36, 64]' },
      { kind: "warning", content: "Don't overuse comprehensions — if the logic is complex, a regular for-loop is more readable." },
    ],
    quiz: [
      { id: "q1", question: "Which method adds an item to the end of a list?", options: ["add()", "append()", "push()", "insert()"], correctIndex: 1 },
      { id: "q2", question: "What is the key difference between a list and a tuple?", options: ["Speed", "Tuples are immutable", "Lists can't hold strings", "Tuples can't hold mixed types"], correctIndex: 1 },
      { id: "q3", question: "What does `[x*2 for x in range(3)]` return?", options: ["[0, 1, 2]", "[0, 2, 4]", "[2, 4, 6]", "[1, 2, 3]"], correctIndex: 1 },
    ],
  },
  {
    id: "py-06",
    track: "python",
    order: 6,
    title: "Dictionaries and Sets",
    description: "Key-value maps and unique collections.",
    difficulty: "beginner",
    estMinutes: 50,
    blocks: [
      { kind: "heading", content: "Dictionaries" },
      { kind: "text", content: "A dictionary (dict) is an unordered collection of key-value pairs. Keys must be unique and immutable (strings, numbers, tuples). Dicts are the workhorse of Python data structures — JSON, configs, and most APIs use them." },
      { kind: "code", language: "python", code: 'person = {\n    "name": "Alice",\n    "age": 30,\n    "skills": ["Python", "SQL"],\n}\n\nprint(person["name"])           # Alice\nprint(person.get("email", "N/A"))  # N/A (no KeyError)\n\nperson["email"] = "alice@example.com"\nperson["age"] = 31\n\ndel person["email"]\n\nfor key, value in person.items():\n    print(f"{key}: {value}")' },
      { kind: "tip", content: "Use .get() instead of [] when you're not sure a key exists — it returns None (or a default) instead of raising KeyError." },
      { kind: "heading", content: "Dict comprehensions" },
      { kind: "code", language: "python", code: 'squares = {x: x**2 for x in range(5)}\nprint(squares)\n# {0: 0, 1: 1, 2: 4, 3: 9, 4: 16}' },
      { kind: "heading", content: "Sets" },
      { kind: "text", content: "A set is an unordered collection of unique items. Perfect for deduplication and set operations (union, intersection)." },
      { kind: "code", language: "python", code: 'a = {1, 2, 3, 4}\nb = {3, 4, 5, 6}\n\nprint(a | b)   # union: {1, 2, 3, 4, 5, 6}\nprint(a & b)   # intersection: {3, 4}\nprint(a - b)   # difference: {1, 2}\n\n# Dedupe a list\nnums = [1, 2, 2, 3, 3, 3, 4]\nprint(list(set(nums)))  # [1, 2, 3, 4]' },
      { kind: "warning", content: "Sets are unordered — don't rely on iteration order. Use a list if order matters." },
    ],
    quiz: [
      { id: "q1", question: "What does `person.get('missing', 'default')` return if 'missing' is not a key?", options: ["None", "Raises KeyError", "'default'", "False"], correctIndex: 2 },
      { id: "q2", question: "Which structure only stores unique values?", options: ["list", "tuple", "dict", "set"], correctIndex: 3 },
      { id: "q3", question: "How do you delete a key from a dictionary?", options: ["dict.remove(key)", "del dict[key]", "dict.delete(key)", "dict.pop(key)"], correctIndex: 1, explanation: "Both del dict[key] and dict.pop(key) work — pop also returns the deleted value." },
    ],
  },
  {
    id: "py-07",
    track: "python",
    order: 7,
    title: "Conditionals (if/elif/else)",
    description: "Make decisions in your code.",
    difficulty: "beginner",
    estMinutes: 35,
    blocks: [
      { kind: "heading", content: "if statements" },
      { kind: "text", content: "Conditionals let your code branch. Python uses indentation (4 spaces by convention) to define blocks — no curly braces." },
      { kind: "code", language: "python", code: 'age = 20\n\nif age < 13:\n    print("Child")\nelif age < 20:\n    print("Teenager")\nelif age < 65:\n    print("Adult")\nelse:\n    print("Senior")' },
      { kind: "tip", content: "Python doesn't have a switch statement (until 3.10's `match` — see deep dive). For multiple options, use elif chains or dict lookups." },
      { kind: "heading", content: "Truthiness" },
      { kind: "text", content: "Python evaluates many values as True or False in conditions. Falsy values: 0, 0.0, '', [], {}, set(), None, False. Everything else is truthy." },
      { kind: "code", language: "python", code: 'items = []\nif items:\n    print("Has items")\nelse:\n    print("Empty")  # <- prints\n\nname = ""\nif not name:\n    print("Please enter your name")' },
      { kind: "heading", content: "Ternary expressions" },
      { kind: "code", language: "python", code: 'age = 17\nstatus = "minor" if age < 18 else "adult"\nprint(status)  # minor' },
      { kind: "heading", content: "Match statement (Python 3.10+)" },
      { kind: "code", language: "python", code: 'command = "start"\n\nmatch command:\n    case "start":\n        print("Starting...")\n    case "stop":\n        print("Stopping...")\n    case "pause" | "resume":\n        print("State changed")\n    case _:\n        print("Unknown command")' },
    ],
    quiz: [
      { id: "q1", question: "How does Python define code blocks?", options: ["Curly braces {}", "Indentation", "begin/end keywords", "Parentheses ()"], correctIndex: 1 },
      { id: "q2", question: "Which value is truthy?", options: ["0", "''", "[]", "'False'"], correctIndex: 3, explanation: "Non-empty strings are truthy, even if the string is 'False'." },
      { id: "q3", question: "What's the syntax for a ternary expression?", options: ["if a then b else c", "a ? b : c", "b if a else c", "case a: b else c"], correctIndex: 2 },
    ],
    deepDiveResources: [
      { label: "PEP 634 — Structural Pattern Matching", url: "https://peps.python.org/pep-0634/", kind: "doc" },
    ],
  },
  {
    id: "py-08",
    track: "python",
    order: 8,
    title: "Loops (for and while)",
    description: "Repeat work without copy-pasting code.",
    difficulty: "beginner",
    estMinutes: 40,
    blocks: [
      { kind: "heading", content: "for loops" },
      { kind: "text", content: "Python's for loop iterates over any iterable (list, string, dict, range, file, etc.). It's cleaner than the C-style for loop you'll find in many languages." },
      { kind: "code", language: "python", code: 'fruits = ["apple", "banana", "cherry"]\nfor fruit in fruits:\n    print(fruit)\n\n# With index (enumerate)\nfor i, fruit in enumerate(fruits):\n    print(f"{i}: {fruit}")\n\n# range()\nfor i in range(5):\n    print(i)  # 0 1 2 3 4\n\nfor i in range(2, 8):\n    print(i)  # 2 3 4 5 6 7' },
      { kind: "heading", content: "while loops" },
      { kind: "code", language: "python", code: 'count = 0\nwhile count < 3:\n    print(f"Counting: {count}")\n    count += 1' },
      { kind: "heading", content: "break and continue" },
      { kind: "code", language: "python", code: '# break exits the loop entirely\nfor n in range(10):\n    if n == 5:\n        break\n    print(n)  # 0 1 2 3 4\n\n# continue skips to next iteration\nfor n in range(5):\n    if n % 2 == 0:\n        continue\n    print(n)  # 1 3' },
      { kind: "heading", content: "Looping dicts" },
      { kind: "code", language: "python", code: 'person = {"name": "Alice", "age": 30}\n\nfor key in person:\n    print(key)              # name, age\n\nfor key, value in person.items():\n    print(f"{key} = {value}")' },
      { kind: "warning", content: "Avoid modifying a list while iterating over it — use a list comprehension or iterate over a copy instead." },
      { kind: "tip", content: "In Python, we rarely write `for i in range(len(items))` — iterate over items directly, or use enumerate() when you need the index." },
    ],
    quiz: [
      { id: "q1", question: "What does `range(3)` produce?", options: ["[1, 2, 3]", "[0, 1, 2]", "[0, 1, 2, 3]", "3"], correctIndex: 1 },
      { id: "q2", question: "Which function gives you index + value pairs while looping?", options: ["zip()", "enumerate()", "pairs()", "range()"], correctIndex: 1 },
      { id: "q3", question: "What does `break` do?", options: ["Skip an iteration", "Exit the loop entirely", "Pause execution", "Restart the loop"], correctIndex: 1 },
    ],
  },
  {
    id: "py-09",
    track: "python",
    order: 9,
    title: "Functions",
    description: "Package logic into reusable units.",
    difficulty: "beginner",
    estMinutes: 50,
    blocks: [
      { kind: "heading", content: "Defining functions" },
      { kind: "text", content: "Functions let you package logic, give it a name, and reuse it. Define one with `def`, then call it by name with parentheses." },
      { kind: "code", language: "python", code: 'def greet(name):\n    """Return a friendly greeting."""\n    return f"Hello, {name}!"\n\nprint(greet("Alice"))   # Hello, Alice!\nprint(greet("Bob"))     # Hello, Bob!' },
      { kind: "tip", content: "Triple-quoted strings right after the def line are docstrings — Python's built-in help system uses them. Always write one for non-trivial functions." },
      { kind: "heading", content: "Parameters and arguments" },
      { kind: "code", language: "python", code: '# Default values\ndef greet(name, greeting="Hello"):\n    return f"{greeting}, {name}!"\n\nprint(greet("Alice"))              # Hello, Alice!\nprint(greet("Bob", "Hi"))          # Hi, Bob!\nprint(greet(greeting="Hey", name="Carol"))  # Hey, Carol!' },
      { kind: "heading", content: "*args and **kwargs" },
      { kind: "code", language: "python", code: 'def sum_all(*nums):\n    return sum(nums)\n\nprint(sum_all(1, 2, 3))       # 6\nprint(sum_all(10, 20, 30, 40))  # 100\n\ndef show_info(**kwargs):\n    for k, v in kwargs.items():\n        print(f"{k}: {v}")\n\nshow_info(name="Alice", age=30, role="Engineer")' },
      { kind: "heading", content: "Return values" },
      { kind: "code", language: "python", code: 'def is_even(n):\n    return n % 2 == 0\n\n# Multiple return values (tuple unpacking)\ndef min_max(numbers):\n    return min(numbers), max(numbers)\n\nlow, high = min_max([3, 1, 4, 1, 5, 9])\nprint(low, high)  # 1 9' },
      { kind: "heading", content: "Lambdas" },
      { kind: "code", language: "python", code: '# Short, anonymous functions\nsquare = lambda x: x ** 2\nprint(square(5))  # 25\n\n# Often used with map/filter/sort\nnums = [5, 2, 8, 1, 9]\nprint(sorted(nums, key=lambda x: -x))  # [9, 8, 5, 2, 1]' },
      { kind: "warning", content: "Don't use mutable default arguments like `def f(items=[])` — they're shared across calls! Use `def f(items=None): if items is None: items = []` instead." },
    ],
    quiz: [
      { id: "q1", question: "How do you define a function in Python?", options: ["function f():", "def f():", "func f():", "define f():"], correctIndex: 1 },
      { id: "q2", question: "What does `*args` allow?", options: ["Named arguments only", "Variable positional arguments", "Default values", "Keyword arguments only"], correctIndex: 1 },
      { id: "q3", question: "Why is `def f(items=[])` dangerous?", options: ["Lists can't be defaults", "The list is shared across calls", "It's a syntax error", "It's slow"], correctIndex: 1, explanation: "Default arguments are evaluated once at function definition, so all calls share the same list." },
    ],
  },
  {
    id: "py-10",
    track: "python",
    order: 10,
    title: "Object-Oriented Programming",
    description: "Classes, objects, inheritance, and polymorphism.",
    difficulty: "intermediate",
    estMinutes: 60,
    blocks: [
      { kind: "heading", content: "Classes and objects" },
      { kind: "text", content: "A class is a blueprint. An object is an instance of a class. Classes group related data (attributes) and behavior (methods) into a single unit." },
      { kind: "code", language: "python", code: 'class Dog:\n    species = "Canis familiaris"  # class attribute\n\n    def __init__(self, name, age):\n        self.name = name  # instance attribute\n        self.age = age\n\n    def bark(self):\n        return f"{self.name} says Woof!"\n\nbuddy = Dog("Buddy", 3)\nprint(buddy.name)        # Buddy\nprint(buddy.bark())      # Buddy says Woof!\nprint(buddy.species)     # Canis familiaris' },
      { kind: "heading", content: "Inheritance" },
      { kind: "code", language: "python", code: 'class Animal:\n    def __init__(self, name):\n        self.name = name\n\n    def speak(self):\n        return f"{self.name} makes a sound"\n\nclass Cat(Animal):\n    def speak(self):  # override\n        return f"{self.name} says Meow"\n\nclass Cow(Animal):\n    def speak(self):\n        return f"{self.name} says Moo"\n\nanimals = [Cat("Whiskers"), Cow("Bessie")]\nfor a in animals:\n    print(a.speak())\n# Whiskers says Meow\n# Bessie says Moo' },
      { kind: "tip", content: "Polymorphism — different objects can be treated uniformly if they share an interface. The loop above doesn't care whether each animal is a Cat or Cow; it just calls .speak()." },
      { kind: "heading", content: "Special methods (dunders)" },
      { kind: "code", language: "python", code: 'class Point:\n    def __init__(self, x, y):\n        self.x = x\n        self.y = y\n\n    def __repr__(self):\n        return f"Point({self.x}, {self.y})"\n\n    def __eq__(self, other):\n        return self.x == other.x and self.y == other.y\n\n    def __add__(self, other):\n        return Point(self.x + other.x, self.y + other.y)\n\np1 = Point(1, 2)\np2 = Point(3, 4)\nprint(p1)         # Point(1, 2)\nprint(p1 + p2)    # Point(4, 6)' },
      { kind: "heading", content: "@property and @classmethod" },
      { kind: "code", language: "python", code: 'class Temperature:\n    def __init__(self, celsius):\n        self._celsius = celsius\n\n    @property\n    def fahrenheit(self):\n        return self._celsius * 9/5 + 32\n\n    @classmethod\n    def from_fahrenheit(cls, f):\n        return cls((f - 32) * 5/9)\n\nt = Temperature(25)\nprint(t.fahrenheit)  # 77.0\n\nt2 = Temperature.from_fahrenheit(98.6)\nprint(t2._celsius)   # 37.0' },
      { kind: "warning", content: "Don't over-engineer with classes. If a class has only data and no behavior, a dict or dataclass is simpler." },
    ],
    quiz: [
      { id: "q1", question: "What is `__init__`?", options: ["A class attribute", "The constructor method", "A destructor", "A static method"], correctIndex: 1 },
      { id: "q2", question: "What does `self` refer to in a method?", options: ["The class itself", "The current instance", "The parent class", "A global variable"], correctIndex: 1 },
      { id: "q3", question: "What is polymorphism?", options: ["Multiple constructors", "Different objects responding to the same interface", "Multiple inheritance", "Method overloading"], correctIndex: 1 },
    ],
    deepDiveResources: [
      { label: "Python Data Classes (official docs)", url: "https://docs.python.org/3/library/dataclasses.html", kind: "doc" },
    ],
  },
  {
    id: "py-11",
    track: "python",
    order: 11,
    title: "Error Handling (try/except)",
    description: "Handle errors gracefully.",
    difficulty: "intermediate",
    estMinutes: 40,
    blocks: [
      { kind: "heading", content: "try/except" },
      { kind: "text", content: "Errors (exceptions) halt your program. Use try/except to catch them and respond gracefully instead of crashing." },
      { kind: "code", language: "python", code: 'try:\n    num = int(input("Enter a number: "))\n    print(f"You entered {num}")\nexcept ValueError:\n    print("That\'s not a valid number!")\nfinally:\n    print("Thanks for playing")' },
      { kind: "heading", content: "Catching specific exceptions" },
      { kind: "code", language: "python", code: 'try:\n    with open("data.txt") as f:\n        content = f.read()\n        value = int(content)\nexcept FileNotFoundError:\n    print("File not found")\nexcept ValueError:\n    print("File content is not a number")\nexcept Exception as e:\n    print(f"Unexpected error: {e}")' },
      { kind: "tip", content: "Always catch specific exceptions, not bare `except:`. Bare except catches everything including KeyboardInterrupt — usually a bug." },
      { kind: "heading", content: "Raising exceptions" },
      { kind: "code", language: "python", code: 'def divide(a, b):\n    if b == 0:\n        raise ValueError("Cannot divide by zero")\n    return a / b\n\ntry:\n    divide(10, 0)\nexcept ValueError as e:\n    print(e)  # Cannot divide by zero' },
      { kind: "heading", content: "Custom exceptions" },
      { kind: "code", language: "python", code: 'class InvalidScoreError(Exception):\n    """Raised when a test score is out of range."""\n    pass\n\ndef grade(score):\n    if not 0 <= score <= 100:\n        raise InvalidScoreError(f"Score {score} out of range")\n    if score >= 90: return "A"\n    if score >= 80: return "B"\n    return "C"' },
      { kind: "warning", content: "Don't use exceptions for normal control flow — they're slow and make code harder to read." },
    ],
    quiz: [
      { id: "q1", question: "Which block runs whether or not an exception occurred?", options: ["except", "finally", "else", "catch"], correctIndex: 1 },
      { id: "q2", question: "How do you raise an exception?", options: ["throw ValueError()", "raise ValueError()", "error ValueError()", "panic ValueError()"], correctIndex: 1 },
      { id: "q3", question: "Why is bare `except:` discouraged?", options: ["It's a syntax error", "It catches everything including KeyboardInterrupt", "It's slow", "It only catches ValueError"], correctIndex: 1 },
    ],
  },
  {
    id: "py-12",
    track: "python",
    order: 12,
    title: "File I/O",
    description: "Read and write files.",
    difficulty: "intermediate",
    estMinutes: 40,
    blocks: [
      { kind: "heading", content: "Reading files" },
      { kind: "text", content: "Use `with open(...)` to read files — it automatically closes the file even if an error occurs." },
      { kind: "code", language: "python", code: '# Read entire file as string\nwith open("README.md", "r") as f:\n    content = f.read()\nprint(content[:100])\n\n# Read line by line (memory-efficient for big files)\nwith open("data.log") as f:\n    for line in f:\n        print(line.strip())\n\n# Read all lines into a list\nwith open("items.txt") as f:\n    lines = f.readlines()' },
      { kind: "heading", content: "Writing files" },
      { kind: "code", language: "python", code: '# "w" overwrites, "a" appends, "x" creates (fails if exists)\nwith open("output.txt", "w") as f:\n    f.write("Hello\\n")\n    f.write("World\\n")\n\n# Multiple lines at once\nlines = ["apple\\n", "banana\\n", "cherry\\n"]\nwith open("fruits.txt", "w") as f:\n    f.writelines(lines)' },
      { kind: "warning", content: "Opening with 'w' truncates the file immediately. Use 'a' to append, or 'x' to fail if the file exists." },
      { kind: "heading", content: "JSON files" },
      { kind: "code", language: "python", code: 'import json\n\ndata = {"name": "Alice", "scores": [90, 85, 92]}\n\n# Write JSON\nwith open("data.json", "w") as f:\n    json.dump(data, f, indent=2)\n\n# Read JSON\nwith open("data.json") as f:\n    loaded = json.load(f)\nprint(loaded["name"])  # Alice' },
      { kind: "heading", content: "CSV files" },
      { kind: "code", language: "python", code: 'import csv\n\n# Write\nwith open("people.csv", "w", newline="") as f:\n    writer = csv.DictWriter(f, fieldnames=["name", "age"])\n    writer.writeheader()\n    writer.writerow({"name": "Alice", "age": 30})\n\n# Read\nwith open("people.csv") as f:\n    for row in csv.DictReader(f):\n        print(row["name"], row["age"])' },
      { kind: "tip", content: "Use pathlib.Path for path manipulation — it's cleaner than os.path and works across platforms." },
    ],
    quiz: [
      { id: "q1", question: "Why use `with open(...)` instead of plain `open()`?", options: ["It's faster", "It auto-closes the file", "It's required for writing", "It reads in parallel"], correctIndex: 1 },
      { id: "q2", question: "Which mode appends to a file?", options: ["'r'", "'w'", "'a'", "'x'"], correctIndex: 2 },
      { id: "q3", question: "Which module handles JSON?", options: ["csv", "json", "yaml", "fileio"], correctIndex: 1 },
    ],
  },
  {
    id: "py-13",
    track: "python",
    order: 13,
    title: "Modules and Packages",
    description: "Organize code into reusable modules.",
    difficulty: "intermediate",
    estMinutes: 35,
    blocks: [
      { kind: "heading", content: "What is a module?" },
      { kind: "text", content: "A module is just a .py file. You can import functions, classes, and variables from any other .py file using `import`." },
      { kind: "code", language: "python", code: '# math_utils.py\ndef add(a, b):\n    return a + b\n\nPI = 3.14159\n\n# main.py\nimport math_utils\nprint(math_utils.add(2, 3))  # 5\nprint(math_utils.PI)        # 3.14159\n\n# Or import specific names\nfrom math_utils import add, PI\nprint(add(4, 5))\nprint(PI)\n\n# Rename on import\nimport math_utils as mu\nprint(mu.add(1, 1))' },
      { kind: "heading", content: "Standard library highlights" },
      { kind: "code", language: "python", code: 'import os           # OS interaction\nimport sys          # System-specific\nimport datetime     # Dates and times\nimport random       # Random numbers\nimport collections  # Specialized containers\nimport itertools    # Iterator tools\nimport math         # Math functions\nimport re           # Regular expressions\nimport json         # JSON\nimport pathlib      # Path manipulation\n\n# Examples\nprint(os.getcwd())                          # current directory\nprint(datetime.datetime.now())              # current time\nprint(random.randint(1, 100))               # random int 1-100\nprint(collections.Counter("aabbbcc"))       # Counter({\'b\': 3, \'a\': 2, \'c\': 2})' },
      { kind: "heading", content: "Packages" },
      { kind: "text", content: "A package is a directory of modules with an `__init__.py` file. Packages let you organize larger codebases hierarchically." },
      { kind: "code", language: "bash", code: "myproject/\n├── __init__.py\n├── models/\n│   ├── __init__.py\n│   ├── user.py\n│   └── product.py\n└── utils/\n    ├── __init__.py\n    └── formatting.py" },
      { kind: "code", language: "python", code: 'from myproject.models.user import User\nfrom myproject.utils import formatting' },
      { kind: "heading", content: "Installing third-party packages" },
      { kind: "code", language: "bash", code: "pip install requests pandas numpy\npip install -r requirements.txt" },
      { kind: "tip", content: "Always pin your dependencies in requirements.txt so others (and future-you) get the same versions." },
    ],
    quiz: [
      { id: "q1", question: "How do you import a specific function from a module?", options: ["import add from math", "from math import add", "include math.add", "use math.add"], correctIndex: 1 },
      { id: "q2", question: "What makes a directory a package in Python?", options: ["A README.md", "An __init__.py file", "A .py extension", "A setup.py"], correctIndex: 1 },
      { id: "q3", question: "Which tool installs third-party packages?", options: ["npm", "pip", "apt", "brew"], correctIndex: 1 },
    ],
  },
  {
    id: "py-14",
    track: "python",
    order: 14,
    title: "Working with APIs (requests)",
    description: "Call REST APIs and handle JSON responses.",
    difficulty: "intermediate",
    estMinutes: 45,
    blocks: [
      { kind: "heading", content: "Installing requests" },
      { kind: "code", language: "bash", code: "pip install requests" },
      { kind: "heading", content: "GET requests" },
      { kind: "code", language: "python", code: 'import requests\n\nresponse = requests.get("https://api.github.com/users/torvalds")\nprint(response.status_code)  # 200\nprint(response.headers["content-type"])  # application/json\n\ndata = response.json()  # parses JSON automatically\nprint(data["login"])      # torvalds\nprint(data["name"])       # Linus Torvalds\nprint(data["followers"])  # a big number' },
      { kind: "heading", content: "Query parameters" },
      { kind: "code", language: "python", code: 'response = requests.get(\n    "https://api.github.com/search/repositories",\n    params={"q": "python web framework", "sort": "stars"},\n)\ndata = response.json()\nfor repo in data["items"][:5]:\n    print(f"{repo[\'full_name\']} - {repo[\'stargazers_count\']} stars")' },
      { kind: "heading", content: "POST requests" },
      { kind: "code", language: "python", code: '# JSON body\nresponse = requests.post(\n    "https://httpbin.org/post",\n    json={"username": "alice", "score": 95},\n)\nprint(response.json())\n\n# Form data\nresponse = requests.post(\n    "https://httpbin.org/post",\n    data={"username": "alice", "password": "secret"},\n)' },
      { kind: "heading", content: "Authentication" },
      { kind: "code", language: "python", code: '# API key in header\nheaders = {"Authorization": "Bearer YOUR_TOKEN"}\nresponse = requests.get("https://api.example.com/me", headers=headers)\n\n# Basic auth\nresponse = requests.get(\n    "https://api.example.com/protected",\n    auth=("username", "password"),\n)' },
      { kind: "heading", content: "Handling errors" },
      { kind: "code", language: "python", code: 'try:\n    response = requests.get("https://api.example.com/data", timeout=10)\n    response.raise_for_status()  # raises HTTPError for 4xx/5xx\n    data = response.json()\nexcept requests.Timeout:\n    print("Request timed out")\nexcept requests.HTTPError as e:\n    print(f"HTTP error: {e}")\nexcept requests.RequestException as e:\n    print(f"Request failed: {e}")' },
      { kind: "warning", content: "Always pass a timeout to requests.get/post — without it, a slow server can hang your program forever." },
    ],
    quiz: [
      { id: "q1", question: "Which method parses a JSON response in the requests library?", options: [".text", ".json()", ".parse()", ".content"], correctIndex: 1 },
      { id: "q2", question: "How do you pass query parameters?", options: ["?q=python in the URL", "params={'q': 'python'}", "query={'q': 'python'}", "args={'q': 'python'}"], correctIndex: 1 },
      { id: "q3", question: "Which method raises an exception for 4xx/5xx responses?", options: [".check_status()", ".raise_for_status()", ".ok()", ".verify()"], correctIndex: 1 },
    ],
  },
  {
    id: "py-15",
    track: "python",
    order: 15,
    title: "Testing with pytest",
    description: "Write tests that catch bugs before users do.",
    difficulty: "intermediate",
    estMinutes: 50,
    blocks: [
      { kind: "heading", content: "Why test?" },
      { kind: "text", content: "Tests verify your code does what you think it does — and keeps doing it as you change it. Untested code breaks silently; well-tested code breaks loudly, which is what you want." },
      { kind: "heading", content: "Installing pytest" },
      { kind: "code", language: "bash", code: "pip install pytest" },
      { kind: "heading", content: "Your first test" },
      { kind: "code", language: "python", code: '# math_utils.py\ndef add(a, b):\n    return a + b\n\n# test_math_utils.py\nfrom math_utils import add\n\ndef test_add():\n    assert add(2, 3) == 5\n    assert add(-1, 1) == 0\n    assert add(0, 0) == 0' },
      { kind: "code", language: "bash", code: "$ pytest\n============================= test session starts =============================\ncollected 1 item\n\ntest_math_utils.py .                                                  [100%]\n\n============================== 1 passed in 0.01s ==============================" },
      { kind: "heading", content: "Multiple tests with parametrize" },
      { kind: "code", language: "python", code: 'import pytest\nfrom math_utils import add\n\n@pytest.mark.parametrize("a, b, expected", [\n    (1, 2, 3),\n    (-1, 1, 0),\n    (100, 200, 300),\n    (0.1, 0.2, 0.3),\n])\ndef test_add(a, b, expected):\n    assert add(a, b) == expected' },
      { kind: "heading", content: "Fixtures — setup/teardown" },
      { kind: "code", language: "python", code: 'import pytest\n\n@pytest.fixture\ndef sample_list():\n    return [3, 1, 4, 1, 5, 9, 2, 6]\n\ndef test_sorted(sample_list):\n    result = sorted(sample_list)\n    assert result == [1, 1, 2, 3, 4, 5, 6, 9]\n\ndef test_min_max(sample_list):\n    assert min(sample_list) == 1\n    assert max(sample_list) == 9' },
      { kind: "heading", content: "Testing exceptions" },
      { kind: "code", language: "python", code: 'import pytest\n\ndef divide(a, b):\n    if b == 0:\n        raise ValueError("Cannot divide by zero")\n    return a / b\n\ndef test_divide_by_zero():\n    with pytest.raises(ValueError, match="Cannot divide by zero"):\n        divide(10, 0)' },
      { kind: "tip", content: "Run tests with `pytest -v` for verbose output, or `pytest -k 'add'` to run only tests matching a pattern." },
      { kind: "warning", content: "Don't test the framework — only test your own code. e.g. don't test that Python's `sorted()` works; test that you call it correctly." },
    ],
    quiz: [
      { id: "q1", question: "What does `assert x == 5` do when x is 4?", options: ["Returns False", "Raises AssertionError", "Prints a warning", "Exits the program"], correctIndex: 1 },
      { id: "q2", question: "Which decorator runs the same test with multiple inputs?", options: ["@pytest.fixture", "@pytest.mark.parametrize", "@pytest.data", "@pytest.repeat"], correctIndex: 1 },
      { id: "q3", question: "How do you test that code raises an exception?", options: ["try/except", "pytest.raises(Exception)", "assert_raises()", "@pytest.catch"], correctIndex: 1 },
    ],
  },
];

export const JAVASCRIPT_LESSONS: Lesson[] = [
  {
    id: "js-01",
    track: "javascript",
    order: 1,
    title: "Getting Started with JavaScript",
    description: "Run JavaScript in the browser and Node.js, write your first program.",
    difficulty: "beginner",
    estMinutes: 30,
    blocks: [
      { kind: "heading", content: "What is JavaScript?" },
      { kind: "text", content: "JavaScript is the programming language of the web. Created by Brendan Eich in 1995 in just 10 days, it now runs in every browser and on servers (via Node.js). It powers interactive websites, mobile apps (React Native), desktop apps (Electron), and even backend services. Modern JavaScript (ES2020+) is a powerful, expressive language." },
      { kind: "heading", content: "Where JavaScript runs" },
      { kind: "text", content: "JavaScript runs in two main places: (1) In web browsers — every browser has a built-in JS engine (V8 in Chrome, SpiderMonkey in Firefox, JavaScriptCore in Safari). (2) On servers — Node.js uses V8 to run JS outside the browser. You can also run JS in the Launchpad Playground tab!" },
      { kind: "heading", content: "Your first program" },
      { kind: "code", language: "javascript", code: 'console.log("Hello, World!");' },
      { kind: "tip", content: "Open your browser's DevTools (F12 or Cmd+Opt+I), switch to the Console tab, and type JavaScript directly. It's the fastest way to experiment." },
      { kind: "heading", content: "Adding JS to a webpage" },
      { kind: "code", language: "html", code: '<!-- Inline -->\n<button onclick="alert(\'Hi\')">Click me</button>\n\n<!-- Script tag -->\n<script>\n  console.log("Page loaded");\n</script>\n\n<!-- External file -->\n<script src="app.js"></script>' },
      { kind: "heading", content: "Comments" },
      { kind: "code", language: "javascript", code: '// Single-line comment\n\n/*\n  Multi-line\n  comment\n*/\n\n/** JSDoc comment — used for documentation */' },
      { kind: "warning", content: "JavaScript is case-sensitive. `console.log` works, `Console.log` throws an error." },
    ],
    quiz: [
      { id: "q1", question: "Who created JavaScript?", options: ["Guido van Rossum", "Brendan Eich", "Linus Torvalds", "James Gosling"], correctIndex: 1 },
      { id: "q2", question: "Where can JavaScript run?", options: ["Only in browsers", "Only on servers", "In browsers and on servers (Node.js)", "Only on mobile"], correctIndex: 2 },
      { id: "q3", question: "Which function prints to the console?", options: ["print()", "console.log()", "echo()", "printf()"], correctIndex: 1 },
    ],
  },
  {
    id: "js-02",
    track: "javascript",
    order: 2,
    title: "Variables and Data Types",
    description: "let, const, var and JavaScript's types.",
    difficulty: "beginner",
    estMinutes: 45,
    blocks: [
      { kind: "heading", content: "Declaring variables" },
      { kind: "text", content: "JavaScript has three ways to declare variables. Modern code uses `let` for variables that change and `const` for variables that don't. `var` is the old way — avoid it." },
      { kind: "code", language: "javascript", code: 'let age = 30;        // can be reassigned\nage = 31;\n\nconst name = "Alice"; // cannot be reassigned\n// name = "Bob";      // TypeError\n\nconst person = { name: "Alice" };\nperson.name = "Bob";  // OK — we\'re mutating, not reassigning\n\nvar old = "avoid";    // function-scoped, hoisted — avoid' },
      { kind: "tip", content: "Default to `const`. Only use `let` when you need to reassign. This makes your code easier to reason about." },
      { kind: "heading", content: "Primitive types" },
      { kind: "text", content: "JavaScript has 7 primitive types: `string`, `number`, `boolean`, `null`, `undefined`, `symbol`, `bigint`. Everything else is an object (including arrays and functions)." },
      { kind: "code", language: "javascript", code: 'const text = "hello";           // string\nconst count = 42;              // number\nconst price = 9.99;            // number (no separate float type)\nconst isActive = true;         // boolean\nconst data = null;             // null (intentional absence)\nlet notSet;                    // undefined (uninitialized)\n\nconsole.log(typeof text);      // "string"\nconsole.log(typeof count);     // "number"\nconsole.log(typeof isActive);  // "boolean"\nconsole.log(typeof undefined); // "undefined"\nconsole.log(typeof null);      // "object" (historical bug!)' },
      { kind: "heading", content: "Type coercion" },
      { kind: "text", content: "JavaScript is loosely typed — it converts between types automatically, sometimes in surprising ways. Always use === to avoid coercion bugs." },
      { kind: "code", language: "javascript", code: 'console.log(1 + "2");      // "12" (string!)\nconsole.log("5" - 2);      // 3 (number!)\nconsole.log(0 == false);   // true (loose equality)\nconsole.log(0 === false);  // false (strict equality)\nconsole.log(null == undefined);   // true\nconsole.log(null === undefined);  // false' },
      { kind: "warning", content: "Always use === and !== instead of == and !=. The strict versions don't do type coercion, which prevents entire categories of bugs." },
      { kind: "heading", content: "Template literals" },
      { kind: "code", language: "javascript", code: 'const name = "Alice";\nconst age = 30;\n\nconst msg = `My name is ${name} and I\'m ${age + 1} next year.`;\nconsole.log(msg);\n\n// Multi-line\nconst html = `\n  <div>\n    <h1>Hello</h1>\n  </div>\n`;' },
    ],
    quiz: [
      { id: "q1", question: "Which keyword declares a variable that can't be reassigned?", options: ["let", "const", "var", "static"], correctIndex: 1 },
      { id: "q2", question: "What does `1 + '2'` return?", options: ["3", "'12'", "13", "Error"], correctIndex: 1, explanation: "When + is used with a string, JS converts the other operand to a string and concatenates." },
      { id: "q3", question: "What does `typeof null` return?", options: ["'null'", "'object'", "'undefined'", "Error"], correctIndex: 1, explanation: "This is a famous historical bug in JavaScript, kept for backward compatibility." },
    ],
  },
  {
    id: "js-03",
    track: "javascript",
    order: 3,
    title: "Strings and Template Literals",
    description: "Work with text in JavaScript.",
    difficulty: "beginner",
    estMinutes: 40,
    blocks: [
      { kind: "heading", content: "String basics" },
      { kind: "code", language: "javascript", code: 'const single = \'hello\';\nconst double = "world";\nconst backtick = `hello world`;\n\n// Strings are immutable\nlet s = "hello";\n// s[0] = "H";  // doesn\'t work\ns = "Hello";      // reassign instead\n\nconsole.log(s.length);        // 5\nconsole.log(s[0]);            // H\nconsole.log(s.charAt(0));     // H\nconsole.log(s.indexOf("l"));  // 2\nconsole.log(s.includes("ell")); // true' },
      { kind: "heading", content: "Useful string methods" },
      { kind: "code", language: "javascript", code: 'const s = "  Hello, World!  ";\n\nconsole.log(s.trim());           // "Hello, World!"\nconsole.log(s.toLowerCase());    // "  hello, world!  "\nconsole.log(s.toUpperCase());    // "  HELLO, WORLD!  "\nconsole.log(s.replace(",", "!")); // "  Hello! World!  "\nconsole.log(s.split(","));        // ["  Hello", " World!  "]\nconsole.log(s.slice(2, 7));       // "Hello"\nconsole.log(s.startsWith("  H")); // true\nconsole.log(s.repeat(2));         // doubled string' },
      { kind: "heading", content: "Template literals" },
      { kind: "text", content: "Template literals (backticks) support interpolation, multi-line strings, and even expressions." },
      { kind: "code", language: "javascript", code: 'const name = "Alice";\nconst items = ["apple", "banana"];\n\nconsole.log(`Hello, ${name}!`);\nconsole.log(`You have ${items.length} items`);\nconsole.log(`First item: ${items[0].toUpperCase()}`);\n\nconst multi = `\n  Line 1\n  Line 2\n  Line 3\n`;' },
      { kind: "heading", content: "Tagged templates" },
      { kind: "code", language: "javascript", code: 'function html(strings, ...values) {\n  return strings.reduce((acc, str, i) => \n    acc + str + (values[i] ?? ""), "");\n}\n\nconst user = "Alice";\nconst safe = html`<p>Hello, ${user}</p>`;\nconsole.log(safe);' },
      { kind: "tip", content: "Always use template literals over string concatenation with +. They're more readable and less error-prone." },
    ],
    quiz: [
      { id: "q1", question: "Are strings mutable in JavaScript?", options: ["Yes", "No", "Only with let", "Only inside functions"], correctIndex: 1 },
      { id: "q2", question: "Which character starts a template literal?", options: ["'", "\"", "`", "/"], correctIndex: 2 },
      { id: "q3", question: "What does `'a,b,c'.split(',')` return?", options: ["'abc'", "['a', 'b', 'c']", "['abc']", "Error"], correctIndex: 1 },
    ],
  },
  {
    id: "js-04",
    track: "javascript",
    order: 4,
    title: "Numbers and Operators",
    description: "Arithmetic, comparison, and logical operators.",
    difficulty: "beginner",
    estMinutes: 40,
    blocks: [
      { kind: "heading", content: "Arithmetic" },
      { kind: "code", language: "javascript", code: 'console.log(7 + 2);   // 9\nconsole.log(7 - 2);   // 5\nconsole.log(7 * 2);   // 14\nconsole.log(7 / 2);   // 3.5\nconsole.log(7 % 2);   // 1 (modulo)\nconsole.log(7 ** 2);  // 49 (exponent)\n\n// Increment / decrement\nlet n = 5;\nconsole.log(n++);  // 5 (postfix returns old value)\nconsole.log(n);     // 6\nconsole.log(++n);   // 7 (prefix returns new value)' },
      { kind: "heading", content: "Number quirks" },
      { kind: "text", content: "JavaScript numbers are all 64-bit floats — there's no separate int type. This leads to some famous quirks:" },
      { kind: "code", language: "javascript", code: 'console.log(0.1 + 0.2);          // 0.30000000000000004\nconsole.log(0.1 + 0.2 === 0.3);  // false!\nconsole.log(9007199254740992 + 1); // 9007199254740992 (loses precision)\n\n// Use Number.EPSILON for float comparisons\nfunction approxEqual(a, b) {\n  return Math.abs(a - b) < Number.EPSILON;\n}\nconsole.log(approxEqual(0.1 + 0.2, 0.3));  // true' },
      { kind: "warning", content: "Never use == to compare floats. Use a small epsilon as shown above, or use a library like decimal.js for money." },
      { kind: "heading", content: "Comparison operators" },
      { kind: "code", language: "javascript", code: 'console.log(3 > 2);          // true\nconsole.log(3 >= 3);         // true\nconsole.log(3 === 3);        // true (strict equality)\nconsole.log(3 !== 4);        // true\nconsole.log("3" == 3);       // true (loose equality — coerces!)\nconsole.log("3" === 3);      // false (no coercion)' },
      { kind: "heading", content: "Logical operators" },
      { kind: "code", language: "javascript", code: 'console.log(true && false);  // false\nconsole.log(true || false);  // true\nconsole.log(!true);          // false\n\n// Short-circuit evaluation\nconst user = null;\nconsole.log(user && user.name);  // null (doesn\'t evaluate user.name)\n\nconst name = user?.name ?? "Anonymous";  // "Anonymous"\nconsole.log(name);' },
      { kind: "heading", content: "Math object" },
      { kind: "code", language: "javascript", code: 'console.log(Math.PI);           // 3.141592653589793\nconsole.log(Math.sqrt(16));     // 4\nconsole.log(Math.max(1, 5, 3)); // 5\nconsole.log(Math.min(1, 5, 3)); // 1\nconsole.log(Math.random());     // 0 to <1\nconsole.log(Math.floor(3.9));   // 3\nconsole.log(Math.ceil(3.1));    // 4\nconsole.log(Math.round(3.5));   // 4' },
    ],
    quiz: [
      { id: "q1", question: "What does `0.1 + 0.2 === 0.3` return?", options: ["true", "false", "Error", "undefined"], correctIndex: 1, explanation: "Floating-point arithmetic isn't exact — use an epsilon comparison." },
      { id: "q2", question: "What does `5 % 2` return?", options: ["2.5", "1", "2", "0"], correctIndex: 1 },
      { id: "q3", question: "What does `Math.floor(3.9)` return?", options: ["3", "4", "3.5", "Error"], correctIndex: 0 },
    ],
  },
  {
    id: "js-05",
    track: "javascript",
    order: 5,
    title: "Arrays",
    description: "Ordered collections in JavaScript.",
    difficulty: "beginner",
    estMinutes: 50,
    blocks: [
      { kind: "heading", content: "Creating arrays" },
      { kind: "code", language: "javascript", code: 'const fruits = ["apple", "banana", "cherry"];\nconst mixed = [1, "hello", true, null];\nconst empty = [];\nconst numbers = new Array(1, 2, 3);\n\nconsole.log(fruits.length);   // 3\nconsole.log(fruits[0]);       // apple\nconsole.log(fruits[fruits.length - 1]);  // cherry' },
      { kind: "heading", content: "Adding and removing" },
      { kind: "code", language: "javascript", code: 'const arr = [1, 2, 3];\n\narr.push(4);          // add to end -> [1, 2, 3, 4]\narr.unshift(0);       // add to start -> [0, 1, 2, 3, 4]\n\nconst last = arr.pop();       // remove from end -> 4\nconst first = arr.shift();    // remove from start -> 0\n\nconsole.log(arr);     // [1, 2, 3]' },
      { kind: "heading", content: "Iteration methods" },
      { kind: "code", language: "javascript", code: 'const nums = [1, 2, 3, 4, 5];\n\n// forEach — side effects\nnums.forEach((n, i) => console.log(i, n));\n\n// map — transform each element\nconst doubled = nums.map(n => n * 2);\nconsole.log(doubled);  // [2, 4, 6, 8, 10]\n\n// filter — keep elements that pass\nconst evens = nums.filter(n => n % 2 === 0);\nconsole.log(evens);    // [2, 4]\n\n// reduce — combine all into one\nconst sum = nums.reduce((acc, n) => acc + n, 0);\nconsole.log(sum);      // 15\n\n// find / findIndex\nconst firstEven = nums.find(n => n % 2 === 0);\nconsole.log(firstEven);  // 2\n\n// some / every\nconsole.log(nums.some(n => n > 4));   // true\nconsole.log(nums.every(n => n > 0));  // true' },
      { kind: "tip", content: "Master map, filter, and reduce — they're the heart of modern JavaScript data manipulation. They return new arrays instead of mutating, making code easier to reason about." },
      { kind: "heading", content: "Other useful methods" },
      { kind: "code", language: "javascript", code: 'const arr = [3, 1, 4, 1, 5, 9, 2, 6];\n\nconsole.log(arr.slice(2, 5));      // [4, 1, 5] (no mutation)\nconsole.log(arr.splice(2, 2));     // [4, 1] (mutates!)\nconsole.log(arr.includes(5));      // true\nconsole.log(arr.indexOf(9));       // 4 (after splice)\nconsole.log([...arr].sort());      // [1, 2, 3, 5, 6, 9]\nconsole.log([...arr].reverse());   // reversed\nconsole.log(Array.from("hello"));  // [\'h\', \'e\', \'l\', \'l\', \'o\']\nconsole.log([...arr, 100, 200]);   // spread to add' },
      { kind: "warning", content: "sort() mutates the original array and sorts as strings by default. Use arr.sort((a, b) => a - b) for numbers, and consider [...arr].sort() to avoid mutation." },
    ],
    quiz: [
      { id: "q1", question: "Which method transforms each element of an array?", options: ["forEach", "map", "filter", "reduce"], correctIndex: 1 },
      { id: "q2", question: "What does `[1,2,3].reduce((a,b) => a+b, 0)` return?", options: ["[1,2,3]", "6", "0", "Error"], correctIndex: 1 },
      { id: "q3", question: "Does `arr.sort()` mutate the original array?", options: ["Yes", "No", "Only with numbers", "Only with strings"], correctIndex: 0, explanation: "sort() mutates in place. Use [...arr].sort() to avoid mutation." },
    ],
  },
  {
    id: "js-06",
    track: "javascript",
    order: 6,
    title: "Objects",
    description: "Key-value pairs — JavaScript's main data structure.",
    difficulty: "beginner",
    estMinutes: 50,
    blocks: [
      { kind: "heading", content: "Object literals" },
      { kind: "text", content: "Objects are collections of key-value pairs. They're the most common data structure in JavaScript — JSON, configs, and most data are objects." },
      { kind: "code", language: "javascript", code: 'const person = {\n  name: "Alice",\n  age: 30,\n  skills: ["Python", "JavaScript"],\n  address: {\n    city: "Colombo",\n    country: "Sri Lanka"\n  },\n  greet() {\n    return `Hi, I\'m ${this.name}`;\n  }\n};\n\nconsole.log(person.name);          // Alice\nconsole.log(person["age"]);        // 30\nconsole.log(person.address.city);  // Colombo\nconsole.log(person.greet());       // Hi, I\'m Alice' },
      { kind: "heading", content: "Adding, updating, deleting" },
      { kind: "code", language: "javascript", code: 'const user = { name: "Bob" };\n\nuser.email = "bob@example.com";  // add\nuser.name = "Robert";           // update\ndelete user.email;               // delete\n\nconsole.log("name" in user);     // true\nconsole.log("email" in user);    // false' },
      { kind: "heading", content: "Destructuring" },
      { kind: "code", language: "javascript", code: 'const person = { name: "Alice", age: 30, city: "Colombo" };\n\n// Object destructuring\nconst { name, age } = person;\nconsole.log(name, age);  // Alice 30\n\n// Rename\nconst { name: fullName } = person;\nconsole.log(fullName);   // Alice\n\n// Default values\nconst { email = "N/A" } = person;\nconsole.log(email);      // N/A\n\n// Nested destructuring\nconst { address: { city } } = { name: "Bob", address: { city: "Kandy" } };\nconsole.log(city);       // Kandy' },
      { kind: "heading", content: "Spread and shorthand" },
      { kind: "code", language: "javascript", code: 'const defaults = { theme: "dark", fontSize: 14 };\nconst userPrefs = { fontSize: 16 };\n\nconst merged = { ...defaults, ...userPrefs };\nconsole.log(merged);  // { theme: "dark", fontSize: 16 }\n\n// Shorthand property names\nconst name = "Alice";\nconst age = 30;\nconst person = { name, age };  // { name: "Alice", age: 30 }' },
      { kind: "heading", content: "Object methods" },
      { kind: "code", language: "javascript", code: 'const obj = { a: 1, b: 2, c: 3 };\n\nconsole.log(Object.keys(obj));     // [\'a\', \'b\', \'c\']\nconsole.log(Object.values(obj));   // [1, 2, 3]\nconsole.log(Object.entries(obj));  // [[\'a\', 1], [\'b\', 2], [\'c\', 3]]\n\nfor (const [key, value] of Object.entries(obj)) {\n  console.log(`${key} = ${value}`);\n}' },
      { kind: "tip", content: "Use Object.entries() + destructuring to iterate over key-value pairs. Cleaner than a manual for-in loop." },
    ],
    quiz: [
      { id: "q1", question: "How do you access the `name` property of an object `person`?", options: ["person->name", "person.name", "person::name", "person(name)"], correctIndex: 1 },
      { id: "q2", question: "What does `Object.keys({a:1, b:2})` return?", options: ["[1, 2]", "['a', 'b']", "{a:1, b:2}", "Error"], correctIndex: 1 },
      { id: "q3", question: "What does `{ ...a, ...b }` do?", options: ["Adds a and b", "Merges a and b (b overrides a)", "Compares a and b", "Creates an empty object"], correctIndex: 1 },
    ],
  },
  {
    id: "js-07",
    track: "javascript",
    order: 7,
    title: "Conditionals (if/else/switch)",
    description: "Branch your code with conditionals.",
    difficulty: "beginner",
    estMinutes: 35,
    blocks: [
      { kind: "heading", content: "if / else if / else" },
      { kind: "code", language: "javascript", code: 'const age = 20;\n\nif (age < 13) {\n  console.log("Child");\n} else if (age < 20) {\n  console.log("Teenager");\n} else if (age < 65) {\n  console.log("Adult");\n} else {\n  console.log("Senior");\n}' },
      { kind: "heading", content: "Truthy and falsy" },
      { kind: "text", content: "JavaScript has 6 falsy values: false, 0, '', null, undefined, NaN. Everything else is truthy — including '0', 'false', [], and {}." },
      { kind: "code", language: "javascript", code: 'if ("hello") console.log("truthy");   // truthy\nif (0) console.log("truthy");        // (no output)\nif ([]) console.log("truthy");       // truthy (empty array!)\nif ("") console.log("truthy");       // (no output)\n\nconst name = "";\nif (!name) console.log("Please enter name");  // prints' },
      { kind: "warning", content: "An empty array [] is truthy in JS! Use arr.length > 0 to check if it has items." },
      { kind: "heading", content: "Ternary operator" },
      { kind: "code", language: "javascript", code: 'const age = 17;\nconst status = age < 18 ? "minor" : "adult";\nconsole.log(status);  // minor\n\n// Multiple ternaries (use sparingly)\nconst label = age < 13 ? "child" : age < 20 ? "teen" : "adult";' },
      { kind: "heading", content: "Short-circuit evaluation" },
      { kind: "code", language: "javascript", code: 'const user = null;\nconst name = user?.name ?? "Anonymous";\nconsole.log(name);  // Anonymous\n\n// || for defaults\nconst input = "";\nconst value = input || "default";\nconsole.log(value);  // "default"\n\n// && for conditional execution\nconst loggedIn = true;\nloggedIn && console.log("Welcome!");' },
      { kind: "heading", content: "switch" },
      { kind: "code", language: "javascript", code: 'const command = "start";\n\nswitch (command) {\n  case "start":\n    console.log("Starting...");\n    break;\n  case "stop":\n    console.log("Stopping...");\n    break;\n  case "pause":\n  case "resume":\n    console.log("State changed");\n    break;\n  default:\n    console.log("Unknown command");\n}' },
      { kind: "tip", content: "Don't forget `break` in switch cases! Without it, execution falls through to the next case (which is sometimes intentional, but usually a bug)." },
    ],
    quiz: [
      { id: "q1", question: "How many falsy values does JavaScript have?", options: ["3", "5", "6", "10"], correctIndex: 2, explanation: "false, 0, '', null, undefined, NaN — that's 6." },
      { id: "q2", question: "Is an empty array [] truthy or falsy?", options: ["Falsy", "Truthy", "Depends on context", "Error"], correctIndex: 1, explanation: "Unlike Python, empty arrays are truthy in JavaScript." },
      { id: "q3", question: "What does the `??` operator do?", options: ["Strict equality", "Nullish coalescing — defaults for null/undefined only", "Logical OR", "Optional chaining"], correctIndex: 1 },
    ],
  },
  {
    id: "js-08",
    track: "javascript",
    order: 8,
    title: "Loops (for, while, for-of, for-in)",
    description: "Repeat work with various loop constructs.",
    difficulty: "beginner",
    estMinutes: 40,
    blocks: [
      { kind: "heading", content: "Classic for loop" },
      { kind: "code", language: "javascript", code: 'for (let i = 0; i < 5; i++) {\n  console.log(i);  // 0 1 2 3 4\n}\n\n// Loop over array indices\nconst fruits = ["apple", "banana", "cherry"];\nfor (let i = 0; i < fruits.length; i++) {\n  console.log(i, fruits[i]);\n}' },
      { kind: "heading", content: "for...of — iterate values" },
      { kind: "code", language: "javascript", code: 'const fruits = ["apple", "banana", "cherry"];\nfor (const fruit of fruits) {\n  console.log(fruit);\n}\n\n// Works on any iterable (strings, Maps, Sets, etc.)\nfor (const char of "hello") {\n  console.log(char);  // h e l l o\n}' },
      { kind: "tip", content: "Prefer for...of over classic for loops when you don't need the index. It's cleaner and less error-prone." },
      { kind: "heading", content: "for...in — iterate keys (careful!)" },
      { kind: "code", language: "javascript", code: 'const person = { name: "Alice", age: 30 };\nfor (const key in person) {\n  console.log(key, person[key]);\n  // name Alice\n  // age 30\n}' },
      { kind: "warning", content: "for...in loops over enumerable properties, including inherited ones. Don't use it for arrays — use for...of or .forEach() instead." },
      { kind: "heading", content: "while and do...while" },
      { kind: "code", language: "javascript", code: 'let count = 0;\nwhile (count < 3) {\n  console.log(count);  // 0 1 2\n  count++;\n}\n\n// do...while runs at least once\ndo {\n  console.log("runs once");\n} while (false);' },
      { kind: "heading", content: "break and continue" },
      { kind: "code", language: "javascript", code: 'for (let i = 0; i < 10; i++) {\n  if (i === 5) break;     // exit loop\n  if (i % 2 === 0) continue;  // skip even\n  console.log(i);  // 1 3\n}' },
      { kind: "heading", content: "Array iteration methods (preferred)" },
      { kind: "code", language: "javascript", code: 'const nums = [1, 2, 3, 4, 5];\n\nnums.forEach(n => console.log(n));\n\nconst doubled = nums.map(n => n * 2);\n\nconst evens = nums.filter(n => n % 2 === 0);\n\nconst sum = nums.reduce((acc, n) => acc + n, 0);' },
      { kind: "tip", content: "Use .map(), .filter(), .reduce() instead of loops wherever possible. They're declarative and avoid off-by-one errors." },
    ],
    quiz: [
      { id: "q1", question: "Which loop iterates over array values?", options: ["for...in", "for...of", "while", "do...while"], correctIndex: 1 },
      { id: "q2", question: "Which loop iterates over object keys?", options: ["for...in", "for...of", "foreach", "iterate"], correctIndex: 0 },
      { id: "q3", question: "Does do...while run at least once?", options: ["Yes, always", "No, only if condition is true", "Only if loop is empty", "It depends"], correctIndex: 0 },
    ],
  },
  {
    id: "js-09",
    track: "javascript",
    order: 9,
    title: "Functions and Arrow Functions",
    description: "Define and use functions, including arrow functions.",
    difficulty: "beginner",
    estMinutes: 50,
    blocks: [
      { kind: "heading", content: "Function declarations" },
      { kind: "code", language: "javascript", code: 'function greet(name) {\n  return `Hello, ${name}!`;\n}\n\nconsole.log(greet("Alice"));  // Hello, Alice!\n\n// Function declarations are hoisted — can be called before defined\nconsole.log(add(2, 3));  // 5\nfunction add(a, b) { return a + b; }' },
      { kind: "heading", content: "Function expressions" },
      { kind: "code", language: "javascript", code: 'const greet = function(name) {\n  return `Hello, ${name}!`;\n};\n\n// NOT hoisted — must be defined before use\n// console.log(add(2, 3));  // TypeError\nconst add = function(a, b) { return a + b; };' },
      { kind: "heading", content: "Arrow functions" },
      { kind: "text", content: "Arrow functions are a concise syntax introduced in ES6. They're now the default for short functions, especially callbacks." },
      { kind: "code", language: "javascript", code: '// Single expression — implicit return\nconst square = x => x * 2;\n\n// No parameters\nconst greet = () => "Hello!";\n\n// Multiple parameters\nconst add = (a, b) => a + b;\n\n// Block body — explicit return\nconst greet = (name) => {\n  const msg = `Hello, ${name}!`;\n  return msg;\n};\n\n// Returning an object literal — wrap in parens\nconst makeUser = (name, age) => ({ name, age });' },
      { kind: "heading", content: "Default parameters" },
      { kind: "code", language: "javascript", code: 'function greet(name = "Guest", greeting = "Hello") {\n  return `${greeting}, ${name}!`;\n}\n\nconsole.log(greet());              // Hello, Guest!\nconsole.log(greet("Alice"));       // Hello, Alice!\nconsole.log(greet("Bob", "Hi"));   // Hi, Bob!' },
      { kind: "heading", content: "Rest parameters" },
      { kind: "code", language: "javascript", code: 'function sum(...nums) {\n  return nums.reduce((acc, n) => acc + n, 0);\n}\n\nconsole.log(sum(1, 2, 3));       // 6\nconsole.log(sum(10, 20, 30, 40)); // 100' },
      { kind: "heading", content: "Arrow vs regular functions — `this`" },
      { kind: "warning", content: "Arrow functions don't bind their own `this` — they inherit it from the enclosing scope. This is great for callbacks but breaks object methods." },
      { kind: "code", language: "javascript", code: 'const obj = {\n  name: "Alice",\n  // Regular function — `this` is obj\n  greetRegular() {\n    return `Hi, ${this.name}`;\n  },\n  // Arrow function — `this` is undefined (or window)\n  greetArrow: () => `Hi, ${this?.name}`,\n};\n\nconsole.log(obj.greetRegular());  // Hi, Alice\nconsole.log(obj.greetArrow());    // Hi, undefined' },
    ],
    quiz: [
      { id: "q1", question: "Are function declarations hoisted?", options: ["Yes", "No", "Only in strict mode", "Only arrow functions"], correctIndex: 0 },
      { id: "q2", question: "What's the arrow function equivalent of `function(x) { return x*2; }`?", options: ["x => x*2", "(x) -> x*2", "x => { x*2 }", "function x => x*2"], correctIndex: 0 },
      { id: "q3", question: "Do arrow functions have their own `this`?", options: ["Yes", "No — they inherit from enclosing scope", "Only when used as methods", "Only with new keyword"], correctIndex: 1 },
    ],
  },
  {
    id: "js-10",
    track: "javascript",
    order: 10,
    title: "Classes and OOP",
    description: "Object-oriented programming with classes.",
    difficulty: "intermediate",
    estMinutes: 55,
    blocks: [
      { kind: "heading", content: "Class basics" },
      { kind: "code", language: "javascript", code: 'class Dog {\n  constructor(name, age) {\n    this.name = name;\n    this.age = age;\n  }\n\n  bark() {\n    return `${this.name} says Woof!`;\n  }\n\n  static info() {\n    return "Dogs are great!";\n  }\n}\n\nconst buddy = new Dog("Buddy", 3);\nconsole.log(buddy.name);      // Buddy\nconsole.log(buddy.bark());    // Buddy says Woof!\nconsole.log(Dog.info());      // Dogs are great!' },
      { kind: "heading", content: "Inheritance" },
      { kind: "code", language: "javascript", code: 'class Animal {\n  constructor(name) {\n    this.name = name;\n  }\n\n  speak() {\n    return `${this.name} makes a sound`;\n  }\n}\n\nclass Cat extends Animal {\n  speak() {\n    return `${this.name} says Meow`;\n  }\n}\n\nclass Dog extends Animal {\n  constructor(name, breed) {\n    super(name);  // call parent constructor\n    this.breed = breed;\n  }\n\n  speak() {\n    return `${super.speak()} — Woof!`;\n  }\n}\n\nconsole.log(new Cat("Whiskers").speak());  // Whiskers says Meow\nconsole.log(new Dog("Buddy", "Lab").speak());  // Buddy makes a sound — Woof!' },
      { kind: "heading", content: "Getters and setters" },
      { kind: "code", language: "javascript", code: 'class Temperature {\n  constructor(celsius) {\n    this._celsius = celsius;\n  }\n\n  get fahrenheit() {\n    return this._celsius * 9/5 + 32;\n  }\n\n  set fahrenheit(f) {\n    this._celsius = (f - 32) * 5/9;\n  }\n}\n\nconst t = new Temperature(25);\nconsole.log(t.fahrenheit);  // 77 (calls getter)\nt.fahrenheit = 98.6;        // calls setter\nconsole.log(t._celsius);    // 37' },
      { kind: "heading", content: "Private fields (ES2022)" },
      { kind: "code", language: "javascript", code: 'class BankAccount {\n  #balance = 0;  // private field\n\n  deposit(amount) {\n    if (amount <= 0) throw new Error("Invalid amount");\n    this.#balance += amount;\n  }\n\n  get balance() {\n    return this.#balance;\n  }\n}\n\nconst acc = new BankAccount();\nacc.deposit(100);\nconsole.log(acc.balance);  // 100\n// console.log(acc.#balance);  // SyntaxError' },
      { kind: "tip", content: "Use # for true private fields (ES2022+). The older convention _name is just a hint — it doesn't actually prevent access." },
      { kind: "heading", content: "Static methods and fields" },
      { kind: "code", language: "javascript", code: 'class MathUtils {\n  static PI = 3.14159;\n\n  static square(x) {\n    return x * x;\n  }\n}\n\nconsole.log(MathUtils.PI);        // 3.14159\nconsole.log(MathUtils.square(5)); // 25' },
    ],
    quiz: [
      { id: "q1", question: "What does `super(name)` do in a subclass constructor?", options: ["Calls a sibling method", "Calls the parent class constructor", "Creates a static method", "Throws an error"], correctIndex: 1 },
      { id: "q2", question: "How do you define a private field in modern JS?", options: ["_name", "private name", "#name", "this.private.name"], correctIndex: 2 },
      { id: "q3", question: "How do you call a static method?", options: ["instance.method()", "Class.method()", "this.method()", "super.method()"], correctIndex: 1 },
    ],
  },
  {
    id: "js-11",
    track: "javascript",
    order: 11,
    title: "Asynchronous JavaScript (Promises & async/await)",
    description: "Handle async operations without callback hell.",
    difficulty: "intermediate",
    estMinutes: 60,
    blocks: [
      { kind: "heading", content: "Why async?" },
      { kind: "text", content: "JavaScript is single-threaded. Long operations (network requests, file I/O, timers) would freeze the UI if they ran synchronously. Async patterns let your code keep running while waiting." },
      { kind: "heading", content: "Promises" },
      { kind: "text", content: "A Promise represents a value that may not be available yet. It's in one of three states: pending, fulfilled, or rejected." },
      { kind: "code", language: "javascript", code: 'const promise = new Promise((resolve, reject) => {\n  setTimeout(() => {\n    const success = Math.random() > 0.5;\n    if (success) resolve("It worked!");\n    else reject(new Error("It failed"));\n  }, 1000);\n});\n\npromise\n  .then(result => console.log(result))\n  .catch(err => console.error(err))\n  .finally(() => console.log("done"));' },
      { kind: "heading", content: "async/await" },
      { kind: "text", content: "async/await (ES2017) is syntactic sugar over promises that makes async code look synchronous. It's the modern standard." },
      { kind: "code", language: "javascript", code: 'async function fetchUser(id) {\n  try {\n    const response = await fetch(`/api/users/${id}`);\n    if (!response.ok) throw new Error("Not found");\n    const user = await response.json();\n    return user;\n  } catch (err) {\n    console.error("Failed:", err);\n    return null;\n  }\n}\n\nconst user = await fetchUser(1);\nconsole.log(user);' },
      { kind: "heading", content: "Parallel promises" },
      { kind: "code", language: "javascript", code: '// Run in parallel, wait for all\nconst [user, posts, comments] = await Promise.all([\n  fetchUser(1),\n  fetchPosts(1),\n  fetchComments(1),\n]);\n\n// Wait for first to complete\nconst fastest = await Promise.race([\n  fetchFromCache(id),\n  fetchFromNetwork(id),\n]);\n\n// AllSettled — never rejects, returns all results\nconst results = await Promise.allSettled([\n  tryApi1(),\n  tryApi2(),\n  tryApi3(),\n]);' },
      { kind: "heading", content: "Timers" },
      { kind: "code", language: "javascript", code: '// setTimeout — run once after delay\nsetTimeout(() => console.log("1s later"), 1000);\n\n// setInterval — run repeatedly\nconst id = setInterval(() => console.log("every 1s"), 1000);\nclearInterval(id);  // stop\n\n// Promise-based delay\nconst delay = ms => new Promise(r => setTimeout(r, ms));\nawait delay(2000);\nconsole.log("2s later");' },
      { kind: "warning", content: "await only works inside async functions (or at the top level of an ES module). Calling await in a regular function is a syntax error." },
      { kind: "tip", content: "Always wrap await in try/catch unless you're sure the promise can't reject. Unhandled rejections crash Node.js and cause uncaught errors in browsers." },
    ],
    quiz: [
      { id: "q1", question: "What are the three states of a Promise?", options: ["start/stop/error", "pending/fulfilled/rejected", "init/run/done", "open/closed/error"], correctIndex: 1 },
      { id: "q2", question: "Where can you use `await`?", options: ["Anywhere", "Only inside async functions or modules", "Only in classes", "Only in try/catch"], correctIndex: 1 },
      { id: "q3", question: "What does Promise.all do?", options: ["Runs promises sequentially", "Runs promises in parallel, waits for all", "Returns the fastest promise", "Cancels slow promises"], correctIndex: 1 },
    ],
  },
  {
    id: "js-12",
    track: "javascript",
    order: 12,
    title: "Fetching Data from APIs",
    description: "Use fetch() to call REST APIs.",
    difficulty: "intermediate",
    estMinutes: 45,
    blocks: [
      { kind: "heading", content: "fetch() basics" },
      { kind: "text", content: "fetch() is the modern browser API for HTTP requests. It returns a Promise that resolves to a Response object." },
      { kind: "code", language: "javascript", code: 'const response = await fetch("https://api.github.com/users/torvalds");\nconst data = await response.json();\nconsole.log(data.login);       // torvalds\nconsole.log(data.followers);   // a big number' },
      { kind: "heading", content: "Handling errors" },
      { kind: "code", language: "javascript", code: 'async function getUser(name) {\n  try {\n    const res = await fetch(`https://api.github.com/users/${name}`);\n    \n    if (!res.ok) {\n      throw new Error(`HTTP ${res.status}: ${res.statusText}`);\n    }\n    \n    return await res.json();\n  } catch (err) {\n    console.error("Fetch failed:", err);\n    return null;\n  }\n}\n\nconst user = await getUser("torvalds");' },
      { kind: "warning", content: "fetch() only rejects on network errors — HTTP 404/500 are NOT errors! Check `response.ok` or `response.status` yourself." },
      { kind: "heading", content: "POST/PUT/DELETE requests" },
      { kind: "code", language: "javascript", code: '// POST with JSON body\nconst res = await fetch("/api/users", {\n  method: "POST",\n  headers: {\n    "Content-Type": "application/json",\n    "Authorization": `Bearer ${token}`,\n  },\n  body: JSON.stringify({\n    name: "Alice",\n    email: "alice@example.com",\n  }),\n});\n\nconst created = await res.json();\n\n// DELETE\nawait fetch(`/api/users/${id}`, { method: "DELETE" });' },
      { kind: "heading", content: "Query parameters" },
      { kind: "code", language: "javascript", code: 'const params = new URLSearchParams({\n  q: "python",\n  sort: "stars",\n  page: "1",\n});\n\nconst res = await fetch(`/api/search?${params}`);\nconst data = await res.json();' },
      { kind: "heading", content: "AbortController — cancellation" },
      { kind: "code", language: "javascript", code: 'const controller = new AbortController();\n\n// Cancel after 5 seconds\nsetTimeout(() => controller.abort(), 5000);\n\ntry {\n  const res = await fetch("/api/slow", {\n    signal: controller.signal,\n  });\n  const data = await res.json();\n} catch (err) {\n  if (err.name === "AbortError") {\n    console.log("Request was cancelled");\n  } else {\n    throw err;\n  }\n}' },
      { kind: "tip", content: "Always pass a timeout to fetch via AbortController. Otherwise a slow server can hang your UI indefinitely." },
    ],
    quiz: [
      { id: "q1", question: "What does fetch() return?", options: ["The data directly", "A Promise that resolves to a Response", "An XMLHttpRequest", "A callback"], correctIndex: 1 },
      { id: "q2", question: "Does fetch() reject on a 404 response?", options: ["Yes", "No — only on network errors", "Only in strict mode", "Only with CORS"], correctIndex: 1, explanation: "fetch() only rejects on network errors. HTTP errors (4xx, 5xx) are normal responses — check response.ok." },
      { id: "q3", question: "How do you cancel a fetch request?", options: ["request.cancel()", "AbortController", "fetch(timeout: 5000)", "You can't cancel fetches"], correctIndex: 1 },
    ],
  },
  {
    id: "js-13",
    track: "javascript",
    order: 13,
    title: "The DOM — Manipulating Web Pages",
    description: "Select, modify, and respond to web page elements.",
    difficulty: "intermediate",
    estMinutes: 55,
    blocks: [
      { kind: "heading", content: "Selecting elements" },
      { kind: "code", language: "javascript", code: '// By ID\nconst header = document.getElementById("header");\n\n// By CSS selector\nconst button = document.querySelector(".btn-primary");\nconst items = document.querySelectorAll(".list-item");  // NodeList\n\n// By class/tag\nconst buttons = document.getElementsByClassName("btn");  // HTMLCollection\nconst paragraphs = document.getElementsByTagName("p");' },
      { kind: "heading", content: "Modifying elements" },
      { kind: "code", language: "javascript", code: 'const heading = document.querySelector("h1");\n\nheading.textContent = "New Title";\nheading.innerHTML = "<em>Fancy</em> Title";\nheading.style.color = "blue";\nheading.classList.add("highlight");\nheading.classList.remove("dim");\nheading.classList.toggle("active");\nheading.id = "main-heading";' },
      { kind: "heading", content: "Creating and appending" },
      { kind: "code", language: "javascript", code: 'const list = document.querySelector("ul");\n\nconst newItem = document.createElement("li");\nnewItem.textContent = "New item";\nnewItem.classList.add("list-item");\n\nlist.appendChild(newItem);\n\n// Or use insertAdjacentHTML\nlist.insertAdjacentHTML("beforeend", "<li>HTML item</li>");\n\n// Remove\nnewItem.remove();' },
      { kind: "heading", content: "Event listeners" },
      { kind: "code", language: "javascript", code: 'const button = document.querySelector("button");\n\nbutton.addEventListener("click", (e) => {\n  console.log("Clicked!", e.target);\n});\n\n// Common events: click, input, change, submit, keydown, mouseover\n// Remove listener (must be same function reference)\nconst handler = () => console.log("hi");\nbutton.addEventListener("click", handler);\nbutton.removeEventListener("click", handler);' },
      { kind: "heading", content: "Event delegation" },
      { kind: "code", language: "javascript", code: '// Instead of attaching to each item, attach to parent\nconst list = document.querySelector("ul");\nlist.addEventListener("click", (e) => {\n  if (e.target.tagName === "LI") {\n    console.log("Clicked:", e.target.textContent);\n  }\n});\n\n// Works for dynamically added items too!' },
      { kind: "heading", content: "Forms" },
      { kind: "code", language: "javascript", code: 'const form = document.querySelector("form");\n\nform.addEventListener("submit", (e) => {\n  e.preventDefault();  // stop page reload\n  \n  const formData = new FormData(form);\n  const data = Object.fromEntries(formData);\n  console.log(data);\n  \n  // Or access fields directly\n  const email = form.querySelector("#email").value;\n});' },
      { kind: "tip", content: "Use event delegation instead of attaching listeners to many child elements. It's faster and works for dynamically added elements." },
      { kind: "warning", content: "Avoid inline event handlers like <button onclick=\"...\"> — they couple HTML and JS, are hard to maintain, and don't scale." },
    ],
    quiz: [
      { id: "q1", question: "Which method selects the first matching element?", options: ["getElementById", "querySelector", "querySelectorAll", "selectElement"], correctIndex: 1 },
      { id: "q2", question: "How do you stop a form from reloading the page on submit?", options: ["return false", "e.preventDefault()", "form.stopReload()", "form.noReload = true"], correctIndex: 1 },
      { id: "q3", question: "What's event delegation?", options: ["Attaching many listeners to one element", "Attaching one listener to a parent to handle child events", "Removing all listeners", "Cancelling events"], correctIndex: 1 },
    ],
  },
  {
    id: "js-14",
    track: "javascript",
    order: 14,
    title: "localStorage and sessionStorage",
    description: "Persist data in the browser.",
    difficulty: "intermediate",
    estMinutes: 35,
    blocks: [
      { kind: "heading", content: "Browser storage options" },
      { kind: "text", content: "The browser offers three client-side storage options: localStorage (persists forever, ~5-10MB), sessionStorage (cleared when tab closes), and cookies (sent to server, ~4KB). For app data, localStorage is usually right." },
      { kind: "heading", content: "localStorage basics" },
      { kind: "code", language: "javascript", code: '// localStorage stores strings only — serialize objects with JSON\nlocalStorage.setItem("name", "Alice");\nconsole.log(localStorage.getItem("name"));  // Alice\n\n// Objects\nconst user = { name: "Alice", age: 30 };\nlocalStorage.setItem("user", JSON.stringify(user));\n\nconst loaded = JSON.parse(localStorage.getItem("user"));\nconsole.log(loaded.name);  // Alice\n\n// Remove\nlocalStorage.removeItem("name");\n\n// Clear all\nlocalStorage.clear();' },
      { kind: "heading", content: "Useful helpers" },
      { kind: "code", language: "javascript", code: 'const storage = {\n  get(key, defaultValue = null) {\n    try {\n      const raw = localStorage.getItem(key);\n      return raw ? JSON.parse(raw) : defaultValue;\n    } catch {\n      return defaultValue;\n    }\n  },\n  \n  set(key, value) {\n    try {\n      localStorage.setItem(key, JSON.stringify(value));\n      return true;\n    } catch (e) {\n      console.error("Storage full or unavailable:", e);\n      return false;\n    }\n  },\n  \n  remove(key) {\n    localStorage.removeItem(key);\n  },\n};\n\nstorage.set("theme", "dark");\nconsole.log(storage.get("theme", "light"));' },
      { kind: "heading", content: "Storage events" },
      { kind: "code", language: "javascript", code: '// Listen for changes from OTHER tabs\nwindow.addEventListener("storage", (e) => {\n  console.log(`${e.key} changed from ${e.oldValue} to ${e.newValue}`);\n  if (e.key === "theme") {\n    applyTheme(e.newValue);\n  }\n});' },
      { kind: "warning", content: "localStorage is synchronous and blocks the main thread. Don't store huge objects — for big data, use IndexedDB instead." },
      { kind: "tip", content: "Always wrap localStorage in try/catch — it can throw (private browsing mode, quota exceeded, disabled)." },
    ],
    quiz: [
      { id: "q1", question: "What data type can localStorage store directly?", options: ["Objects", "Arrays", "Strings only", "Numbers"], correctIndex: 2, explanation: "localStorage only stores strings — use JSON.stringify/parse for objects." },
      { id: "q2", question: "When is sessionStorage cleared?", options: ["On page reload", "When the tab is closed", "After 1 hour", "Never"], correctIndex: 1 },
      { id: "q3", question: "How can one tab know if another tab changed localStorage?", options: ["Polling", "storage event", "It can't", "WebSocket"], correctIndex: 1 },
    ],
  },
  {
    id: "js-15",
    track: "javascript",
    order: 15,
    title: "Modules (import/export) and Testing",
    description: "Organize code into modules and write tests.",
    difficulty: "intermediate",
    estMinutes: 55,
    blocks: [
      { kind: "heading", content: "ES Modules" },
      { kind: "text", content: "ES Modules (ESM) are the official JavaScript module system. They replace older systems like CommonJS (require) and AMD." },
      { kind: "code", language: "javascript", code: '// math.js — exports\nexport function add(a, b) {\n  return a + b;\n}\n\nexport const PI = 3.14159;\n\n// Default export (one per module)\nexport default function square(x) {\n  return x * x;\n}\n\n// app.js — imports\nimport square, { add, PI } from "./math.js";\nconsole.log(add(2, 3));   // 5\nconsole.log(PI);          // 3.14159\nconsole.log(square(5));   // 25\n\n// Rename on import\nimport { add as plus } from "./math.js";\n\n// Import everything\nimport * as math from "./math.js";\nconsole.log(math.add(1, 1));' },
      { kind: "heading", content: "Dynamic imports" },
      { kind: "code", language: "javascript", code: '// Load a module on demand (returns a Promise)\nconst button = document.querySelector("#calculate");\nbutton.addEventListener("click", async () => {\n  const math = await import("./math.js");\n  console.log(math.add(2, 3));\n});' },
      { kind: "heading", content: "Testing with Vitest" },
      { kind: "code", language: "bash", code: "npm install -D vitest" },
      { kind: "code", language: "javascript", code: '// math.js\nexport function add(a, b) { return a + b; }\n\n// math.test.js\nimport { describe, it, expect } from "vitest";\nimport { add } from "./math";\n\ndescribe("add", () => {\n  it("adds two numbers", () => {\n    expect(add(2, 3)).toBe(5);\n  });\n\n  it("handles negatives", () => {\n    expect(add(-1, 1)).toBe(0);\n  });\n\n  it("handles zero", () => {\n    expect(add(0, 0)).toBe(0);\n  });\n});' },
      { kind: "code", language: "bash", code: "$ npx vitest\n ✓ math.test.js (3 tests) ✓" },
      { kind: "heading", content: "Testing async code" },
      { kind: "code", language: "javascript", code: 'import { describe, it, expect } from "vitest";\n\ndescribe("fetchUser", () => {\n  it("returns user data", async () => {\n    const user = await fetchUser(1);\n    expect(user).toBeDefined();\n    expect(user.name).toBe("Alice");\n  });\n\n  it("throws on invalid id", async () => {\n    await expect(fetchUser(-1)).rejects.toThrow("Invalid id");\n  });\n});' },
      { kind: "heading", content: "Mocking" },
      { kind: "code", language: "javascript", code: 'import { vi } from "vitest";\n\n// Mock fetch globally\nglobal.fetch = vi.fn(() =>\n  Promise.resolve({\n    ok: true,\n    json: () => Promise.resolve({ name: "Alice" }),\n  })\n);\n\n// Mock a module\nvi.mock("./api", () => ({\n  getUser: vi.fn(() => Promise.resolve({ name: "Alice" })),\n}));' },
      { kind: "tip", content: "Write tests as you write code, not after. Test-first (TDD) is even better — write a failing test, then make it pass." },
      { kind: "warning", content: "Don't mock everything — over-mocking makes tests brittle and gives false confidence. Mock only external boundaries (network, filesystem, time)." },
    ],
    quiz: [
      { id: "q1", question: "What's the syntax for a default export?", options: ["export default function()", "default export function()", "export function default()", "module.exports = function()"], correctIndex: 0 },
      { id: "q2", question: "How do you dynamically import a module?", options: ["require()", "import()", "load()", "fetch module"], correctIndex: 1 },
      { id: "q3", question: "Which function asserts equality in Vitest?", options: ["assert()", "expect().toBe()", "equals()", "should()"], correctIndex: 1 },
    ],
  },
];

// Merge in lessons generated for all other languages
import { EXTRA_LANGUAGE_LESSONS } from "./lessons-extra";

export const ALL_LESSONS: Lesson[] = [
  ...PYTHON_LESSONS,
  ...JAVASCRIPT_LESSONS,
  ...EXTRA_LANGUAGE_LESSONS,
];

export const LESSON_MAP: Record<string, Lesson> = Object.fromEntries(
  ALL_LESSONS.map((l) => [l.id, l]),
);

// Get all unique tracks (languages) that have lessons
export function getAllTracks(): { id: string; name: string; icon: string; count: number }[] {
  const trackMap = new Map<string, { id: string; name: string; icon: string; count: number }>();
  for (const lesson of ALL_LESSONS) {
    const existing = trackMap.get(lesson.track);
    if (existing) {
      existing.count++;
    } else {
      // Find the language metadata
      const langInfo = ALL_LANGUAGE_INFO[lesson.track];
      trackMap.set(lesson.track, {
        id: lesson.track,
        name: langInfo?.name ?? lesson.track,
        icon: langInfo?.icon ?? "📘",
        count: 1,
      });
    }
  }
  return Array.from(trackMap.values()).sort((a, b) => a.name.localeCompare(b.name));
}

// Language metadata for all languages that have lessons
export const ALL_LANGUAGE_INFO: Record<string, { id: string; name: string; icon: string }> = {
  python: { id: "python", name: "Python", icon: "🐍" },
  javascript: { id: "javascript", name: "JavaScript", icon: "🟨" },
  typescript: { id: "typescript", name: "TypeScript", icon: "🔷" },
  java: { id: "java", name: "Java", icon: "☕" },
  c: { id: "c", name: "C", icon: "🔵" },
  cpp: { id: "cpp", name: "C++", icon: "➕" },
  csharp: { id: "csharp", name: "C#", icon: "#️⃣" },
  go: { id: "go", name: "Go", icon: "🐹" },
  rust: { id: "rust", name: "Rust", icon: "🦀" },
};

export function getLessonsForTrack(track: string): Lesson[] {
  return ALL_LESSONS.filter((l) => l.track === track).sort((a, b) => a.order - b.order);
}

export function getLessonById(id: string): Lesson | undefined {
  return LESSON_MAP[id];
}
