// ============================================================
// curriculum/module-catalog.ts — v6.004 Canonical Module Catalog.
//
// The SINGLE source of truth for the modules every track can pick
// from. A track's CurriculumTrackConfig references these by slug.
//
// This is ARCHITECTURE ONLY — no lesson content, no quizzes, no AI
// context. Just the module definitions + their relationships.
//
// The catalog is ordered by canonical `sequence`. Tracks may reorder
// via their CurriculumTrackModule.order, but this is the default.
//
// Module slug convention: `c_<short-name>` (the `c_` prefix avoids
// collisions with lesson slugs and quiz refs).
// ============================================================

import type { CurriculumModule } from "./types";

export const MODULE_CATALOG: CurriculumModule[] = [
  // ---- FOUNDATION ----
  {
    slug: "c_getting-started",
    title: "Getting Started",
    description: "Install the toolchain, write and run your first program, and understand the compile/interpret model.",
    icon: "🚀",
    difficulty: "beginner",
    difficultyScore: 1,
    sequence: 1,
    category: "foundation",
    estimatedHours: 2,
    optionalByDefault: false,
    requiredModules: [],
    skillsUnlocked: ["run-first-program"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: false,
    appliesTo: ["all"],
    version: "1.0.0",
  },
  {
    slug: "c_setup-tooling",
    title: "Setup & Tooling",
    description: "Editor setup, linters, formatters, debuggers, and the project structure conventions.",
    icon: "🛠️",
    difficulty: "beginner",
    difficultyScore: 1,
    sequence: 2,
    category: "foundation",
    estimatedHours: 2,
    optionalByDefault: false,
    requiredModules: ["c_getting-started"],
    skillsUnlocked: ["editor-setup", "linting"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: false,
    appliesTo: ["all"],
    version: "1.0.0",
  },
  {
    slug: "c_basic-syntax",
    title: "Basic Syntax",
    description: "Statements, expressions, comments, indentation/braces, and the lexical structure of the language.",
    icon: "📝",
    difficulty: "beginner",
    difficultyScore: 1,
    sequence: 3,
    category: "foundation",
    estimatedHours: 3,
    optionalByDefault: false,
    requiredModules: ["c_getting-started"],
    skillsUnlocked: ["syntax-basics"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: false,
    appliesTo: ["all"],
    version: "1.0.0",
  },
  {
    slug: "c_variables-types",
    title: "Variables & Types",
    description: "Declaration, mutation, primitive vs reference types, type inference, and the type system's core rules.",
    icon: "📦",
    difficulty: "beginner",
    difficultyScore: 2,
    sequence: 4,
    category: "foundation",
    estimatedHours: 4,
    optionalByDefault: false,
    requiredModules: ["c_basic-syntax"],
    skillsUnlocked: ["variables", "primitive-types"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: false,
    appliesTo: ["all"],
    version: "1.0.0",
  },
  {
    slug: "c_operators-expressions",
    title: "Operators & Expressions",
    description: "Arithmetic, comparison, logical, bitwise, and assignment operators; precedence and associativity.",
    icon: "➗",
    difficulty: "beginner",
    difficultyScore: 2,
    sequence: 5,
    category: "foundation",
    estimatedHours: 3,
    optionalByDefault: false,
    requiredModules: ["c_variables-types"],
    skillsUnlocked: ["operators"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: false,
    appliesTo: ["all"],
    version: "1.0.0",
  },
  {
    slug: "c_input-output",
    title: "Input & Output",
    description: "Reading from stdin, writing to stdout, formatting output, and basic user interaction.",
    icon: "⌨️",
    difficulty: "beginner",
    difficultyScore: 2,
    sequence: 6,
    category: "foundation",
    estimatedHours: 2,
    optionalByDefault: false,
    requiredModules: ["c_variables-types"],
    skillsUnlocked: ["io-basics"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: false,
    appliesTo: ["all"],
    version: "1.0.0",
  },

  // ---- CORE LANGUAGE ----
  {
    slug: "c_control-flow",
    title: "Control Flow",
    description: "Conditionals (if/else, switch/match), branching logic, and early returns.",
    icon: "🔀",
    difficulty: "beginner",
    difficultyScore: 2,
    sequence: 7,
    category: "core-language",
    estimatedHours: 3,
    optionalByDefault: false,
    requiredModules: ["c_operators-expressions"],
    skillsUnlocked: ["conditionals"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: false,
    appliesTo: ["all"],
    version: "1.0.0",
  },
  {
    slug: "c_loops-iteration",
    title: "Loops & Iteration",
    description: "for, while, do-while, iterators, break/continue, and idiomatic iteration patterns.",
    icon: "🔁",
    difficulty: "beginner",
    difficultyScore: 2,
    sequence: 8,
    category: "core-language",
    estimatedHours: 3,
    optionalByDefault: false,
    requiredModules: ["c_control-flow"],
    skillsUnlocked: ["loops"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: false,
    appliesTo: ["all"],
    version: "1.0.0",
  },
  {
    slug: "c_functions",
    title: "Functions",
    description: "Defining, calling, parameters, return values, scope, closures, and higher-order functions.",
    icon: "🔧",
    difficulty: "beginner",
    difficultyScore: 3,
    sequence: 9,
    category: "core-language",
    estimatedHours: 5,
    optionalByDefault: false,
    requiredModules: ["c_control-flow"],
    skillsUnlocked: ["functions", "scope"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: true,
    appliesTo: ["all"],
    version: "1.0.0",
  },
  {
    slug: "c_collections",
    title: "Collections & Data Structures",
    description: "Arrays/lists, maps/dicts, sets, tuples, and the standard collection library.",
    icon: "📚",
    difficulty: "intermediate",
    difficultyScore: 3,
    sequence: 10,
    category: "core-language",
    estimatedHours: 5,
    optionalByDefault: false,
    requiredModules: ["c_functions"],
    skillsUnlocked: ["collections", "data-structures"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: false,
    appliesTo: ["all"],
    version: "1.0.0",
  },
  {
    slug: "c_strings-text",
    title: "Strings & Text",
    description: "String representation, manipulation, formatting, encoding, and regular expressions.",
    icon: "🧵",
    difficulty: "intermediate",
    difficultyScore: 3,
    sequence: 11,
    category: "core-language",
    estimatedHours: 4,
    optionalByDefault: false,
    requiredModules: ["c_collections"],
    skillsUnlocked: ["strings", "regex"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: false,
    appliesTo: ["all"],
    version: "1.0.0",
  },

  // ---- ORGANIZATION ----
  {
    slug: "c_modules-packages",
    title: "Modules & Packages",
    description: "Code organization, imports/exports, namespaces, and the package manager ecosystem.",
    icon: "📦",
    difficulty: "intermediate",
    difficultyScore: 3,
    sequence: 12,
    category: "organization",
    estimatedHours: 4,
    optionalByDefault: false,
    requiredModules: ["c_functions"],
    skillsUnlocked: ["modules", "packages"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: false,
    appliesTo: ["all"],
    version: "1.0.0",
  },
  {
    slug: "c_file-io",
    title: "File I/O",
    description: "Reading/writing files, paths, streams, and resource cleanup (RAII / with / using).",
    icon: "📂",
    difficulty: "intermediate",
    difficultyScore: 3,
    sequence: 13,
    category: "organization",
    estimatedHours: 3,
    optionalByDefault: false,
    requiredModules: ["c_modules-packages"],
    skillsUnlocked: ["file-io"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: false,
    appliesTo: ["all"],
    version: "1.0.0",
  },
  {
    slug: "c_error-handling",
    title: "Error Handling",
    description: "Exceptions vs results, custom errors, propagation, and resilient error patterns.",
    icon: "🛡️",
    difficulty: "intermediate",
    difficultyScore: 3,
    sequence: 14,
    category: "organization",
    estimatedHours: 4,
    optionalByDefault: false,
    requiredModules: ["c_file-io"],
    skillsUnlocked: ["error-handling"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: true,
    appliesTo: ["all"],
    version: "1.0.0",
  },

  // ---- PARADIGMS (optional for some languages) ----
  {
    slug: "c_oop",
    title: "Object-Oriented Programming",
    description: "Classes, objects, inheritance, polymorphism, encapsulation, and design patterns.",
    icon: "🏛️",
    difficulty: "intermediate",
    difficultyScore: 4,
    sequence: 15,
    category: "paradigms",
    estimatedHours: 8,
    optionalByDefault: false,
    requiredModules: ["c_error-handling"],
    skillsUnlocked: ["oop", "classes", "inheritance"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: true,
    capstoneTier: "intermediate",
    appliesTo: ["compiled", "interpreted", "jvm", "web"],
    version: "1.0.0",
  },
  {
    slug: "c_functional",
    title: "Functional Programming",
    description: "First-class functions, immutability, map/filter/reduce, recursion, and pure functions.",
    icon: "λ",
    difficulty: "intermediate",
    difficultyScore: 4,
    sequence: 16,
    category: "paradigms",
    estimatedHours: 5,
    optionalByDefault: true,
    requiredModules: ["c_functions"],
    skillsUnlocked: ["functional-programming"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: false,
    appliesTo: ["all"],
    version: "1.0.0",
  },
  {
    slug: "c_generics-templates",
    title: "Generics / Templates",
    description: "Parameterized types, generic functions, constraints, and type-level abstraction.",
    icon: "🎯",
    difficulty: "advanced",
    difficultyScore: 4,
    sequence: 17,
    category: "paradigms",
    estimatedHours: 5,
    optionalByDefault: true,
    requiredModules: ["c_oop"],
    skillsUnlocked: ["generics"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: false,
    appliesTo: ["compiled", "jvm"],
    version: "1.0.0",
  },
  {
    slug: "c_metaprogramming",
    title: "Metaprogramming",
    description: "Reflection, macros, decorators, code generation, and compile-time metaprogramming.",
    icon: "🪄",
    difficulty: "advanced",
    difficultyScore: 5,
    sequence: 18,
    category: "paradigms",
    estimatedHours: 5,
    optionalByDefault: true,
    requiredModules: ["c_generics-templates"],
    skillsUnlocked: ["metaprogramming"],
    certificateEligible: false,
    hasModuleQuiz: false,
    hasCheckpointExam: false,
    appliesTo: ["compiled", "jvm", "interpreted"],
    version: "1.0.0",
  },

  // ---- ADVANCED LANGUAGE ----
  {
    slug: "c_memory-management",
    title: "Memory Management",
    description: "Stack vs heap, ownership/borrowing, GC, RAII, lifetimes, and memory safety.",
    icon: "🧠",
    difficulty: "advanced",
    difficultyScore: 5,
    sequence: 19,
    category: "advanced-language",
    estimatedHours: 6,
    optionalByDefault: true,
    requiredModules: ["c_oop"],
    skillsUnlocked: ["memory-management"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: false,
    capstoneTier: "advanced",
    appliesTo: ["compiled", "systems"],
    version: "1.0.0",
  },
  {
    slug: "c_concurrency-async",
    title: "Concurrency & Async",
    description: "Threads, async/await, promises/futures, channels, locks, and parallelism.",
    icon: "⚡",
    difficulty: "advanced",
    difficultyScore: 5,
    sequence: 20,
    category: "advanced-language",
    estimatedHours: 7,
    optionalByDefault: true,
    requiredModules: ["c_error-handling"],
    skillsUnlocked: ["concurrency", "async"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: true,
    appliesTo: ["all"],
    version: "1.0.0",
  },
  {
    slug: "c_interop-ffi",
    title: "Interop & FFI",
    description: "Calling C/other languages, foreign function interfaces, and platform bindings.",
    icon: "🔗",
    difficulty: "advanced",
    difficultyScore: 5,
    sequence: 21,
    category: "advanced-language",
    estimatedHours: 4,
    optionalByDefault: true,
    requiredModules: ["c_memory-management"],
    skillsUnlocked: ["ffi"],
    certificateEligible: false,
    hasModuleQuiz: false,
    hasCheckpointExam: false,
    appliesTo: ["compiled", "systems", "jvm"],
    version: "1.0.0",
  },

  // ---- PROFESSIONAL ----
  {
    slug: "c_networking",
    title: "Networking",
    description: "HTTP clients/servers, sockets, REST, and network protocol fundamentals.",
    icon: "🌐",
    difficulty: "intermediate",
    difficultyScore: 4,
    sequence: 22,
    category: "professional",
    estimatedHours: 5,
    optionalByDefault: true,
    requiredModules: ["c_error-handling"],
    skillsUnlocked: ["networking", "http"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: false,
    appliesTo: ["all"],
    version: "1.0.0",
  },
  {
    slug: "c_databases",
    title: "Databases",
    description: "SQL/NoSQL, connection management, ORMs, transactions, and schema design.",
    icon: "🗄️",
    difficulty: "intermediate",
    difficultyScore: 4,
    sequence: 23,
    category: "professional",
    estimatedHours: 6,
    optionalByDefault: true,
    requiredModules: ["c_file-io"],
    skillsUnlocked: ["databases", "sql"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: false,
    appliesTo: ["all"],
    version: "1.0.0",
  },
  {
    slug: "c_testing",
    title: "Testing",
    description: "Unit, integration, and property testing; test doubles; coverage; and TDD.",
    icon: "🧪",
    difficulty: "intermediate",
    difficultyScore: 3,
    sequence: 24,
    category: "professional",
    estimatedHours: 5,
    optionalByDefault: false,
    requiredModules: ["c_functions"],
    skillsUnlocked: ["testing", "tdd"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: false,
    appliesTo: ["all"],
    version: "1.0.0",
  },
  {
    slug: "c_debugging",
    title: "Debugging",
    description: "Debuggers, logging, profiling, stack traces, and systematic debugging methodology.",
    icon: "🐛",
    difficulty: "intermediate",
    difficultyScore: 3,
    sequence: 25,
    category: "professional",
    estimatedHours: 4,
    optionalByDefault: false,
    requiredModules: ["c_testing"],
    skillsUnlocked: ["debugging"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: false,
    appliesTo: ["all"],
    version: "1.0.0",
  },
  {
    slug: "c_performance",
    title: "Performance",
    description: "Profiling, optimization, big-O, caching, and language-specific performance pitfalls.",
    icon: "📊",
    difficulty: "advanced",
    difficultyScore: 4,
    sequence: 26,
    category: "professional",
    estimatedHours: 5,
    optionalByDefault: true,
    requiredModules: ["c_debugging"],
    skillsUnlocked: ["performance", "profiling"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: false,
    appliesTo: ["all"],
    version: "1.0.0",
  },
  {
    slug: "c_security",
    title: "Security",
    description: "Input validation, injection prevention, auth basics, secrets, and OWASP top issues.",
    icon: "🔐",
    difficulty: "advanced",
    difficultyScore: 4,
    sequence: 27,
    category: "professional",
    estimatedHours: 5,
    optionalByDefault: true,
    requiredModules: ["c_networking"],
    skillsUnlocked: ["security"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: false,
    appliesTo: ["all"],
    version: "1.0.0",
  },
  {
    slug: "c_best-practices",
    title: "Best Practices",
    description: "Idioms, style guides, code review, documentation, and maintainable code principles.",
    icon: "✅",
    difficulty: "intermediate",
    difficultyScore: 3,
    sequence: 28,
    category: "professional",
    estimatedHours: 4,
    optionalByDefault: false,
    requiredModules: ["c_testing"],
    skillsUnlocked: ["best-practices", "code-review"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: false,
    appliesTo: ["all"],
    version: "1.0.0",
  },
  {
    slug: "c_tooling-ecosystem",
    title: "Tooling & Ecosystem",
    description: "Build systems, package managers, CI/CD, and the language's ecosystem landscape.",
    icon: "🔧",
    difficulty: "intermediate",
    difficultyScore: 3,
    sequence: 29,
    category: "professional",
    estimatedHours: 4,
    optionalByDefault: true,
    requiredModules: ["c_modules-packages"],
    skillsUnlocked: ["build-tools", "ci-cd"],
    certificateEligible: true,
    hasModuleQuiz: true,
    hasCheckpointExam: false,
    appliesTo: ["all"],
    version: "1.0.0",
  },

  // ---- APPLICATION ----
  {
    slug: "c_real-projects",
    title: "Real Projects",
    description: "Guided real-world projects integrating multiple modules into working applications.",
    icon: "🏗️",
    difficulty: "advanced",
    difficultyScore: 4,
    sequence: 30,
    category: "application",
    estimatedHours: 10,
    optionalByDefault: false,
    requiredModules: ["c_best-practices"],
    skillsUnlocked: ["project-building"],
    certificateEligible: true,
    hasModuleQuiz: false,
    hasCheckpointExam: true,
    capstoneTier: "portfolio",
    appliesTo: ["all"],
    version: "1.0.0",
  },
  {
    slug: "c_final-capstone",
    title: "Final Capstone",
    description: "A comprehensive, certificate-gating project demonstrating mastery of the full track.",
    icon: "🎓",
    difficulty: "advanced",
    difficultyScore: 5,
    sequence: 31,
    category: "application",
    estimatedHours: 15,
    optionalByDefault: false,
    requiredModules: ["c_real-projects"],
    skillsUnlocked: ["capstone-mastery"],
    certificateEligible: true,
    hasModuleQuiz: false,
    hasCheckpointExam: false,
    capstoneTier: "certification",
    appliesTo: ["all"],
    version: "1.0.0",
  },
];

// ---- Lookup helpers ----

/** Map of module slug → CurriculumModule. */
export const MODULE_MAP: Record<string, CurriculumModule> = Object.fromEntries(
  MODULE_CATALOG.map((m) => [m.slug, m]),
);

/** Get a module by slug. Returns undefined if not found. */
export function getModule(slug: string): CurriculumModule | undefined {
  return MODULE_MAP[slug];
}

/** All module slugs (ordered by canonical sequence). */
export const ALL_MODULE_SLUGS: string[] = MODULE_CATALOG.map((m) => m.slug);

/** Modules that apply to a given archetype (including "all"). */
export function modulesForArchetype(archetype: string): CurriculumModule[] {
  return MODULE_CATALOG.filter((m) => m.appliesTo.includes("all" as never) || m.appliesTo.includes(archetype as never));
}

/** Total canonical module count. */
export const MODULE_COUNT = MODULE_CATALOG.length;
