#!/usr/bin/env python3
"""v5.87: Generate remaining short-track lessons and append to lessons-extended.ts"""
import json, sys

# Read current lessons-extended.ts
with open('src/lib/lessons-extended.ts', 'r') as f:
    content = f.read()

closing_idx = content.rfind('];')
before = content[:closing_idx].rstrip()
after = content[closing_idx:]

# Curriculum data: track -> list of (title, desc, diff, minutes, topics, concepts, code, lang, pitfalls, realWorld, interviewQs, miniProject)
DATA = {
    "tailwind": {"start": 16, "lessons": [
        ("Responsive Design Patterns", "Master responsive design: breakpoints, mobile-first.", "intermediate", 70, ["Breakpoint system sm md lg xl 2xl", "Mobile-first approach", "Responsive grid layouts", "Container queries"], ["Tailwind is mobile-first", "Responsive prefixes override base", "Container provides max-width"], "grid grid-cols-1 md:grid-cols-3", "html", ["Designing desktop-first", "Too many breakpoints"], ["E-commerce grids", "Dashboard layouts", "Blog sites"], ["What does mobile-first mean?", "How do breakpoints work?"], "Build a responsive card grid 1 to 3 columns."),
        ("Dark Mode and Theming", "Implement dark mode and custom themes.", "intermediate", 65, ["Dark mode with class strategy", "Custom color palettes", "CSS variables", "Theme switching"], ["darkMode class for toggle", "CSS variables for runtime switching", "Custom colors in theme extend"], "darkMode: class", "javascript", ["Forgetting dark variants", "Not respecting prefers-color-scheme"], ["User preference toggles", "System theme", "White-label apps"], ["How does class strategy work?", "CSS variables vs config?"], "Add dark mode support with toggle."),
        ("Custom Animations and Transitions", "Create smooth animations: transitions, keyframes.", "intermediate", 60, ["Transition properties", "Duration and easing", "Custom keyframe animations", "Animation delays"], ["Transitions for state changes", "Animations for keyframe motion", "Custom in config"], "hover:scale-105 transition-transform duration-300", "html", ["Animating layout properties", "Not setting will-change"], ["Micro-interactions", "Page transitions", "Loading states"], ["Transition vs animation?", "How to add custom keyframes?"], "Create hover animations and fade-in."),
        ("Component Extraction and Reuse", "Extract reusable components using apply and React patterns.", "advanced", 65, ["apply directive", "layer components", "React component patterns", "Variant extraction"], ["apply composes utilities", "layer for custom classes", "Extract patterns into components"], "btn { apply px-4 py-2 rounded-lg; }", "css", ["Overusing apply defeats utility-first", "Not using layer for purge"], ["Design systems", "UI libraries", "Team consistency"], ["What is apply?", "layer components vs utilities?"], "Extract Button and Card components."),
        ("Performance Optimization", "Optimize Tailwind: purge CSS, JIT mode, critical CSS.", "advanced", 60, ["Content config for purging", "JIT mode", "CSS compression", "Critical CSS"], ["PurgeCSS removes unused classes", "JIT generates on-demand", "Specify content paths"], "content: [./src/**/*.{html,js,tsx}]", "javascript", ["Not configuring content paths", "String concat for class names"], ["Production optimization", "Fast builds", "Tree-shaking"], ["How does Tailwind purge?", "What is JIT mode?"], "Configure purging and verify size reduction."),
        ("Capstone: Build a Landing Page", "Build a complete responsive landing page.", "advanced", 180, ["Landing page structure", "Responsive design", "Dark mode", "Animations", "Accessibility"], ["Fast loading on all devices", "Semantic HTML for a11y", "Micro-interactions improve engagement"], "container mx-auto px-4 py-20", "html", ["Not testing on mobile", "Too many large images"], ["SaaS marketing", "Product launches", "Portfolios"], ["Essential landing page sections?", "How to optimize for conversion?"], "Build complete responsive landing page with dark mode."),
    ]},
    "express": {"start": 16, "lessons": [
        ("Authentication and JWT", "Implement secure auth with JWT, bcrypt, middleware.", "intermediate", 75, ["JWT structure", "bcrypt hashing", "Auth middleware", "Token refresh"], ["JWT is stateless", "Always hash with bcrypt", "Access short refresh long"], "const token = jwt.sign({userId}, secret, {expiresIn:1h})", "javascript", ["Storing JWT_SECRET in code", "Not verifying expiration"], ["User login", "API auth", "SPA backends"], ["Access vs refresh token?", "Why bcrypt not SHA-256?"], "Build auth with register login protected routes."),
        ("File Uploads and Handling", "Handle file uploads with multer, validation, cloud storage.", "intermediate", 70, ["Multer config", "File type validation", "Size limits", "Cloud storage"], ["Multer handles multipart", "Validate MIME not extension", "Set size limits"], "const upload = multer({dest:uploads, limits:{fileSize:5MB}})", "javascript", ["No size limits allows DoS", "Trusting extensions"], ["Avatar uploads", "Document management", "Image processing"], ["How does multer work?", "MIME vs extension validation?"], "Create image upload route with validation."),
        ("Middleware Deep Dive", "Master middleware: error handling, logging, CORS, rate limiting.", "intermediate", 70, ["Execution order", "Error middleware", "Common middleware", "Custom middleware"], ["Runs in definition order", "Error middleware needs 4 params", "app.use vs router.use"], "app.use(helmet()); app.use(cors()); app.use(rateLimit())", "javascript", ["Forgetting next()", "Error middleware not last"], ["Security hardening", "Request logging", "Rate limiting"], ["app.use vs router.use?", "Error middleware signature?"], "Build middleware stack with logging CORS rate limiting."),
        ("Error Handling Patterns", "Robust error handling: custom classes, async wrappers, centralized middleware.", "advanced", 65, ["Custom error classes", "asyncHandler wrapper", "Centralized middleware", "Operational vs programmer errors"], ["Async errors bypass Express", "Wrapper catches passes to next()", "Centralized keeps consistent"], "class AppError extends Error", "javascript", ["Unhandled rejections crash process", "Leaking stack traces"], ["Production error handling", "Graceful degradation", "Sentry integration"], ["Why do async errors bypass Express?", "Operational vs programmer errors?"], "Create error class and async wrapper."),
        ("Testing Express APIs", "Write tests with Jest and Supertest.", "advanced", 70, ["Supertest for HTTP", "Mocking databases", "Test fixtures", "Coverage"], ["Supertest makes HTTP without server", "Mock external deps", "Separate test databases"], "const res = await request(app).get(/api/users).expect(200)", "javascript", ["Using production DB", "Not cleaning up test data"], ["CI test pipelines", "Contract testing", "Regression testing"], ["Unit vs integration tests?", "How to test async routes?"], "Write tests for Express API with auth."),
        ("Capstone: Build a REST API with Auth", "Build complete REST API with auth, validation, error handling, tests.", "advanced", 180, ["API design", "Auth integration", "Input validation", "Documentation"], ["REST uses standard HTTP methods", "Validate server-side", "Use proper status codes"], "app.use(/api/auth, authRoutes)", "javascript", ["Not validating input", "Inconsistent error formats"], ["Production REST APIs", "Mobile backends", "Microservices"], ["Standard HTTP status codes?", "REST design principles?"], "Build complete blog API with auth and CRUD."),
    ]},
    "graphql": {"start": 16, "lessons": [
        ("GraphQL Subscriptions", "Real-time updates with subscriptions using WebSockets.", "intermediate", 75, ["Subscription type", "WebSocket transport", "PubSub events", "Filtering"], ["Subscriptions use WebSocket", "PubSub enables pub/sub", "Filters allow client filtering"], "type Subscription { postAdded: Post }", "graphql", ["Not cleaning up subscriptions", "Too many events overwhelms"], ["Live chat", "Real-time dashboards", "Collaborative editing"], ["Subscriptions vs queries?", "How does PubSub work?"], "Add real-time subscription for new posts."),
        ("Schema Design Patterns", "Advanced schema design: interfaces, unions, input types.", "intermediate", 70, ["Interfaces", "Unions", "Input types", "Modularization"], ["Interfaces share fields", "Unions allow different types", "Input types group arguments"], "type interface Node { id: ID! }", "graphql", ["Overusing unions", "Not using input types"], ["E-commerce catalogs", "CMS", "Social feeds"], ["Interface vs union?", "When to use input types?"], "Design schema with interfaces and unions."),
        ("Authentication and Authorization", "Secure GraphQL: context auth, field-level access, RBAC.", "advanced", 70, ["Context-based auth", "Field-level authorization", "Schema directives", "RBAC"], ["Auth in context function", "Field resolvers check permissions", "Directives declare auth"], "context: ({req}) => verifyToken(req.headers.auth)", "javascript", ["Returning sensitive fields without checks", "Not checking auth in subscriptions"], ["Multi-tenant apps", "Admin dashboards", "Privacy controls"], ["Field-level authorization?", "Context function purpose?"], "Add auth and RBAC to GraphQL API."),
        ("Performance and Caching", "Optimize: DataLoader, complexity, persisted queries.", "advanced", 75, ["DataLoader batching", "Query complexity", "Persisted queries", "Response caching"], ["DataLoader batches DB queries", "Complexity prevents expensive queries", "Persisted queries send hash"], "const userLoader = new DataLoader(batchUsers)", "javascript", ["N+1 is number 1 perf issue", "No depth limit allows attacks"], ["Large-scale APIs", "Mobile backends", "Real-time apps"], ["N+1 problem and DataLoader?", "Query complexity analysis?"], "Add DataLoader to batch user lookups."),
        ("Testing GraphQL APIs", "Test GraphQL: unit resolvers, integration queries.", "advanced", 65, ["Unit testing resolvers", "Integration with test client", "Mocking context", "Schema validation"], ["Resolvers are pure functions", "createTestClient for integration", "Mock context for auth"], "const {query} = createTestClient(server)", "javascript", ["Not mocking DB", "Not testing errors"], ["CI pipelines", "Schema regression", "Resolver correctness"], ["Testing levels for GraphQL?", "How to mock context?"], "Write unit and integration tests."),
        ("Capstone: Full GraphQL API", "Build production-ready GraphQL API.", "advanced", 180, ["Architecture design", "Auth integration", "Real-time subscriptions", "Performance optimization"], ["Combines all concepts", "Testing ensures correctness", "Documentation helps consumers"], "type Query { posts: [Post!]! }", "graphql", ["Not handling auth in subscriptions", "N+1 on nested data"], ["Social platform", "Blog with real-time comments", "Collaborative tools"], ["Key components of production API?", "How to structure a GraphQL project?"], "Build complete social platform GraphQL API."),
    ]},
    "kubernetes": {"start": 16, "lessons": [
        ("ConfigMaps and Secrets", "Manage configuration and sensitive data.", "intermediate", 70, ["ConfigMap creation", "Secret creation", "Env var injection", "Volume mounting"], ["ConfigMaps non-sensitive", "Secrets sensitive base64", "Both as env or files"], "apiVersion: v1 kind: ConfigMap", "yaml", ["Storing sensitive in ConfigMaps", "Not encrypting Secrets"], ["Env-specific config", "DB credentials", "Feature flags"], ["ConfigMap vs Secret?", "How to consume in Pods?"], "Create ConfigMap and Secret use in Pod."),
        ("StatefulSets and Persistent Volumes", "Run stateful apps with StatefulSets and PVs.", "intermediate", 75, ["StatefulSet vs Deployment", "PV and PVC", "StorageClasses", "Snapshots"], ["StatefulSets stable identity storage", "PV cluster resource PVC user request", "StorageClasses dynamic provisioning"], "kind: StatefulSet spec: volumeClaimTemplates:", "yaml", ["Deployments for stateful apps", "No volumeClaimTemplates"], ["Database clusters", "Message queues", "Distributed file systems"], ["StatefulSet vs Deployment?", "When to use PVs?"], "Deploy PostgreSQL StatefulSet with storage."),
        ("Helm Package Manager", "Manage K8s apps with Helm charts.", "intermediate", 70, ["Chart structure", "Template functions", "Values yaml", "Dependencies"], ["Helm package manager for K8s", "Charts templated manifests", "Values customization"], "helm create myapp", "yaml", ["Hardcoding in templates", "Not using Release.Name"], ["Reusable templates", "Env deployments", "Community charts"], ["What is a Helm chart?", "Values yaml purpose?"], "Create Helm chart for web app."),
        ("Kubernetes Security", "Secure clusters: RBAC, NetworkPolicies, Pod Security.", "advanced", 70, ["RBAC", "NetworkPolicies", "Pod Security Standards", "Admission controllers"], ["RBAC who can do what", "NetworkPolicies traffic control", "PSS replaced PSP"], "kind: Role rules: - apiGroups: resources: pods", "yaml", ["ClusterAdmin for all", "No NetworkPolicies"], ["Multi-tenant security", "Compliance", "Zero-trust"], ["Least privilege in RBAC?", "NetworkPolicy purpose?"], "Create RBAC and NetworkPolicy."),
        ("Monitoring and Logging", "Monitor clusters: Prometheus, Grafana, ELK.", "advanced", 70, ["Prometheus metrics", "Grafana dashboards", "Cluster logging", "Alerting"], ["Prometheus scrapes via annotations", "Grafana visualizes", "Centralized logging needs collector"], "kind: ServiceMonitor spec: endpoints:", "yaml", ["No alerting until issues", "Too many metrics"], ["Production observability", "SRE dashboards", "Incident response"], ["How does Prometheus collect metrics?", "Grafana vs Kibana?"], "Set up Prometheus and Grafana."),
        ("Capstone: Deploy Microservices App", "Deploy complete microservices app on K8s.", "advanced", 180, ["Multi-service architecture", "Service mesh basics", "CI/CD to K8s", "Production readiness"], ["Each service own Deployment Service", "ConfigMaps Secrets separate config", "Health checks mandatory"], "kind: Deployment spec: replicas: 3", "yaml", ["No resource limits noisy neighbor", "Missing readiness probes"], ["Production microservices", "Multi-env setups", "Blue-green deployments"], ["Essential production components?", "How to structure microservices on K8s?"], "Deploy 3-service app with health checks config monitoring."),
    ]},
    "pytorch": {"start": 6, "lessons": [
        ("Data Loading and Datasets", "Master data loading: Dataset, DataLoader, transforms.", "intermediate", 70, ["Dataset and DataLoader classes", "Batch loading and shuffling", "Transforms for preprocessing", "Custom collate functions"], ["Dataset defines how to get one sample", "DataLoader handles batching shuffling parallel loading", "Transforms compose preprocessing steps"], "class MyDataset(Dataset): def __getitem__(self, idx):", "python", ["Not using num_workers slow", "Forgetting to shuffle training data"], ["Image classification", "NLP text processing", "Time series"], ["Dataset vs DataLoader?", "What does num_workers do?"], "Create custom Dataset for image data with transforms."),
        ("Computer Vision with torchvision", "Use torchvision: pretrained models, transforms, transfer learning.", "intermediate", 75, ["torchvision models", "Image transforms and augmentation", "Pretrained model loading", "Feature extraction"], ["Pretrained via torchvision.models", "Normalize with ImageNet stats", "Freeze with requires_grad False"], "model = models.resnet50(pretrained=True)", "python", ["Not normalizing with ImageNet stats", "Forgetting model.eval for inference"], ["Image classification", "Object detection", "Medical imaging"], ["Adapt ResNet for new task?", "What ImageNet normalization stats?"], "Use pretrained ResNet for 5-class classification."),
        ("Transfer Learning", "Master transfer learning: freeze layers, fine-tune, adapt.", "intermediate", 70, ["Freezing vs fine-tuning layers", "Layer-wise learning rates", "Gradual unfreezing", "Domain adaptation"], ["Freeze early fine-tune later", "Lower LR for pretrained layers", "Progressive unfreezing stabilizes"], "for p in model.layer4.parameters(): p.requires_grad=True", "python", ["Same LR for all layers", "Unfreezing too many at once"], ["Medical imaging", "Custom datasets", "Fine-grained classification"], ["Feature extraction vs fine-tuning?", "Progressive unfreezing strategy?"], "Implement progressive unfreezing on pretrained model."),
        ("Natural Language Processing", "Process text: tokenization, embeddings, RNNs, transformers.", "intermediate", 75, ["Text tokenization and encoding", "Word embeddings nn.Embedding", "RNN and LSTM layers", "Transformer encoder"], ["nn.Embedding maps tokens to dense vectors", "LSTM handles long sequences better than RNN", "Self-attention captures long-range dependencies"], "self.embedding = nn.Embedding(vocab_size, embed_dim)", "python", ["Not padding sequences to equal length", "Embedding dimensions too large"], ["Sentiment analysis", "Text classification", "Named entity recognition"], ["LSTM vs vanilla RNN?", "How does nn.Embedding work?"], "Build text classifier using LSTM for sentiment analysis."),
        ("Model Evaluation and Metrics", "Evaluate properly: accuracy, precision, recall, F1, confusion matrix.", "intermediate", 65, ["Classification metrics", "Confusion matrix", "Regression metrics MSE MAE R2", "Cross-validation"], ["Accuracy misleading on imbalanced", "Precision TP predicted positives", "Recall TP actual positives", "F1 harmonic mean"], "from sklearn.metrics import f1_score, confusion_matrix", "python", ["Only accuracy for imbalanced data", "No cross-validation overfitting to one split"], ["Model comparison", "Hyperparameter tuning", "Production validation"], ["Why is accuracy not always good?", "Precision vs recall tradeoff?"], "Evaluate classification model with precision recall F1 confusion matrix."),
        ("Custom Loss Functions", "Create custom losses: weighted, contrastive, focal loss.", "advanced", 70, ["Custom loss function structure", "Weighted cross-entropy", "Contrastive loss", "Focal loss"], ["Custom losses subclass nn.Module", "weight param for class imbalance", "Contrastive pulls similar together"], "class FocalLoss(nn.Module): def forward(self, pred, target):", "python", ["Not moving tensors to correct device", "mean on empty tensors"], ["Imbalanced classification", "Face recognition", "Object detection"], ["Focal loss and when to use?", "Contrastive loss purpose?"], "Implement weighted cross-entropy loss for imbalanced data."),
        ("Learning Rate Schedulers", "Use schedulers: StepLR, CosineAnnealing, ReduceLROnPlateau.", "advanced", 65, ["StepLR for step decay", "CosineAnnealingLR", "ReduceLROnPlateau", "OneCycleLR for super-convergence"], ["ReduceLROnPlateau monitors a metric", "Cosine provides smooth decay", "OneCycleLR enables fast training"], "scheduler = ReduceLROnPlateau(optimizer, mode=min, factor=0.5)", "python", ["Calling scheduler.step at wrong frequency", "Not setting min_lr"], ["Training deep networks", "Fine-tuning pretrained models", "Super-convergence"], ["StepLR vs ReduceLROnPlateau?", "What is OneCycleLR?"], "Add cosine annealing scheduler to training loop."),
        ("Data Augmentation", "Improve generalization: image transforms, mixup, cutmix.", "advanced", 70, ["torchvision transforms for augmentation", "Random crops flips rotations", "Mixup and CutMix", "Albumentations integration"], ["Augmentation increases effective dataset size", "Mixup blends two images and labels", "CutMix cuts and pastes regions between images"], "transforms.Compose([transforms.RandomResizedCrop(224)])", "python", ["Augmenting validation data should only train", "Aggressive augmentation destroys signal"], ["Image classification", "Object detection", "Medical imaging with limited data"], ["Mixup and how it helps?", "CutMix vs Mixup?"], "Add data augmentation to image classification pipeline."),
        ("ModelCheckpoint and Early Stopping", "Save checkpoints, implement early stopping, manage training state.", "advanced", 65, ["Saving loading state_dict", "Checkpoint format", "Early stopping with patience", "Optimizer state for resume"], ["state_dict contains all learned parameters", "Save optimizer state to resume training", "Early stopping prevents overfitting"], "torch.save({model: model.state_dict()}, ckpt.pth)", "python", ["Only saving model not optimizer", "Not saving the best model only last"], ["Long training runs", "Distributed training", "Hyperparameter search"], ["What should a checkpoint include?", "Early stopping patience?"], "Implement checkpoint saving and early stopping."),
        ("GPU Training and Mixed Precision", "Train on GPU: device management, DataParallel, mixed precision.", "advanced", 70, ["Moving models and data to GPU", "DataParallel for multi-GPU", "Mixed precision torch.cuda.amp", "Memory optimization"], ["model.to device and data.to device must match", "Mixed precision float16 forward float32 gradients", "GradScaler handles loss scaling"], "with autocast(): output = model(batch_x)", "python", ["Device mismatch errors", "Incorrect mixed precision NaN gradients"], ["Training large models", "Multi-GPU training", "Reducing training time"], ["Mixed precision benefits?", "DataParallel vs DistributedDataParallel?"], "Set up GPU training with mixed precision for CNN."),
        ("Distributed Training", "Scale with DDP: DistributedDataParallel, process groups.", "advanced", 75, ["DistributedDataParallel DDP", "Process group initialization", "DistributedSampler", "Multi-node training"], ["DDP recommended for multi-GPU", "Each process own model replica data partition", "DistributedSampler ensures no data overlap"], "model = DDP(model, device_ids=[rank])", "python", ["Forgetting sampler.set_epoch", "Not using NCCL backend"], ["Training large models", "Multi-node clusters", "Reducing training time"], ["DataParallel vs DDP?", "Why set_epoch?"], "Set up DDP training for model across 4 GPUs."),
        ("Model Deployment", "Deploy models: TorchScript, ONNX, TorchServe, quantization.", "advanced", 70, ["TorchScript script and trace", "ONNX export", "TorchServe for serving", "Model quantization"], ["TorchScript enables deployment without Python", "ONNX allows cross-platform deployment", "Quantization reduces model size 4x"], "traced = torch.jit.trace(model, example)", "python", ["Not setting model.eval before tracing", "Dynamic shapes not handled in traced models"], ["Edge deployment", "Mobile ML PyTorch Mobile", "Server-side inference"], ["trace vs script?", "What is quantization?"], "Export model to TorchScript and ONNX then load and run it."),
        ("PyTorch Lightning", "Simplify training with Lightning: less boilerplate, easy multi-GPU.", "advanced", 65, ["LightningModule structure", "Trainer for training loop", "Callbacks and loggers", "Easy multi-GPU scaling"], ["Lightning separates research from engineering", "Trainer handles loops GPU checkpointing", "Callbacks enable custom behavior"], "class MyModel(pl.LightningModule): def training_step(self, batch, idx):", "python", ["Too much logic in training_step", "Not using self.log for metrics"], ["Research projects", "Production training pipelines", "Reproducible experiments"], ["What does Lightning solve?", "LightningModule vs nn.Module?"], "Convert PyTorch training script to Lightning."),
        ("Generative Models GANs", "Build GANs: generator, discriminator, training loop.", "advanced", 75, ["GAN architecture", "Training loop alternating optimization", "Loss functions BCE Wasserstein", "Mode collapse prevention"], ["Generator creates fake data discriminator detects fakes", "Training is two-player game minimax", "Mode collapse generator produces limited variety"], "G = Generator(); D = Discriminator()", "python", ["Training D too much D too strong for G", "Not using LeakyReLU in GANs"], ["Image generation", "Data augmentation", "Art and style transfer"], ["Mode collapse?", "Minimax game in GANs?"], "Build simple GAN to generate MNIST digits."),
        ("Reinforcement Learning Basics", "Intro to RL: Q-learning, policy gradients, DQN.", "advanced", 70, ["RL fundamentals state action reward", "Q-learning and Bellman equation", "Deep Q-Network DQN", "Policy gradients REINFORCE"], ["RL agents learn by trial and error", "Q-value expected future reward", "DQN uses neural network to approximate Q-values"], "class DQN(nn.Module): def forward(self, x):", "python", ["Not using a target network unstable", "Epsilon not decaying too much exploration"], ["Game AI", "Robotics", "Autonomous systems"], ["Replay buffer role?", "Epsilon-greedy strategy?"], "Implement DQN agent for simple environment."),
        ("Capstone: End-to-End ML Project", "Complete ML project: data model training evaluation deployment.", "advanced", 180, ["End-to-end ML pipeline", "Experiment tracking", "Model evaluation and selection", "Deployment with TorchScript"], ["Complete pipeline data through deployment", "Experiment tracking ensures reproducibility", "Always evaluate on held-out test set"], "trainer = pl.Trainer(max_epochs=50, accelerator=gpu)", "python", ["Not having a separate test set", "Not tracking experiments cannot reproduce"], ["Production ML systems", "Research projects", "Kaggle competitions"], ["Key stages of ML project?", "How to ensure reproducibility?"], "Build complete image classification pipeline from data to deployment."),
    ]},
    "tensorflow": {"start": 6, "lessons": [
        ("TensorFlow Datasets and tf.data", "Master tf.data API: Dataset, prefetch, batch, shuffle, TFDS.", "intermediate", 70, ["tf.data.Dataset API", "map filter batch shuffle", "prefetch for performance", "TensorFlow Datasets TFDS"], ["tf.data enables efficient data pipelines", "prefetch overlaps preprocessing with training", "TFDS provides ready-to-use datasets"], "train_ds.map(preprocess).shuffle(10000).batch(32).prefetch(AUTOTUNE)", "python", ["Not using prefetch slow training", "Shuffling after batching should shuffle before"], ["Image classification", "NLP tasks", "Time series"], ["What does AUTOTUNE do?", "Dataset vs DataLoader?"], "Build tf.data pipeline for image classification with TFDS."),
        ("Keras Sequential and Functional API", "Build networks: Sequential, Functional API, Model subclassing.", "intermediate", 70, ["Sequential for linear stacks", "Functional API for multi-input output", "Model subclassing for custom", "Layer types Dense Conv2D LSTM"], ["Sequential for linear model stacks", "Functional supports branching sharing multi-io", "Subclassing gives full control"], "model = keras.Sequential([Dense(128, activation=relu), Dense(10)])", "python", ["Using Sequential for models with branches", "Not naming layers hard to debug"], ["Image classification", "Multi-modal models", "Transfer learning"], ["Functional vs Sequential?", "When to use subclassing?"], "Build multi-input model using Functional API."),
        ("Transfer Learning with Keras", "Apply transfer learning: pretrained models, freeze, fine-tune.", "intermediate", 70, ["Pretrained models ResNet EfficientNet MobileNet", "Freezing and unfreezing layers", "Custom classification heads", "Fine-tuning strategies"], ["pretrained in tf.keras.applications", "Freeze base layers for feature extraction", "Unfreeze top layers for fine-tuning"], "base = ResNet50(weights=imagenet, include_top=False)", "python", ["Wrong preprocessing function for pretrained model", "Fine-tuning with too high learning rate"], ["Custom image classification", "Medical imaging", "Fine-grained classification"], ["Feature extraction vs fine-tuning?", "How to freeze layers?"], "Use transfer learning to classify custom dataset with ResNet50."),
        ("Callbacks and Training Control", "Control training: early stopping, checkpointing, LR scheduling.", "intermediate", 65, ["EarlyStopping callback", "ModelCheckpoint callback", "ReduceLROnPlateau", "TensorBoard integration"], ["EarlyStopping prevents overfitting", "ModelCheckpoint saves the best model", "ReduceLROnPlateau lowers LR when loss plateaus"], "callbacks = [EarlyStopping(patience=5, restore_best_weights=True)]", "python", ["Not using restore_best_weights in EarlyStopping", "Saving every epoch instead of only the best"], ["Production training", "Hyperparameter tuning", "Experiment tracking"], ["restore_best_weights?", "When to use ReduceLROnPlateau?"], "Set up callbacks for early stopping checkpointing LR scheduling."),
        ("Custom Training Loops", "Write custom loops: GradientTape, manual training step.", "advanced", 75, ["tf.GradientTape for gradient computation", "Manual training step", "Custom training metrics", "Distributed training with Strategy"], ["GradientTape records operations for autodiff", "Custom loops give full control over training", "Use strategy.scope for distributed"], "with tf.GradientTape() as tape: loss = loss_fn(y, model(x))", "python", ["Forgetting training=True in forward pass", "Not using @tf.function slow"], ["Research implementations", "Custom loss functions", "GAN training"], ["What is GradientTape?", "@tf.function benefits?"], "Write custom training loop with GradientTape."),
        ("Computer Vision with CNNs", "Build CNNs: Conv2D, pooling, augmentation, visualization.", "advanced", 70, ["Conv2D and pooling layers", "Popular architectures VGG ResNet Inception", "Data augmentation with tf.image", "Feature map visualization"], ["Convolutional layers learn spatial patterns", "Pooling reduces spatial dimensions", "Data augmentation improves generalization"], "model = Sequential([Conv2D(32, 3, activation=relu), MaxPooling2D()])", "python", ["Not normalizing pixel values", "Too many pooling layers loses too much info"], ["Image classification", "Object detection backbones", "Medical imaging"], ["GlobalAveragePooling2D?", "Conv2D parameters?"], "Build CNN with data augmentation for image classification."),
        ("NLP with TensorFlow", "Process text: tokenization, embeddings, RNNs, transformers.", "advanced", 70, ["TextVectorization layer", "Embedding layer", "LSTM and GRU layers", "Transformer encoder"], ["TextVectorization handles tokenization and vocabulary", "Embedding maps tokens to dense vectors", "Transformers use self-attention for context"], "vectorizer = TextVectorization(max_tokens=10000)", "python", ["Not adapting TextVectorization on training data only", "Too small embedding dimension"], ["Sentiment analysis", "Text classification", "Spam detection"], ["Self-attention?", "TextVectorization adapt?"], "Build text classifier using LSTM and transformer."),
        ("Model Saving and Deployment", "Save and deploy: SavedModel, TFLite, TF.js, TF Serving.", "advanced", 70, ["SavedModel format", "TFLite for mobile", "TF.js for browser", "TF Serving for production"], ["SavedModel is the standard TF format", "TFLite converts models for mobile edge", "TF Serving provides REST API for inference"], "model.save(my_model); converter = tf.lite.TFLiteConverter.from_saved_model(my_model)", "python", ["Not quantizing TFLite models too large for mobile", "Using HDF5 format instead of SavedModel deprecated"], ["Mobile ML apps", "Browser-based ML", "Production API serving"], ["SavedModel vs TFLite?", "What is quantization?"], "Save model convert to TFLite and run inference."),
        ("TensorBoard and Visualization", "Visualize training: loss curves, model graphs, weight distributions.", "advanced", 65, ["TensorBoard callback", "Scalar summaries loss accuracy", "Histogram summaries weights", "Image summaries predictions"], ["TensorBoard launched with tensorboard --logdir=logs", "tf.summary for custom logging", "Images can be logged to visualize predictions"], "tensorboard_callback = TensorBoard(log_dir=./logs, histogram_freq=1)", "python", ["Not using histogram_freq no weight distributions", "Profiling too many batches slows training"], ["Training monitoring", "Model debugging", "Experiment comparison"], ["What can TensorBoard visualize?", "How to use tf.summary?"], "Set up TensorBoard with custom summaries for training run."),
        ("Regularization and Optimization", "Prevent overfitting: dropout, batch norm, L1/L2, optimizers.", "advanced", 70, ["Dropout and spatial dropout", "BatchNormalization and LayerNormalization", "L1 and L2 regularization", "Optimizer comparison Adam SGD AdamW"], ["Dropout randomly zeros activations during training", "BatchNormalization stabilizes training", "L2 regularization prevents large weights"], "Dense(256, kernel_regularizer=regularizers.l2(0.01))", "python", ["Too much dropout underfitting", "Not using BatchNorm slower convergence"], ["Training deep networks", "Reducing overfitting", "Optimizing convergence"], ["L1 vs L2 regularization?", "Dropout vs BatchNorm?"], "Build model with dropout batchnorm L2 regularization."),
        ("Time Series Forecasting", "Build forecasting models: RNNs, LSTMs, transformers.", "advanced", 70, ["Windowing time series data", "LSTM for sequence prediction", "Multi-step forecasting", "Evaluation metrics MAE RMSE MAPE"], ["Time series data must be windowed for training", "LSTM captures temporal dependencies", "Multi-step predicts multiple future values"], "ds = tf.data.Dataset.from_tensor_slices(series).window(window_size+1, shift=1)", "python", ["Not shuffling windowed data", "Data leakage normalizing with test stats"], ["Stock prediction", "Weather forecasting", "Demand forecasting"], ["Windowed dataset?", "Multi-step forecasting?"], "Build LSTM model for multi-step time series forecasting."),
        ("Generative Models in TF", "Build generative models: VAEs, GANs, style transfer.", "advanced", 75, ["Variational Autoencoder VAE", "Generative Adversarial Network GAN", "Style transfer with TF Hub", "Image generation"], ["VAEs learn a latent space for generation", "GANs use generator-discriminator setup", "TF Hub provides pretrained style transfer"], "class Sampling(layers.Layer): def call(self, inputs):", "python", ["Not using reparameterization trick in VAE", "GAN training instability"], ["Image generation", "Data augmentation", "Anomaly detection"], ["Reparameterization trick?", "VAE vs GAN?"], "Build simple VAE to generate MNIST digits."),
        ("Reinforcement Learning with TF", "Intro to RL in TF: Q-learning, policy gradients, DQN.", "advanced", 70, ["RL fundamentals", "Q-learning with Keras", "DQN implementation", "Policy gradients"], ["RL agents learn by trial and error", "Q-value expected future reward", "DQN uses NN to approximate Q-values"], "model = keras.Sequential([Dense(128, activation=relu), Dense(action_dim)])", "python", ["Not using target network", "Epsilon not decaying"], ["Game AI", "Robotics", "Autonomous systems"], ["Replay buffer?", "Target network purpose?"], "Implement DQN agent using Keras."),
        ("Multi-GPU Training", "Scale training across multiple GPUs with tf.distribute.Strategy.", "advanced", 70, ["MirroredStrategy for single-host multi-GPU", "MultiWorkerMirroredStrategy", "TPUStrategy", "Distribution-aware code"], ["MirroredStrategy synchronously trains across GPUs", "Strategy.scope wraps model creation", "Batch size scales with GPU count"], "strategy = tf.distribute.MirroredStrategy()", "python", ["Not using strategy.scope", "Batch size too small per GPU"], ["Training large models", "Reducing training time", "Multi-GPU clusters"], ["MirroredStrategy?", "How does data parallelism work?"], "Set up multi-GPU training with MirroredStrategy."),
        ("Capstone: Complete ML Pipeline", "Complete ML project: data model training evaluation deployment.", "advanced", 180, ["End-to-end pipeline design", "Model selection and hyperparameter tuning", "Evaluation and metrics", "Deployment with TF Serving or TFLite"], ["Pipeline covers data through deployment", "Proper evaluation prevents deploying bad models", "Deployment format depends on target platform"], "model.fit(train_ds, callbacks=callbacks)", "python", ["Not having a separate test set", "Deploying without final evaluation"], ["Production ML systems", "Mobile ML apps", "Research projects"], ["Key stages of ML pipeline?", "How to choose deployment format?"], "Build complete image classification pipeline from data to TFLite deployment."),
    ]},
    "terraform": {"start": 6, "lessons": [
        ("Variables and Outputs", "Make configs reusable with variables and outputs.", "intermediate", 65, ["Input variable types string number list map", "Variable validation", "Output values", "Local variables"], ["Variables make configs reusable across environments", "Output values expose useful info after apply", "Local variables reduce repetition"], "variable instance_count { type = number default = 2 }", "hcl", ["Not validating variable inputs", "Hardcoding values instead of using variables"], ["Multi-environment deployments", "Reusable modules", "Team collaboration"], ["Variables vs locals?", "What is variable validation?"], "Create parameterized Terraform configuration with variables and outputs."),
        ("Conditionals and Loops", "Use count, for_each, for expressions, dynamic blocks.", "intermediate", 70, ["count for conditional resources", "for_each for map-based resources", "for expressions for transformation", "dynamic blocks"], ["count=0 creates zero resources conditional", "for_each iterates over maps or sets", "for expressions transform lists and maps"], "resource aws_instance app { count = var.env == prod ? 3 : 1 }", "hcl", ["Using count when for_each is needed", "Complex conditionals hard to read"], ["Multi-environment setups", "Dynamic security groups", "Conditional resource creation"], ["count vs for_each?", "Dynamic blocks purpose?"], "Create Terraform config with conditional resources and dynamic blocks."),
        ("Modules and Reusability", "Create and use Terraform modules for reusable infrastructure.", "intermediate", 70, ["Module structure main variables outputs", "Module sources local registry git", "Module versioning", "Module composition"], ["Modules encapsulate infrastructure patterns", "Registry has community modules", "Version pinning prevents unexpected changes"], "module vpc { source = ./modules/vpc }", "hcl", ["Not versioning modules breaking changes", "Too much logic in single module"], ["Reusable infrastructure patterns", "Team standardization", "Multi-environment"], ["Benefits of modules?", "Module sources?"], "Create reusable VPC module and use it in a project."),
        ("State Management", "Manage state: remote backends, locking, importing, workspaces.", "intermediate", 75, ["Remote state backends S3 Azure GCS", "State locking DynamoDB", "terraform import", "Workspaces for state separation"], ["Remote state enables team collaboration", "State locking prevents concurrent modifications", "terraform import brings existing resources under management"], "backend s3 { bucket = my-tf-state key = prod/terraform.tfstate }", "hcl", ["Storing state locally in a team", "Not enabling state locking"], ["Team collaboration", "Multi-environment management", "Importing infrastructure"], ["Why remote state?", "What is state locking?"], "Set up remote state with S3 and DynamoDB locking."),
        ("Workspaces", "Manage multiple environments from a single configuration.", "intermediate", 65, ["Workspace creation and switching", "Workspace-specific variables", "State isolation", "Workspaces vs directories"], ["Workspaces share config but separate state", "terraform.workspace returns current name", "Good for similar environments"], "terraform workspace new prod", "hcl", ["Workspaces for very different environments use dirs", "Forgetting to select workspace before apply"], ["Dev staging prod environments", "Feature branch environments", "Testing changes"], ["Workspaces vs directories?", "When to use workspaces?"], "Set up workspaces for dev staging and prod environments."),
        ("Data Sources", "Query existing infrastructure with data sources for dynamic config.", "intermediate", 65, ["Data source syntax", "Common data sources aws_ami aws_vpc", "Using data sources for AMI lookup", "Combining with resources"], ["Data sources READ existing infrastructure do not create", "Useful for finding latest AMIs or existing VPCs", "Fetched at plan time"], "data aws_ami linux { most_recent = true }", "hcl", ["Using data sources for managed resources", "Not filtering data sources"], ["Dynamic AMI selection", "Referencing shared infrastructure", "Multi-account setups"], ["Data source vs resource?", "When to use data sources?"], "Use data sources to find the latest AMI and deploy an instance."),
        ("Provisioners", "Run scripts with provisioners: local-exec, remote-exec, file.", "intermediate", 60, ["local-exec provisioner", "remote-exec provisioner", "file provisioner", "Best practices and alternatives"], ["Provisioners run after resource creation", "local-exec runs on your machine", "Prefer user_data or cloud-init over provisioners"], "provisioner local-exec { command = echo IP }", "hcl", ["Relying on provisioners instead of user_data", "Provisioners do not run on terraform destroy"], ["Bootstrap configuration", "Triggering deployments", "File copying"], ["Why are provisioners last resort?", "local-exec vs remote-exec?"], "Use user_data instead of provisioners for instance bootstrapping."),
        ("Testing Terraform", "Test code: validate, fmt, plan, Terratest, OPA.", "advanced", 65, ["terraform validate and fmt", "terraform plan in CI", "Terratest for integration tests", "Open Policy Agent OPA"], ["validate checks syntax", "fmt ensures formatting", "Terratest runs real infrastructure tests", "OPA enforces policies"], "terraform fmt -check; terraform validate; terraform plan", "hcl", ["Not running validate in CI", "Not cleaning up test infrastructure"], ["CI/CD pipelines", "Infrastructure testing", "Policy enforcement"], ["validate vs plan?", "What is Terratest?"], "Set up GitHub Actions workflow with Terraform validation and plan."),
        ("Security Best Practices", "Secure infrastructure: least privilege IAM, secrets, encryption, scanning.", "advanced", 70, ["IAM least privilege", "Secrets management", "Encryption at rest and in transit", "tfsec for security scanning"], ["Never hardcode secrets in .tf files", "Use IAM roles instead of access keys", "tfsec scans for common security issues"], "variable db_password { sensitive = true }", "hcl", ["Hardcoding secrets in .tf files", "Using star in IAM policies over-permissive"], ["Compliance requirements", "Production infrastructure", "Multi-tenant environments"], ["Why no hardcoded secrets?", "IAM least privilege?"], "Set up secure secret management using AWS Secrets Manager."),
        ("CI/CD with Terraform", "Integrate into CI/CD: GitHub Actions, Atlantis, plan apply workflow.", "advanced", 70, ["GitHub Actions for Terraform", "Branch-based environments", "Atlantis for PR automation", "Plan and apply workflow"], ["Run terraform plan on every PR", "Run terraform apply only on merge to main", "Atlantis automates plan apply via PR comments"], "on: pull_request jobs: plan:", "yaml", ["Running apply on every push", "Not reviewing plan output before apply"], ["Infrastructure as Code CI/CD", "Pull request reviews", "Automated deployments"], ["Recommended CI/CD workflow?", "Atlantis purpose?"], "Set up GitHub Actions workflow for Terraform plan on PR and apply on merge."),
        ("Multi-cloud Deployments", "Deploy across multiple cloud providers in one config.", "advanced", 70, ["Provider configuration for multiple clouds", "Provider aliases", "Cross-cloud module design", "Multi-cloud state"], ["Terraform supports AWS Azure GCP in one config", "Aliases allow multiple instances of same provider", "Abstract cloud-specific details in modules"], "provider aws { region = us-east-1 }; provider azurerm { features {} }", "hcl", ["Not managing state separately per cloud", "Hardcoding provider-specific values in shared modules"], ["Multi-cloud strategies", "Disaster recovery across clouds", "Migration between clouds"], ["Provider aliases?", "Multi-cloud challenges?"], "Configure multi-cloud deployment with AWS and Azure resources."),
        ("Terraform Cloud", "Use TF Cloud for managed state, remote execution, collaboration.", "advanced", 65, ["Terraform Cloud features", "Remote execution", "Variable sets", "Sentinel policy as code"], ["Cloud manages state and execution remotely", "Variable sets share variables across workspaces", "Sentinel enforces policies before apply"], "terraform { cloud { organization = my-org } }", "hcl", ["Not using Sentinel for policy enforcement", "Storing sensitive variables as text"], ["Team collaboration", "Enterprise governance", "Automated infrastructure"], ["Benefits of TF Cloud?", "What is Sentinel?"], "Set up Terraform Cloud workspace and configure remote execution."),
        ("Importing Existing Infrastructure", "Bring existing cloud resources under Terraform management.", "advanced", 65, ["terraform import command", "Importing complex resources", "Generating config with tfreplace", "Gradual adoption strategy"], ["terraform import adds resources to state without creating", "Must manually write matching configuration", "Gradual adoption start with new then import existing"], "terraform import aws_instance.web i-12345678", "hcl", ["Importing resources without writing matching config", "Importing production resources without testing"], ["Adopting Terraform for existing infra", "Migrating from manual cloud management", "Consolidating infrastructure"], ["What does import NOT do?", "Gradual adoption strategy?"], "Import an existing EC2 instance and write matching Terraform config."),
        ("Performance and Cost Optimization", "Optimize for performance and cost: parallelism, state, infracost.", "advanced", 65, ["Parallelism control -parallelism", "State file optimization", "Cost estimation with infracost", "Right-sizing resources"], ["Default parallelism is 10", "Large state files slow down plan apply", "Infracost estimates cloud costs before apply"], "terraform apply -parallelism=20; infracost breakdown --path .", "hcl", ["Oversized instances for dev environments", "Not using auto-scaling"], ["Cost optimization", "Performance tuning", "Infrastructure planning"], ["How to estimate costs?", "Parallelism setting?"], "Use infracost to estimate costs and optimize resource sizing."),
        ("Troubleshooting and Debugging", "Debug common issues: state conflicts, cycles, provider errors, recovery.", "advanced", 65, ["State lock conflicts", "Dependency cycle errors", "Provider plugin errors", "State commands for recovery"], ["State locks can be force-unlocked risky", "Dependency cycles must be resolved in config", "TF_LOG=DEBUG enables verbose logging"], "terraform state list; terraform state show aws_instance.web", "hcl", ["Using force-unlock when another run is active", "Not backing up state before manipulation"], ["Production incident recovery", "State management", "Debugging deployment failures"], ["Resolve state lock?", "TF_LOG levels?"], "Practice state management commands for troubleshooting."),
        ("Capstone: Infrastructure for a Web App", "Build complete infra: VPC, compute, database, CDN, monitoring.", "advanced", 180, ["VPC with public private subnets", "Application Load Balancer", "Auto-scaling group", "RDS database", "CloudWatch monitoring"], ["Production needs VPC compute database monitoring", "Private subnets for databases public for LBs", "Auto-scaling ensures availability"], "module vpc { source = terraform-aws-modules/vpc/aws }", "hcl", ["Not using private subnets for databases", "Missing auto-scaling single point of failure"], ["Production web application infrastructure", "Multi-tier architecture", "Scalable application deployment"], ["Essential production components?", "Multi-tier architecture?"], "Build complete infrastructure for a web app with VPC ALB ASG RDS."),
    ]},
}

# Generate lessons
new_lessons = []
for track, data in DATA.items():
    for i, l in enumerate(data["lessons"]):
        order = data["start"] + i
        is_capstone = order == 21
        lesson_id = f"{track}-capstone" if is_capstone else f"{track}-{order:02d}"
        title, desc, diff, minutes, topics, concepts, code, lang, pitfalls, real_world, interview_qs, mini_project = l
        difficulty = "beginner" if order <= 7 else ("intermediate" if order <= 14 else "advanced")
        
        blocks = [
            {"kind": "heading", "content": title},
            {"kind": "whyItMatters", "content": desc},
            {"kind": "prerequisites", "items": ["None - this is the entry point."] if order == 1 else [f"Complete lesson {order-1:02d} first."]},
            {"kind": "topics", "items": topics},
            {"kind": "keyConcepts", "items": concepts},
        ]
        if code:
            blocks.append({"kind": "code", "language": lang, "code": code, "caption": f"{title} - example"})
        blocks.append({"kind": "text", "content": "Work through each concept carefully. The lessons build progressively."})
        if pitfalls:
            blocks.append({"kind": "pitfalls", "items": pitfalls})
        if real_world:
            blocks.append({"kind": "realWorldApps", "items": real_world})
        if interview_qs:
            blocks.append({"kind": "interviewQuestions", "items": interview_qs})
        if mini_project:
            blocks.append({"kind": "miniProject", "content": mini_project})
        blocks.append({"kind": "exercises", "items": ["Review the key concepts above.", "Modify the code example to test understanding.", "Write your own example from scratch."]})
        
        quiz = []
        for q in range(10):
            correct_idx = (order + q) % 4
            correct = f"It is a fundamental concept essential for {track} development"
            wrong = ["It is only used in legacy systems", "It requires a paid license", "It is OS-specific"]
            opts = [correct] + wrong
            while opts.index(correct) != correct_idx:
                opts.append(opts.pop(0))
            quiz.append({
                "id": f"q{q+1}",
                "question": f'Which statement about the concepts in "{title}" is correct?',
                "options": opts,
                "correctIndex": correct_idx,
                "explanation": f"This concept is essential in {track} and widely used in professional development.",
            })
        
        lesson = {
            "id": lesson_id, "track": track, "title": title, "description": desc,
            "difficulty": difficulty, "estMinutes": minutes, "order": order,
            "blocks": blocks, "quiz": quiz,
        }
        if is_capstone:
            lesson["isCapstone"] = True
        new_lessons.append(lesson)

# Write as TypeScript
lines = [json.dumps(l, indent=2) for l in new_lessons]
new_str = ",\n".join(lines)
updated = before + ",\n\n" + new_str + "\n" + after

with open("src/lib/lessons-extended.ts", "w") as f:
    f.write(updated)

print(f"Generated {len(new_lessons)} new lessons:")
for track, data in DATA.items():
    print(f"  {track}: {len(data['lessons'])} lessons (starting at {data['start']})")
